{7226}{7340}There was once in venice|a moor othello who for
{7345}{7438}his merits in the affairs of war|was held in great esteem.
{7443}{7520}It happened that he fell in love|with a young and noble lady
{7526}{7555}called desdemona,
{7569}{7665}who drawn by his virtue,|became equally enamoured of him.
{7683}{7752}So it was that since her father|was much opposed to the union
{7752}{7853}of desdemona with a moor,|she fled her house at night.
{7866}{7927}In secret haste|they were married.
{7956}{8057}Now there was in othello's|company, an ensign named lago,
{8064}{8124}a very amiable outward appearance
{8131}{8188}but his character was|extremely treacherous.
{8197}{8350}I have told often and|i retell it again and again.
{8357}{8426}I hate the moore.
{8430}{8493}I'll poison his delight.
{8514}{8611}How? How, lago?
{8614}{8695}Proclaim him in the streets,|incense her kinsmen,
{8698}{8801}and though he in fertile climate|dwell, plague him with flies.
{8807}{8847}No, they come.
{8892}{8937}What will i do?
{8954}{8986}Why, go to bed and sleep.
{8994}{9063}- I'll incontinently drown myself.|Oh, bitterness.
{9072}{9101}What should i do?
{9105}{9134}Put money in thy purse.
{9150}{9209}Ere i would say i would drown|myself for love of a guinea
{9209}{9269}hen, i would change my|humanity with a baboon!
{9431}{9468}Come, be a man.
{9506}{9536}Drown thyself?
{9539}{9593}Drown cats and blind puppies.
{9638}{9716}It cannot be that desdemona|should long continue her love
{9719}{9768}to the moor or he his to her.
{9814}{9872}It was a violent commencement.
{9890}{9989}And thou shalt see an answerable|sequestration,
{10023}{10065}put buy money in thy purse.
{10076}{10121}When she is sated with his body
{10123}{10172}she'll fine the error|of her choice.
{10177}{10265}She must change, she must,|for youth.
{10346}{10371}Your daughter!
{10410}{10462}- Look, your house!|- Your house!
{10465}{10507}- Your daughter!|- Your daughter!
{10510}{10559}Senior, is all your family|within?
{10564}{10611}Why, wherefore ask you this?
{10616}{10649}Lf't be your pleasure for your|dull watch o' th' night,
{10652}{10721}transported, with no worse nor|better guard but with a knave
{10724}{10822}of common hire, a gondolier,|to the gross clasps of a
{10826}{10856}lascivious moor.
{10859}{10877}This thou shalt answer!
{10884}{10997}Straight satisfy yourself, if she|be in your chamber or your house,
{11017}{11072}lago, can i depend on the issue?
{11077}{11126}Thou are sure of me.|Go, make money.
{11135}{11195}It is too true an evil.|Gone she is.
{11202}{11289}Is there not charms by which|the property of youth
{11293}{11336}and maidhood may be abused?
{11341}{11371}Call up all my people!
{11376}{11410}Raise my kindred!
{11590}{11620}Where is the moor?
{11625}{11680}Keep up your bright swords|for the dew'll rust them.
{11685}{11727}Oh, thou foul thief!
{11732}{11766}Where hast thou stowed|my daughter?
{11769}{11792}Hold your hands! Good signor,
{11794}{11854}where will you that i go to|answer this your charge?
{11858}{11902}To prison till fit time of law
{11905}{11965}and course of direct session|call thee to answer.
{12012}{12127}Now at the same hour, there|came messengers in haste
{12140}{12195}to the senate for there was|news that the turkish armies
{12201}{12274}were moving against the|venetian garrison in cyprus.
{12288}{12340}The senators, already raised
{12343}{12398}the net, elected the moor to the|commander of their troops.
{12402}{12443}And officers were searching
{12446}{12487}the town to apprise othello|of this honor
{12490}{12568}when lo, desdemona's old|father himself brings the moor
{12570}{12623}at sword's point to the council|chamber upon a charge of
{12626}{12714}working from desdemona with|unlawful enchant.
{12719}{12742}She was abused,
{12745}{12816}stolen from me and, ay,|corrupted by magic spells.
{12819}{12848}I'm very sorry for't.
{12863}{12959}If she in chains of magic were not|bound, whether a maid so tender,
{12964}{13051}fair and happy would ever have|to incur her general mock,
{13051}{13086}run from her father
{13095}{13172}to the sooty bosom of such a|fierce bat!
{13298}{13366}Damned as thou art,|thou hast enchanted her!
{13374}{13452}Othello, what in your own part|can you say to this?
{13457}{13485}Nothing but this is so!
{13488}{13561}Did you by indirect and forced
{13564}{13613}courses subdue and poison|this young maid of affection?
{13679}{13758}Most potent grave and|reverend signors,
{13820}{13882}my very noble and approved|good masters,
{13910}{13982}that i've taken away this old|man's daughter it's most true.
{14030}{14060}True i have married her.
{14106}{14209}The very head and front of my|offending has this extent,
{14213}{14230}no more.
{14287}{14320}Rude in my speech,
{14342}{14392}and little blessed with the soft|phrase of peace,
{14411}{14464}since these arms of mine had|seven years' pith till now some
{14466}{14519}nine moon wasted they|have used their dearest action
{14521}{14626}in the tented field and little|little of this great world can i
{14626}{14682}speak more than pertains|to feats of broil and battle.
{14691}{14757}And therefore little shall i grace|my cause in speaking of myself.
{14794}{14859}Yet by your gracious patience
{14862}{14968}i will round unvarnished tale|deliver of my whole course of love,
{14982}{15019}what drugs, what charms,
{15024}{15076}what conjuration and what
{15076}{15122}mighty magic, for such|proceedings am i charged withal
{15131}{15169}that i won his daughter.
{15174}{15229}Her father loved me, oft
{15234}{15278}invited me, still questioned me|the story of my life.
{15283}{15333}I ran it through even from my
{15334}{15383}boyish days wherein i speak of|the most disastrous chances
{15388}{15458}of moving accidents by flood|and fields of hair-breadth
{15460}{15514}scapes for the imminent|deadly breach.
{15527}{15634}Of being taken by insolent foe,|and sold to slavery,
{15657}{15755}of my redemption thence and|potency my travels history
{15773}{15861}wherein a venturous vast and|desert idle, rough quarries,
{15873}{15971}rocks and tills whose heads|touch heaven.
{15997}{16023}It was my head to speak.
{16034}{16118}Rest to hear, but desdemona|seriously inclined.
{16186}{16246}But still the house affairs would|draw her thence, which ever as
{16249}{16302}she could with haste dispatch,
{16307}{16394}come again and with a greedy|ear devour up my discourse.
{16450}{16510}I found good means to draw
{16515}{16601}from her a prayer of earnest|heart that i would all my
{16606}{16662}pilgrimage dilate, and often|did beguile her of her tears
{16666}{16737}when i did speak of some|distressed stroke of my use of it.
{16745}{16898}She gave me for my pains,|a world of sighs.
{16915}{17005}She swore, in faith: 'twas|strange, 'twas passing strange.
{17044}{17113}Twas pitiful, 'twas wondrous|pitiful.
{17135}{17168}She wished she had not heard
{17170}{17263}it, yet she wished that|heaven made her such a man.
{17317}{17408}She thanked me, and bade me|if i had a friend that loved her
{17422}{17486}i should but teach him how to|tell my story
{17509}{17541}and that would woo her.
{17545}{17589}Upon this hint i spake,
{17591}{17653}she loved my for the dangers|i had passed,
{17703}{17747}and i loved her that she|did pity them.
{17758}{17831}This only is the witchcraft|i have used.
{17838}{17881}I think this tale would win|my daughter, too.
{17886}{17917}Come hither, desdemona.
{18112}{18194}Do you perceive in all this|noble company
{18196}{18285}where most owe you obedience?
{18346}{18425}My noble father, i do perceive|here a divided duty.
{18435}{18495}To you i am bound for life|and education.
{18510}{18590}My life and education both do|learn me how to respect you.
{18606}{18639}You are the lord of duty.
{18671}{18821}I am hitherto your daughter.|But here's my husband.
{18831}{18883}And so much duty as my|mother showed to you
{18886}{18929}preferring you before her father
{18940}{18990}so much i challenge that i|may profess,
{18990}{19192}due to the moor, my lord.|God be with you. I have done.
{19194}{19242}When remedies are past|the griefs are ended.
{19245}{19336}Please it your grace on to|the state affairs.
{19341}{19393}The turk with a most mighty|preparation makes for cyprus.
{19398}{19477}Othello, the fortitude of the|place is vast known to you.
{19490}{19518}You must away this morning.
{19538}{19556}With all my heart.
{19559}{19612}When we consider the importance|of cyprus to the turk, we must
{19615}{19679}not think the turk is so|unskillful to leave that latest
{19682}{19715}which concerns them first,
{19718}{19806}neglecting an attempt of ease and|gain to wake and wage a danger.
{19908}{19991}Look to her, moor|if thou hast eyes to see.
{19991}{20086}She has deceived her father|and may thee.
{20095}{20141}My life upon her faith!
{20538}{20594}Mark me with what violence|she first loved the moor
{20597}{20656}but for bragging and dealing|a fantastical lie.
{20664}{20727}Will she love him still for prating?
{20733}{20798}Ah, let not thy discreet heart|think it.
{20846}{20923}- Lieutenant cassio.|- Largo
{20967}{21002}what a cannon.
{21007}{21027}I know my price.
{21030}{21043}I'm worth no worse a place.
{21046}{21080}But he, sir, had the election.
{21082}{21152}And what's he? This michael|cassio, this florentine,
{21154}{21235}that never set a squadron in the|field nor the division of a battle
{21238}{21333}knows more than a spinster.|Yet cassio must his lieutenant
{21336}{21413}be, by god bless the mark of|the fellow's ancient!
{21445}{21476}Well, i would not follow him that.
{21481}{21504}Oh, sir, content you.
{21510}{21548}I follow him to serve my turn|upon him.
{21550}{21591}Lago? Lago!
{21594}{21617}Honest lago!
{21627}{21660}I wake up on your lordship.
{21663}{21714}My desdemona must i leave|with thee.
{21718}{21782}I pray bring her after good time|to cyprus.
{21786}{21815}Well, me good lord, i'll do it.
{21882}{21948}The moor's of a free and|open nature, that thinks men
{21951}{22028}honest that seem to be so,|and will as tenderly be led by
{22031}{22068}th' nose as asses are.
{22254}{22296}We cannot all be masters.
{22298}{22350}Nor all masters cannot by|truly followed.
{22366}{22434}You shall mark many a duteous|and knee-crooking knave who
{22438}{22507}doting on his own obsequious|bondage wears out his time,
{22510}{22573}much like his master's ass, for|naught but provender; and when,
{22576}{22609}he's old, cashiered.
{22622}{22670}Whip me such honest knaves!
{22682}{22704}Others there are who, trimmed
{22709}{22732}in forms and visages of duty,|keep yet their hearts attending
{22734}{22758}on themselves,|and throwing but shows of
{22759}{22807}services on their lords,|do well thrive by them, and when
{22812}{22863}they have lined their coats|do themselves homage.
{22869}{22915}These fellows have some soul,
{22926}{23017}and such a one do i profess|myself for, sir, it is as sure
{23022}{23161}as you're roderigo, were|i the moor, i would not be lago.
{23183}{23233}In following him i follow|but myself.
{23264}{23337}When my outward action doth|demonstrate the native act and
{23340}{23411}figure of my heart in compliment
{23423}{23502}extern, 'tis not long after but|i will wear my heart upon my
{23506}{23692}sleeve, for daws to peck at.|I am not what i am.
{24142}{24205}I have but an hour of love|to spend with thee.
{24274}{24310}We must obey the time.
{25382}{25445}Oh, lago, what tidings can|you tell of my lord?
{25446}{25474}He's not yet arrived, but the
{25482}{25560}turkish fleets be not enshelterd|they are drowned.
{25654}{25713}It is there! I know|othello's trumpet!
{25906}{26001}News, lads! News! The desperate|tempest hath so banged the turks
{26010}{26036}that their designment halts.
{26042}{26077}Our wars are done!
{26276}{26469}He takes her by the palm.|Well said. An excellent courtship.
{26582}{26703}With as little a web as this will i|ensnare as great a fly as cassio.
{27337}{27464}It gives me wonder great as my|content to see you here before me.
{27469}{27513}Oh, my soul's joy!
{27550}{27621}If after every tempest come such
{27626}{27689}calms, may the winds blow|till they have wakened death.
{27694}{27754}- My dear othello!|- Oh, my fair warrior!
{27774}{27854}I prattle out of fashion, and|i dote in my own comforts.
{27863}{27912}- Worthy montano, your pardon|- sir
{27917}{27964}good michael, look you|to the guard tonight.
{27994}{28020}Come, my dear love.
{28116}{28197}Once more well met at cyprus.
{28579}{28708}It is othello's pleasure that|upon certain tidings now arrived
{28717}{28805}importing the destruction of|the turkish fleet, every man
{28810}{28850}put himself into triumph.
{28855}{28951}Each man what sport and revels|his addiction lead him.
{28954}{29009}For, besides these beneficial news,
{29012}{29098}it is the celebration of|our general's nuptial.
{29101}{29259}Heaven bless the isle of cyprus|and our noble general othello!
{29344}{29391}First, i must tell thee this.
{29419}{29490}Desdemona is directly|in love with him.
{29516}{29615}With cassio?|Why, 'tis not possible.
{29618}{29668}Her eyes must be fed.
{29679}{29741}And what delight shall she|have to look on the devil?
{29798}{29851}Very nature will compel her|to the second choice.
{29864}{29877}Now sir, this granted,
{29889}{30006}who stands so eminent in the degree|of this fortune as cassio does?
{30031}{30056}Why, none! Why, none!
{30071}{30173}A slipper and subtle knave,|a devilish knave!
{30194}{30248}- He is handsome.|- Cassio?
{30270}{30312}He has all the requisites in him
{30315}{30404}that folly and green minds|look after.
{30445}{30537}Oh, a pestilent complete knave
{30540}{30608}and the woman hath found|him already.
{30662}{30747}I cannot believe that in|desdemona.
{30893}{30964}Did you not see her paddle|with the palm of his hand?
{30978}{31004}Did not mark that?
{31020}{31090}Yes, that i did, but that was|but a courtesy.
{31093}{31137}Courtesy? Lechery. An index
{31149}{31258}and obscure prologue to the|history of lust and foul thoughts.
{31284}{31374}They met so near with their lips|that their breaths embraced together.
{31395}{31438}Villainous thoughts, roderigo.
{31462}{31504}But, sir, be you ruled by me.
{31561}{31599}Listen, listen to cassio tonight.|Watch him on the court of god.
{31602}{31670}Cassio knows you not.|I'll not be far from you.
{31674}{31718}Do you find some occasion|to anger him from what
{31726}{31747}other course you please.
{31758}{31771}Well
{31774}{31813}sir, he's rash and very sudden
{31817}{31861}in choler, and haply may|strike at you.
{31865}{31888}Provoke him that he may,
{31894}{31989}for even out of that will i|cause these of cyprus to mutiny
{31994}{32080}and the displanting of cassio.|Lieutenant cassio!
{32102}{32191}Lago, i'll say, you like me|well, lago?
{32196}{32258}In the sincerity of|love and friendship.
{32267}{32315}Come, lieutenant, a stoup of|wine!
{32323}{32352}Here a brace of gallants that
{32359}{32429}fain have a measure to the|health of black othello.
{32431}{32463}Not tonight, good lago.
{32466}{32525}I have very poor and unhappy|brains for drinking.
{32530}{32561}Oh, just one cup.
{32758}{32777}I must to the watch.
{32779}{32836}Not this hour, lieutenant,|'tis not yet ten o' th' clock.
{32850}{32923}Our general cast us thus early|for the love of his desdemona.
{32945}{32990}He hath not yet made wanton|the night with her
{32993}{33034}and she is sport for jove.
{33043}{33081}She's a most exquisite lady.
{33093}{33136}And full of game, i'll warrant.
{33142}{33218}What an eye she has|to provocation.
{33222}{33268}I object, i think right modest.
{33282}{33502}Well, happiness to their sheets.|Another cup, i'll drink for you.
{33505}{33557}I have drunk two cups and|i don't dare not to task
{33560}{33592}my weakness with any more.
{33597}{33633}My man, 'tis a night of revels.
{33651}{33693}I'll do't, but it dislikes me.
{34083}{34154}If it were now to die, 'twere|now to be most happy,
{34159}{34211}for i fear my soul hath her content
{34221}{34311}so absolute that not another|comfort like to this
{34316}{34845}succeeds in unknown fate.|Ah, brothers on call tonight!
{34875}{34913}God, an excellent song!
{34930}{34957}I learned it in england, where
{34962}{35019}indeed they are most potent|in potting.
{35046}{35084}Your dane, your german,
{35087}{35149}and your swag-bellied hollander|- drink, ho! -
{35153}{35183}are nothing to your english.
{35198}{35261}Is your englishman so exquisite|in his drinking?
{35263}{35313}He drinks you with facility|you dane dead drunk,
{35339}{35391}he sweats not to overthrow|your almain,
{35396}{35472}he gives your hollander a vomit|ere the next pottle can be filled.
{35474}{35511}To the health of our general!
{35516}{35571}I am for it, lieutenant, and|i'll do you justice.
{36719}{36809}Good faith, a little one,|not past a pint, as i'm a soldier.
{37604}{37728}Well, god above all|and there be souls must be saved,
{37745}{37802}and there be souls must not|be saved.
{37805}{37836}It's true, good lieutenant.
{37838}{37940}For mine own part, no offense
{37995}{38084}to the general, nor any man|of quality, i hope to be saved.
{38170}{38238}Ay, but, by your leave,|not before me.
{38294}{38342}Do not think, gentlemen,|i am drunk.
{38386}{38521}This is my ancient, my right|hand, this is my left.
{38538}{38620}I am not drunk now. I can|stand well enough, and
{38640}{38660}i speak well enough.
{38662}{38705}Excellent well!
{38708}{38795}Very well. You must not think|then that i am drunk.
{38998}{39072}Zounds, you rogue, you rascal!
{39167}{39185}What noise is this?
{39190}{39276}A knave teach me my duty?
{39320}{39341}What's the matter, lieutenant?
{39345}{39401}I'll beat the knave into|a twiggen bottle.
{39761}{39783}Away, i say.
{39786}{39830}Go out and cry a mutiny!
{39841}{40083}Mutiny! Mutiny! Mutiny!|Mutiny! Mutiny! Mutiny!
{40346}{40368}Stop, lieutenant!
{40373}{40417}Hold this shame forever!
{40420}{40470}Have you forgot all place of|sense and duty?
{40474}{40499}Hold the rage!
{41150}{41178}Hold, gentlemen!
{41298}{41375}You're ordered above.|Yeah, move, come on!
{41382}{41428}Why, sir, the generals!
{42126}{42162}Silence that dreadful bell!
{42222}{42267}Who began this? Lago.
{42284}{42313}I do not know.
{42321}{42453}Friends all, but now, even now,|in quarter and terms like
{42467}{42526}bride and groom devesting|them for bed,
{42542}{42626}but now swords out and tilting|one at other's breasts.
{42637}{42697}Worthy montano, what's the matter
{42704}{42765}that you unlace your|reputation thus and spend your
{42765}{42826}rich opinion for the name|of a night-brawler?
{42833}{42948}Your officer, lago, can|inform you.
{42957}{42985}Fortunate. Town of war to manage|private and domestic quarrel?
{42994}{43040}In night, and on the court|and guard of safety?
{43107}{43161}Lago, who began't?
{43167}{43225}Thou dost deliver more or less|than truth, thou art no soldier.
{43229}{43275}I had rather have this tongue|cut from my mouth than it should
{43278}{43334}do offense to michael cassio.
{43377}{43425}Sir, men in rage strike those|that wish them best,
{43428}{43497}yet surely cassio i believe|received from him that fled
{43515}{43579}some strange dignity, which|patience could not pass.
{43623}{43699}I know, lago, the honesty|and love doth mince this matter,
{43701}{43732}making it light to cassio.
{43770}{43937}Cassio, i love thee,|but never more be officer of mine.
{43949}{44000}Look if my gentle love be not|raised up.
{44021}{44053}I'll make thee an example.
{45062}{45189}What, are you hurt, lieutenant?|Ay, past all surgery.
{45202}{45241}Marry, heaven forbid!
{45246}{45324}Reputation, reputation,|reputation!
{45331}{45386}O, i have lost my reputation!
{45397}{45449}I have lost the immortal part|of myself,
{45453}{45478}and what remains is bestial.
{45481}{45535}My reputation, lago,|my reputation.
{45538}{45603}Reputation oft got without|merit and lost without deserving.
{45646}{45693}I tell you what you shall do.
{45695}{45752}Our general's wife is|now the general.
{45754}{45790}Confess yourself freely to her.
{45797}{45897}Desdemona is of so free, so|kind, so blessed a disposition
{45900}{45965}she holds it a vice in her|goodness not to do more than
{45968}{45992}she is requested.
{46053}{46084}Farewell, lieutenant.
{46314}{46339}Roderigo.
{46397}{46433}My money is almost spent,
{46437}{46508}i have been tonight exceedingly|well cudgeled.
{46518}{46554}And i think the issue will be,
{46565}{46636}i shall have so much experience|for my pains, and so, with
{46638}{46750}no money at all, and a little|more wit, return again to venice.
{46779}{46826}How poor are they that|have not patience!
{46842}{46868}Does not go well?
{46894}{46957}Cassio has beaten thee, and|thou by that small hurt hath
{46960}{47001}cashiered cassio.
{47004}{47036}Content thyself awhile.
{47048}{47122}For whiles this honest fool|plies desdemona to repair
{47125}{47188}his fortune, and she for him|pleads strongly to the moor.
{47199}{47244}Io, by how much she strives
{47246}{47291}to do him good, she shall|undo her credit with the moor.
{47306}{47391}So will i turn her virtue into pitch,|and out of her own
{47394}{47475}goodness make the net|that shall enmesh them all.
{48523}{48548}Do not doubt, cassio.
{48553}{48613}I'll have my lord and you again|as friendly as you were.
{48617}{48694}Madam, whatever shall become|of michael cassio, he's never
{48698}{48753}anything but your true servant.
{48766}{48812}Ha! I like not that.
{48815}{48833}What dost thou say?
{48838}{48903}Nothing, my lord, or if,|i know not what.
{48922}{48947}How now, my lord?
{48962}{49003}I have been talking with|a suitor here.
{49008}{49052}A man that languishes in|your displeasure.
{49055}{49073}Who is't you mean?
{49075}{49101}Why, your lieutenant cassio.
{49110}{49131}Went he hence now?
{49131}{49202}I' sooth so humbled that he hath|left part of his grief with me
{49206}{49226}to suffer with him.
{49232}{49258}Good love, call him back.
{49261}{49282}Some other time.
{49287}{49337}- Shall't be shortly?|- The sooner, sweet, for you.
{49341}{49400}- Shall't be tonight at supper?|- No, not tonight.
{49403}{49414}Tomorrow dinner then?
{49420}{49448}I shall not dine at home.
{49448}{49485}I meet the captains|at the citadel.
{49490}{49545}Why then, tomorrow night.|I prithee name the time.
{49548}{49590}No more. Let him come|when he will.
{49602}{49642}I will deny thee nothing.
{49763}{49795}Whereon i do beseech thee
{49806}{49857}grant me this to leave me|but a little to myself.
{49862}{49989}Shall i deny you? No.|Farewell, my lord.
{50118}{50184}- My noble lord.|- What dost thou say, lago?
{50230}{50288}Did michael cassio, when you|wooed my lady,
{50290}{50315}know of your love?
{50336}{50414}He did, from first to last.|Why dost thou ask?
{50426}{50497}But for a satisfaction of my|thought, no further harm.
{50510}{50545}Why of thy thought, lago?
{50566}{50618}I did not think he had been|acquainted with her.
{50626}{50686}O, yes, and went between us|very oft.
{50691}{50752}- Indeed?|- Indeed? Ay, indeed.
{50780}{50852}Discern'st thou aught in that?|Is he not honest?
{50906}{50980}- Honest, my lord?|- Honest? Ay, honest!
{50995}{51031}My lord, for aught i know.
{51049}{51073}What dost thou think?
{51102}{51122}Think, my lord?
{51137}{51208}Think. Thou dost mean something.
{51221}{51272}I heard thee say even now,|thou lik'st not that,
{51274}{51310}when cassio left my wife.
{51380}{51464}If thou dost love me|show me thou thought.
{51467}{51497}My lord, you know i love you.
{51509}{51537}I think thou dost.
{51622}{51657}For michael cassio, i dare
{51698}{51817}be sworn, i think he is honest.|I think so, too.
{51913}{51958}Men should be what they seem.
{51962}{52012}Certain, men should be|what they seem.
{52051}{52111}Why then, i think cassio's|an honest man.
{52132}{52216}Nay, yet there's more in this?
{52264}{52352}I prithee speak to me as|to thy thinkings.
{52407}{52441}Good name in man and woman,
{52457}{52549}dear my lord, is the immediate|jewel of their souls.
{52558}{52625}Who steals my purse steals|trash; 'this something, nothing.
{52628}{52706}Twas mine, 'tis his, and has|been slave to thousands.
{52753}{52825}But he that flinches from me|my good name robs me of
{52837}{52939}that which not enriches him|and makes me poor indeed.
{52941}{52973}By heaven, i'll know|thy thoughts.
{52976}{53064}Beware, my lord, of jealousy!|It is the green-eyed monster,
{53066}{53109}which doth mock the meat|it feeds on.
{53112}{53165}That cuckold lives in bliss|who, certain of his fate,
{53170}{53189}loves not his wronger.
{53194}{53287}But o, what damned minutes|tells he over who dotes,
{53296}{53398}yet doubts, suspects,|yet fondly loves!
{53421}{53465}Why? Why is this?
{53508}{53576}Think'st thou i'd make a life of
{53588}{53647}jealousy to follow still the|changes of the moon with
{53652}{53795}fresh suspicions?|No, lago, i'll see before i doubt.
{53800}{53878}When i doubt, prove.|I speak not yet of proof.
{53893}{54009}Look to your wife.|Observe her well with cassio.
{54290}{54351}I know our country disposition|well.
{54406}{54468}In venice they do let heaven
{54470}{54514}see the pranks they dare not|show their husbands.
{54518}{54604}Their best conscience is not to|leave't undone but kept unknown.
{54609}{54634}Dost thou say so?
{54639}{54691}She did deceive her father,|marrying you.
{54694}{54726}And when she seemed to shake|and fear your looks,
{54730}{54752}she loved them most.
{54773}{54795}And so she did.
{54798}{54909}Why, go to then! She that so|young could give out such a
{54914}{54989}seeming to seel her father's|eyes up close as oak.
{54995}{55082}He thought 'twas witchcraft.|But i am much to blame.
{55086}{55153}I humbly do beseech you of my|pardon for too much loving you.
{55232}{55271}I'm bound to thee forever.
{55573}{55622}I see this hath a little|dashed your spirit.
{55626}{55676}Not a jot, not a jot.
{55678}{55705}Trust me, i fear it has.
{55731}{55824}I hope you will consider what|is spoke comes from my love.
{55846}{55885}Cassio's my worthy friend.
{55903}{55941}My lord, i see you're moved!
{55954}{56027}No, not much moved.
{56064}{56172}I do not think but|desdemona's honest.
{56180}{56269}Long live she so.|And long live you to think so.
{56333}{56389}And yet, how nature erring|from itself
{56390}{56442}ay, there's the point, as to
{56445}{56543}be bold with you, not to|affect many proposed matches
{56552}{56624}of her own clime, complexion,|and degree.
{56654}{56777}One may smell in such a will|most rank, foul disproportions,
{56794}{56821}thought unnatural.
{56968}{57057}My lord, i would i might entreat|your honor to scan this thing
{57060}{57093}no further. Leave it to time.
{57104}{57128}Farewell.
{57174}{57210}Leave me, lago.
{57336}{57378}How now, my dear othello?
{57409}{57450}My lord, i take my leave.
{57538}{57566}Are you not well?
{57601}{57650}I have a pain upon my|forehead here.
{57654}{57681}Why, that's with watching.
{57685}{57708}It will away again.
{57712}{57765}Let me but bind it hard, within|hours it will be well.
{57766}{57822}Your napkin is too little.|Let it alone!
{59359}{59390}I have a thing for you.
{59393}{59409}You have a thing for me?
{59412}{59473}It is a common thing to|have a foolish wife.
{59476}{59494}O, is that all? What will you
{59498}{59553}give me now for that|same handkerchief?
{59558}{59573}What handkerchief?
{59575}{59628}That which so often you|did bid me to steal.
{59631}{59649}Give it me.
{59654}{59709}If it be not for some purpose|of import, give't me again.
{59718}{59745}Poor lady, she'll run mad.
{59746}{59816}I have use for it. Leave me.
{60530}{60549}How now, general?
{60550}{60589}I swear 'tis better to be much
{60590}{60614}abused than but to|know't a little.
{60618}{60657}- My lord!|- Is my lord angry?
{60662}{60735}He went hence but now, and|certainly in strange unquietness.
{60740}{60791}- I will go seek him.|- I prithee do so.
{60794}{60853}There's matter in't indeed|if he be angry.
{61065}{61149}Villain, be sure thou prove|my love a whore, be sure of it!
{61196}{61230}Give me the ocular proof,
{61241}{61300}or, by the worth of mine eternal|soul, thou hadst been better
{61302}{61339}have been born a dog than|answer my waked wrath!
{61342}{61354}Is't come to this?
{61358}{61410}Make me to see't, or at the|least so prove it that
{61412}{61475}the probation bear no hinge|nor loop to hang a doubt on
{61483}{61517}or woe upon thy life!
{61532}{61593}Never pray more,|abandon all remorse.
{61598}{61665}For nothing canst thou to|damnation add greater than that.
{61667}{61690}O monstrous world!
{61692}{61729}Take note, take note, o world!
{61734}{61772}To be direct and honest|is not safe.
{61774}{61954}By the world i think my wife|be honest, and think she is not.
{61970}{62064}I think that thou art just, and|think thou art not.
{62091}{62128}I'll have some proof. Her name,
{62147}{62247}that was as fresh as dian's|visage, is now begrimed and
{62252}{62345}black as mine own face.
{62361}{62396}Would i were satisfied!
{62402}{62436}How satisfied, my lord?
{62438}{62530}Would you, the supervisor,|grossly gape on?
{62556}{62607}Behold her topped?
{62665}{62717}It is impossible you should|see this.
{62720}{62797}Were they as prime as goats,|as hot as monkey?
{62800}{62861}Give me a living reason|she's disloyal!
{62903}{62973}I lay with cassio lately, and|being trouble with a raging
{62980}{62998}tooth, i could not sleep.
{63001}{63072}There are a kind of men so loose|or should that in their sleeps
{63075}{63109}will mutter their affairs.
{63112}{63161}One of this kind is cassio.
{63179}{63244}In sleep i heard him say,
{63256}{63379}sweet desdemona, let us|be wary, let us hid our loves.
{63389}{63446}And then, sir, would he gripe|and wring my hand, cry
{63448}{63497}o sweet creature! Then kiss
{63499}{63563}me hard as if he plucked up|kisses by the roots that grew
{63565}{63663}upon my lips, laid his leg o'er|my thigh, and sigh, and kiss
{63670}{63726}and then cry, cursed fate|that gave thee to the moor!
{63729}{63785}I'll tear her all to pieces!
{63787}{63862}Tell me but this. Have you not|sometimes seen a handkerchief
{63866}{63915}spotted with strawberries in|your wife's hand?
{63920}{63944}I gave her such a one.
{63946}{64020}Such a handkerchief, i'm sure|it was your wife's, did i today
{64022}{64066}see cassio wipe his face.
{64128}{64150}If it be that
{64152}{64203}if it be that, or any that was
{64224}{64278}hers, it speaks against her|with the other proofs.
{64347}{64404}Now do i see 'tis true.
{64500}{64565}O, that the slave had|forty thousand lives!
{64568}{64580}One is too poor, too week|for my revenge!
{64630}{64711}- Yet be content!|- Blood, blood, blood!
{64718}{64810}Patience, i say.|Your mind may change.
{64812}{64871}Never, lago. Like to the pontiac
{64871}{64939}sea, whose icy current and|compulsive course nev'r keeps
{64982}{65022}retiring ebb, but keeps due on|to the propontic and the
{65024}{65037}hellespont.
{65043}{65082}Even so my bloody thoughts,
{65086}{65168}with violent pace, shall nev'r|look back, nev'r ebb to humble
{65171}{65255}love, till that a capable and|wide revenge swallow them up.
{65257}{65333}Witness that here lago doth|give up the execution of
{65340}{65395}his wit, hands, heart to|wronged othello's service.
{65398}{65425}Within these three days let me
{65426}{65486}here thee say that|cassio's not alive.
{65489}{65563}My friend is dead. 'tis done|at your request.
{65594}{65621}But let her live.
{65625}{65657}Damn her, lewd minx!
{65683}{65720}O, damn her!
{65840}{65937}Now art thou my lieutenant.
{65951}{66009}I am your own forever.
{66527}{66571}Cassio! Cassio!
{67508}{67535}Give me your hand.
{67618}{67662}This hand is moist, my lady.
{67668}{67716}It hath felt no age nor|known no sorrow.
{67718}{67866}This argues fruitfulness and|liberal heart. Hot, hot and most.
{67890}{67947}'Tis a good hand, a frank one.
{67950}{67998}You may, indeed, say so|for 'twas that hand that
{68001}{68026}gave away my heart.
{68029}{68059}A liberal hand.
{68064}{68099}Come now, your promise.
{68102}{68169}- What promise, chuck?|- Let cassio be received again.
{68302}{68333}Lend me thy handkerchief.
{68343}{68371}I have it not about me.
{68381}{68420}- Not?|- No, indeed, my lord.
{68423}{68448}That's a fault. That handkerchief
{68452}{68500}did an egyptian to my mother|give.
{68502}{68550}The worms were hallowed that|did breed the silk.
{68555}{68590}Then would to god that|i had never seen't.
{68599}{68674}Is't lost? Is't gone?|Speak, is it out of the way?
{68683}{68725}It is not lost.|But what an if it were?
{68730}{68749}How?
{68760}{68808}I say it is not lost.
{68817}{68852}Fetch't, let me see it!
{68857}{68906}Why, so i can, but i will|not now.
{68912}{68962}This is a trick to put me|from my suit.
{68969}{69009}Pray you let cassio|be received again.
{69013}{69070}- The handkerchief!|- I pray talking of cassio
{69077}{69088}the handkerchief!
{69094}{69160}A man that all his time hath founded|his good fortunes on your love,
{69166}{69211}- shares dangers with you|- the handkerchief!
{69217}{69271}Come, come, you'll never|meet a more sufficient man.
{69277}{69466}Away. Away!|Away!
{69510}{69561}Cassio, this handkerchief.|Whose is it?
{69567}{69622}I found it here.|I like the work well.
{69629}{69681}'Tis very good!|Shall i see you soon at night?
{69684}{69730}I will see you soon, bianca.
{69730}{69793}- Come, lieutenant.|- Cassio, handkerchief.
{69801}{69861}Take it. Have it copied|thee made for it.
{69978}{70012}Tell you yet once more,
{70018}{70105}importune desdemona to|put you in your place again.
{70195}{70249}Sure there's some wonder|in this handkerchief.
{70266}{70321}'Tis a year or two shows|us a man.
{70327}{70400}They're all but stomachs,|and we all but food. Cassio!
{70414}{70545}They eat us hungerly, and|when they're full, they belch us.
{70674}{70728}How now, good cassio?|What's the news with you?
{70908}{71003}What trumpet is that same?|Something from venice.
{71445}{71496}My noble lord, whilest you|were here, overwhelmed with
{71502}{71572}your grief, cassio came hither.|I shifted him aways, bade him
{71578}{71643}anon return, and|here speak with me.
{71656}{71695}Mark the fleers, the gibes,
{71700}{71769}and notable scorns that dwell|in every region of his face.
{71816}{71863}For i will make him tell|the tale anew,
{71866}{71937}where, how, how oft, how|long ago, and when he hath
{71942}{71995}and is again to cope your wife.
{72124}{72171}I say, but mark his gesture.
{72178}{72245}Marry patience, or i shall say|you're all in all in spleen,
{72250}{72302}and nothing of a man.|Dost thou hear, lago?
{72311}{72376}I will be found most cunning|in my patience.
{72408}{72498}But - dost thou hear? - |most bloody.
{72529}{72591}- How do you know, lieutenant?|- Lago.
{72615}{72673}Now, if this suit lay in bianca's|power,
{72678}{72721}how quickly should you speed!
{72728}{72764}Alas, poor caitiff!
{72803}{72871}I never knew woman love|man so.
{72877}{72962}She gives it out that|you shall marry her.
{72966}{73028}Ay!
{73196}{73270}I was talking on the sea bank,|and the bauble falls me thus
{73275}{73321}about my neck
{73336}{73397}so hangs, and lolls, and|weeps upon me,
{73405}{73448}so shakes and pulls me!
{73450}{73519}- Cassio!|- I must leave her company.
{73528}{73617}What did you mean by that same|handkerchief you gave me even now?
{73630}{73692}A likely piece of work that|you should find it in your
{73697}{73723}chamber and know not who|left i t there!
{73733}{73756}This is some minx's token.
{73763}{73799}I'll take out no work on't.
{73806}{73847}Now now, my sweet bianca?|How now?
{73851}{73883}After her! After her!
{74022}{74085}Did you see how he laughed|at his vice?
{74104}{74127}O lago.
{74137}{74167}Did you see the handkerchief?
{74187}{74225}Was that mine?
{74245}{74329}Desdemona gave it him, and|he hath giv'n it his whore.
{74578}{74683}I had been happy if the general|camp, pioners and all, had
{74690}{74735}tasted her sweet body.
{74746}{74818}So i had nothing known.
{74844}{74928}What sense had i of her|stolen hours of lust?
{74941}{75019}I saw it not, it harmed me not.
{75032}{75113}I slept the next night well,|was free and merry!
{75144}{75244}I found not cassio's kisses|on her lips.
{75375}{75503}A fine woman, a fair woman,|a sweet woman.
{75673}{75702}Nay, you must forget that.
{75706}{75787}Ay, let her rot and perish,|and be damned.
{75798}{75949}No, my heart is turned to stone.|I strike it and it hurts my hand.
{75994}{76056}O, the world hath not a|sweeter creature!
{76106}{76219}She might lie by an emperor's|side and command him tasks.
{76227}{76273}Nay, that's not your way.
{76303}{76401}Hang her! I do but say|what she is.
{76469}{76508}So delicate with her needle.
{76528}{76576}An admirable musician.
{76618}{76703}O, she will sing the savageness|out of a bear.
{76722}{76793}Of so high and plenteous|wit and invention
{76800}{76845}she's the worse for all this.
{76853}{76906}O, a thousand, a thousand|times.
{76938}{76985}Of so gentle a condition?
{76990}{77017}Ay, too gentle.
{77026}{77143}Nay, that's certain.|Yet the pity of it, lago.
{77181}{77286}O lago, the pity of it, lago.
{77320}{77361}I will chop her into messes!
{77372}{77413}Cuckold me!
{77752}{77784}- Will you think so?|- Think so, lago?
{77787}{77836}- What, to kiss in private?|- An unauthorized kiss?
{77842}{77902}Or to be naked with her|friend in bed an hour or more
{77908}{77944}not meaning any harm.
{77958}{77985}Naked in bed?
{77991}{78010}But if i give my wife|a handkerchief
{78016}{78033}what then?
{78037}{78091}Why, then 'tis hers, my lord,|and being hers shy may,
{78095}{78117}i think, bestow't on any man.
{78132}{78162}By heaven, i would most|gladly have forgot it!
{78168}{78206}He had my handkerchief!
{78211}{78245}- Ay, what of that?|- That's not so good now.
{78251}{78303}What if i had said i had seen|him do you wrong?
{78310}{78350}- Or heard him say|- hath he said anything?
{78359}{78398}He hath, my lord, but|no more than
{78404}{78414}what hath he said?
{78419}{78508}That he did i know not what he did|what? What?
{78531}{78571}Lie.
{78653}{78685}Lie with her?
{78693}{78801}With her, on her, what you will.
{79861}{79895}Damnation!
{79906}{79969}My lord, i say, othello!
{80308}{80337}Dost thou mock me?
{80340}{80436}I mock you not, by heaven.
{81331}{81519}O now for ever farewell|the tranquil mind.
{81576}{81624}Farewell content.
{81689}{81760}Farewell the plumed troops,|and the big wars that make
{81770}{81875}ambition virtue. O farewell!
{81897}{81970}Farewell the neighing steed and|the shrill trump,
{81991}{82107}the spirit-stirring drum,|th'ear-piercing fife, the royal
{82110}{82262}banner, and all quality,|pride, pomp, and circumstance,
{82268}{82327}of glorious war.
{82366}{82473}And o you mortal engines|whose rude throats the immortal
{82477}{82553}jove's dread clamors|counterfeit.
{82622}{82705}Farewell! Othello's occupation's|gone!
{83675}{83740}- God save you, worthy general.|- Pray you.
{83882}{83955}The duke and the senators|of venice greet you.
{83977}{84046}I kiss the instrument of|their pleasures.
{84383}{84446}Is there division 'twixt my lord|and cassio?
{84450}{84525}A most unhappy one, i would|do much t' atome them,
{84529}{84575}for the love i bear to cassio.
{84588}{84617}My lord?
{84623}{84676}May be th' letter moved him,|for, i think, they do command
{84680}{84721}him home, deputing cassio|in his government.
{84726}{84785}- Trust me, i am glad on it.|- Indeed?
{84862}{84995}- Why, sweet othello|- devil! Out of my way!
{85009}{85034}I will not stay to offend you.
{85038}{85076}Truly an obedient lady.
{85091}{85137}I do beseech your lordship|call her back.
{85141}{85171}- Mistress!|- My lord!
{85176}{85199}What would you do with her, sir?
{85208}{85231}Who? I, my lord?
{85243}{85266}You did wish that i would make|her turn.
{85269}{85385}Sir, she can turn, and turn,|and yet go on and turn again,
{85393}{85421}and she can weep, sir, weep.
{85430}{85490}And she's obedient, as you say,|obedient. Very obedient.
{85497}{85547}Proceed you in your tears.
{85570}{85600}Concerning this, sir
{85618}{85734}o well-painted passion!|I am commanded home.
{85753}{85868}Get you away, i'll send|for you anon.
{85965}{86083}Sir, i obey the mandate and|will return to venice.
{86091}{86149}Cassio shall have my place.
{86315}{86371}You are welcome, sir,|to cyprus.
{86541}{86657}Goats and monkeys!
{86797}{86825}Is he not light of brain?
{86884}{86917}He's that he is.
{87684}{87720}Let me see your eyes.
{87788}{87816}Look in my face.
{88001}{88068}Why, what art thou?
{88081}{88139}Your wife, my lord.|Your true and loyal wife.
{88152}{88249}Had it pleased heaven to try me|with affliction, had they rained
{88254}{88357}all kinds of sores and shames|on my bare head, steeped me
{88362}{88450}in poverty to the very lips,|given to captivity me and
{88457}{88508}my utmost hopes.
{88519}{88657}I should have found in some|place of my soul a drop of patinece
{88682}{88804}but, alas, to make me the fixed|figure for the time of scorn
{88805}{88873}to point his slow and moving|finger at.
{88888}{88977}Yet could i bear that too, well,|very well.
{89003}{89157}But there where i have garnered|up my heart, where either
{89161}{89292}i must live or bear no life,|the fountain from the which my
{89297}{89535}current runs or else dries up,|to be discarded thence, or
{89549}{89655}keep it as a cistern for foul|toads to knot and gender in.
{89660}{89715}I hope my noble lord|esteems me honest.
{89735}{89824}O, ay, as summer flies are|in the shambles, that quicken
{89836}{89867}even with blowing.
{89874}{90087}O, thou weed, who art so|lovely fair, and smell'st so
{90096}{90210}sweet, that the sense aches|at thee, would thou hadst
{90326}{90360}never been born!
{90368}{90432}Alas, what ignorant sin|have i committed?
{90505}{90593}Committed? A thou public|commoner, i should make very
{90597}{90669}forges of my cheeks that would|to cinders burn up modestly.
{90673}{90739}Did i but speak thy deeds.|What committed?
{90745}{90808}Heaven stops the nose at it,|and the moon winks,
{90813}{90885}the bawdy wind that kisses all|it meets is hushed within the
{90889}{90993}hollow mine of earth and|will not hear't. What committed?
{91113}{91195}- Are not you a strumpet?|- By heaven you do me wrong!
{91198}{91287}- Are not you a strumpet?|- No, as i am a christian!
{91292}{91319}- Is't possible?|- O heaven forgive us!
{91324}{91367}I cry you mercy then.
{91373}{91483}I took you for that cunning|whore of venice that married with othello
{92258}{92290}how do you, madam?
{92331}{92376}How do you, my good lady?
{92418}{92441}Faith, half asleep.
{92445}{92503}Good madam, what's the|matter with my lord?
{92508}{92532}With who?
{92549}{92590}Why, with my lord, madam.
{92662}{92690}Who is thy lord?
{92694}{92737}He that is yours, sweet lady.
{92761}{92875}I have none. Do not talk|to me, emilia.
{92905}{92992}I cannot weep, nor answers have|i none, but what should go by water
{93015}{93269}prithee tonight lay on my|wedding sheets, remember.
{94336}{94494}Get me some poison, lago,|this night.
{94521}{94617}I'll not expostulate with her,|lest her body and beauty
{94637}{94677}unprovide my mind again.
{94685}{94725}Do it not with poison.
{94732}{94868}Strangle her in her bed, even|the bed she hath contaminated.
{94873}{94947}Good, good! The justice of|it pleases.
{94954}{95061}And for cassio, let me be|his undertaker.
{95130}{95159}Excellent good!
{95167}{95210}You shall hear more by midnight.
{95692}{95726}A halter pardon him!
{95737}{95781}And hell gnaw his ones!
{95797}{95835}Who should he call her whore?
{95857}{95889}Who keeps her company?
{95913}{95951}What time? What place?
{95961}{96047}What form? What likelihood?
{96061}{96115}The moor's abused by some|most villainous knave,
{96117}{96173}some base notorious knave,|some scurvy fellow!
{96177}{96211}Speak within doors.
{96223}{96286}Some such squire he was|that turned your wit the steamy
{96289}{96368}side without and made you to|suspect me with the moor.
{96371}{96406}Desdemona.
{96612}{96649}Get you to bed.
{96659}{96705}Dismiss your attendant there.
{96717}{96749}Look't be done.
{98297}{98356}I do not find that thou deal'st|justly with me.
{98359}{98389}What in the contrary?
{98403}{98469}Every day thou daff'st me|with some device, lago.
{98475}{98529}I have wasted myself out of|my means.
{98540}{98605}The jewels you have had from|me to deliver desdemona would
{98609}{98675}half have corrupted a votarist.
{98681}{98735}You have tole me she hath|received them, and returned
{98740}{98810}me expectations and comforts|of sudden respect and
{98813}{98862}acquaintance, but i find none.
{98866}{98925}Very well. Go to.
{98929}{98988}I cannot go to, man,|nor 'tis not very well.
{98994}{99052}I will make myself known|to desdemona.
{99065}{99111}She will return me my jewels.
{99162}{99241}If not, i will seek satisfaction|of you.
{99245}{99319}Now i see there's a mettle|in thee, and even from this
{99322}{99393}instant do build on thee a|better opinion than ever before.
{99401}{99449}Give me thy hand, roderigo.
{99566}{99635}I protest i have dealt|mostly directly in thy affair.
{99657}{99692}It hath not appeared.
{99701}{99789}I grant thee it hath not appeared,|and your suspicion is not
{99793}{99864}without wit and judgment.
{99886}{99964}If thou hast that in thee indeed|which i have greater reason
{99966}{100009}to believe now than ever,
{100018}{100156}i mean purpose, courage, and|valor, this night prove it.
{100159}{100323}If thou the next night following|enjoy not desdemona,
{100359}{100424}take me from this world|with treachery.
{100717}{100813}There is especial commission|come from venice to depute
{100817}{100873}cassio in othello's place.
{100881}{100982}Why, then othello and desdemona|return again to venice.
{100984}{101071}Unless his abode be lingered|here by some accident, wherein
{101078}{101212}none can be so determinate|as the removing of cassio.
{101222}{101289}How do you mean, removing him?
{101299}{101360}Why, by making him uncapable|of othello's place.
{101421}{101457}Knocking him out his brains.
{101481}{101570}And that you would have|me to do?
{101866}{101957}I will be near to second your attempt,|and he shall fall between us.
{102075}{102144}I have no great devotion|to the deed.
{102148}{102174}It makes us, or it mars us.
{102181}{102210}Think on that.
{104108}{104131}Lago.
{104467}{104490}Lago.
{105254}{105316}Hark! Who is it that knocks?
{105341}{105367}It is the wind.
{105561}{105607}I called my love false love.
{105665}{105703}But what said he then?
{105942}{105985}O, these men, these men
{106015}{106088}dost thou in conscience think,|tell me emilia, that there be
{106100}{106182}women do abuse their husbands|in such gross kind?
{106195}{106237}There be some such,|no question.
{106243}{106289}Wouldst thou do such a deed|for all the world?
{106296}{106325}Why, would not you?
{106331}{106355}No, by this heavenly light!
{106357}{106405}Nor i neither by this|heavenly light.
{106410}{106453}I might do it as well as|in the dark.
{106473}{106524}Wouldst thou do such a deed|for all the world?
{106560}{106604}The world's a huge place.
{106604}{106663}It is a great price for a small vice.
{106670}{106710}In troth, i think thou|wouldst not.
{106723}{106760}In troth, i think i should.
{106771}{106833}Marry, i would not do such a|thing for a joint-ring, nor for
{106837}{106903}measures of lawn, nor for|gowns, petticoats, nor caps,
{106906}{106989}nor any petty exhibition, but|for all the whole world?
{106991}{107040}I do not think there is|any such woman.
{107046}{107162}Yes, a dozen, but i do think|it is their husbands' faults
{107165}{107193}if wives do fall.
{107201}{107265}Say that they slack their duties|and pour our treasures into
{107269}{107334}foreign laps, or else break out|in peevish jealousies, throwing
{107338}{107433}restraint upon us,|or say they strike us.
{107481}{107544}We have galls, and though|we have some grace.
{107547}{107584}Yet have we some revenge.
{107595}{107667}Let husbands know their wives|have sense like them.
{107669}{107693}They see, and smell.
{107701}{107781}And have their palates both for|sweet and sour, as husbands have.
{107789}{107850}What is it that they do when|they change us for others?
{107857}{107893}Is it sport? I think it is.
{107906}{107949}And doth affection breed it?|I think it doth.
{107957}{108024}Is't frailty that thus errs?|It is so too.
{108034}{108130}And have we not affections?|Desires for sport? And frailty?
{108146}{108175}As men have?
{108189}{108262}Then let them use us well,|else let them know, the ills
{108265}{108317}we do, their ills instructs us so.
{108324}{108393}Good night. Good night.
{109674}{109802}It is the cause, it is the cause,|my soul.
{109818}{109909}Let me not name it for you,|you chaste stars.
{109942}{110081}It is the cause. Yet i'll not|shed her blood.
{110094}{110221}Nor scar that whiter skin of|hers than snow, and smooth
{110225}{110283}as monumental alabaster.
{110325}{110445}Yet she must die, else she'll|betray more men.
{111877}{112003}Put out the light, and then|put out the light.
{112018}{112121}If i quench thee, thou flaming|minister, i can again they
{112127}{112202}former light restore, should|i repent me.
{112218}{112341}But once put out thy light,|those cunning'st pattern of
{112345}{112468}excelling nature, i know not|where is that promethean heat
{112473}{112562}than can thy light relume.
{112583}{112644}- Othello.|- Ay, desdemona.
{112675}{112716}Will you come to bed, my lord?
{112921}{112953}Have you prayed tonight,|desdemona?
{112955}{112966}Ay, my lord.
{112971}{113028}If you bethink yourself of any|crime unreconciled as yet to
{113033}{113118}heaven and grace,|solicit for it straight.
{113139}{113184}Alas, my lord, what may you|mean by that?
{113198}{113229}Well, do it, and be brief.
{113272}{113340}I would not kill thy|unprepared spirit.
{113367}{113412}No, heaven forfend!
{113462}{113504}I would not kill thy soul.
{113515}{113546}Talk you of killing?
{113554}{113616}Ay, i do.
{113642}{113669}Then heaven have mercy on me.
{113675}{113734}Amen, with all my heart.
{113752}{113861}If you say so, i hope|you will not kill me.
{113945}{114000}Peace! And be still.
{114052}{114127}I will so, and yet i fear you.
{114141}{114216}Why i should fear i know not,|since guiltiness i know not.
{114222}{114271}But yet i feel i fear.
{114329}{114364}That handkerchief!
{114381}{114453}That handkerchief which i so|loved and gave thee,
{114465}{114499}thou gave it to cassio.
{114509}{114546}No, by my life and soul!
{114552}{114590}Send for the man and ask him.
{114596}{114617}Sweet soul, take heed.
{114624}{114684}Take heed of perjury,|thou art on thy deathbed.
{114714}{114755}- Lord have mercy on me.|- I say amen.
{114769}{114833}And have your mercy too.|I never loved cassion in my life.
{114837}{114874}I saw the handkerchief.|He found it then,
{114880}{114898}i never gave it to him.
{114902}{114955}Send for him, let him|confess the truth.
{114960}{114983}He hath confessed.
{114985}{115000}What, my lord?
{115002}{115037}That he hath used thee.
{115073}{115169}How? Unlawfully?
{115203}{115237}Ay.
{115249}{115281}He will not say so.
{115288}{115336}No, his mouth is stopped.
{115360}{115421}Honest lago hath taken|order for it.
{115444}{115468}What, is he dead?
{115477}{115549}Had all his hairs been lives,|my great revenge had
{115551}{115584}stomach for them all.
{115595}{115661}Out, strumpet! Weep'st thou|for him to my face?
{115666}{115715}O, banish me, my lord,|but kill me not!
{115721}{115750}Down, strumpet!
{115755}{115804}Kill me tomorrow, let me|live tonight!
{115945}{115981}It is too late.
{116581}{116632}Now how dost thou look now?
{116639}{116782}Cold, cold, my girl,|even like thy chastity!
{116802}{116862}O cursed, cursed slave!
{116867}{116927}Whip me, ye devils, from the|possession of this heavenly sight!
{116933}{116967}Blow me about in winds!
{116974}{117015}Roast me in sulphur!
{117019}{117126}Wash me in steep-down gulfs|of liquid fire!
{117145}{117338}O desdemon! Dead desdemon!|Dead, o! O!
{117349}{117389}My lord! My lord!
{117393}{117468}What, ho, my lord! My lord!
{117474}{117529}I do beseech you that|i may speak with you, my lord.
{117611}{117633}What, ho, my lord!
{117657}{117672}I had forgot thee.
{117677}{117739}O my good lord, yonder...,|alas, what cry is that?
{117746}{117772}Yonder's murders done.
{117780}{117871}It is the very error of the moon.
{117901}{117969}She comes more nearer earth|than she was wont
{117999}{118041}and that makes men mad.
{118093}{118156}Alas! That was my lady's voice.
{118166}{118273}O! Sweet desdemona!|Who hath done this deed?
{118284}{118342}Nobody, i myself.
{118357}{118416}Commend me to my kind lord.
{119101}{119137}You heard her say herself.
{119144}{119171}It was not i.
{119173}{119229}She said so. I must needs|report the truth.
{119231}{119288}She's like a liar gone|to burning hell!
{119306}{119336}It was i that killed her.
{119347}{119418}She turned to folly, and|she was a whore!
{119423}{119439}Liar!
{119442}{119473}Cassio did top her.
{119478}{119507}Ask thy husband else!
{119509}{119541}That she was false to wedlock?
{119545}{119569}Ay, with cassio.
{119574}{119680}Had she been true, if heaven|would make me such another
{119683}{119795}world of one entire and perfect|chrysolite,
{119839}{119873}i'd not have sold her for it.
{119877}{119928}My husband say she was false?
{119932}{119970}Ay, it was he that told me|on her first.
{119976}{120048}An honest man he is, and hates|the slime that sticks
{120054}{120083}on filthy deeds.
{120085}{120149}She was too fond of her|most filthy bargain.
{120153}{120166}Peace.
{120170}{120213}- Do thy worst.|- Peace.
{120224}{120263}This deed of thine is no more|worthy heaven than
{120268}{120292}thou wast worthy her.
{120297}{120324}Peace, you were best.
{120339}{120436}O gull! O dolt! As ignorant|as dirt!
{120439}{120499}I'll make thee known though|i lost twenty lives.
{120507}{120569}Help! Help, ho, help!
{120576}{120623}Murder! Help, ho!
{120641}{120684}Disprove this villain, if thou|be'st a man.
{120686}{120723}He says thou told'st him that|his wife was false.
{120728}{120756}I know thou didst not.
{120765}{120809}Speak, for my heart is full.
{120814}{120863}I told him what i thought, and|told no more than what he
{120868}{120901}found himself was apt and true.
{120905}{120937}But did you ever tell him|she was false?
{120949}{120975}I did.
{121007}{121126}You told a lie, upon my|soul, a lie! A wicked lie!
{121131}{121197}Did you say with cassio?
{121201}{121214}With cassio, mistress.
{121217}{121241}Go to, charm your tongue.
{121244}{121273}I will not charm my tongue.
{121276}{121314}I am bound to speak.
{121327}{121390}My mistress here lies|murdered in her bed.
{121396}{121424}Heaven forfend!
{121485}{121542}Nay, stare not, masters.
{121558}{121614}It is true indeed.
{121682}{121739}Villainy, villainy, villainy!
{121746}{121801}I think upon it, i think i smell it.
{121806}{121877}O villainy! I thought so then.
{121928}{121992}I'll kill myself for grief.
{122013}{122024}What, are you mad?
{122029}{122053}Good gentlemen!
{122062}{122085}I'll charge you get your home.
{122089}{122141}Let me have leave to speak.
{122173}{122271}It is proper i obey him,|but not now.
{122311}{122421}Perchance, lago, i will|never go home.
{122436}{122455}Nay, lay thee down and roar,|for thou hast killed the sweetest
{122532}{122577}innocent that ever|did lift up eye.
{122581}{122607}O, she was foul!
{122609}{122672}Lago knows that she with|cassio hath the act of shame
{122680}{122714}a thousand times committed.
{122717}{122726}O heaven!
{122729}{122801}Cassio confessed it, and she|did gratify his amorous works
{122808}{122842}with that handkerchief!
{122852}{122867}Handkerchief!
{122873}{122932}- 'Twill out, 'twill out!|- Hold your peace.
{122936}{123005}I peace? No! I will speak as|liberal as the north!
{123008}{123029}Be wise.
{123038}{123167}Heaven! A man, devil did|them all, all, all!
{123172}{123245}I shame against me,|yet i'll speak.
{123254}{123328}Oh, thou dull moor, that|handkerchief thou speaks of
{123333}{123411}i found by fortune, and did|give my husband
{123810}{123955}she was chaste, she loved thee.
{124086}{124135}She loved thee.
{124495}{124573}Othello, did you and he|consent in cassio's death?
{124575}{124599}Ay.
{124601}{124657}Dear general, i never gave|you cause.
{124664}{124736}Othello, your power and|your command is taken off,
{124749}{124796}and cassio rules in cyprus.
{124885}{124980}Be not afraid though you do|see me weaponed.
{125089}{125157}Here is my journey's end.
{125182}{125280}Here is my butt, the very|seamark of my utmost sail.
{125382}{125536}Will you, i pray, demand that|demi-devil why he hath thus
{125540}{125581}ensnared my soul and body?
{125620}{125653}Demand me nothing.
{125725}{125773}What you know, you know.
{125844}{125940}Are there no stones in heaven|but what serves for the thunder?
{126677}{126844}I pray you, when you shall|these unlucky deeds relate,
{126918}{126954}speak of me as i am.
{127025}{127095}Nothing extenuate, nor set|down aught in malice.
{127164}{127382}Then must you speak of one that|loved not wisely, but too well.
{127441}{127523}Of one not easily jealous,|but being wrought,
{127584}{127788}perplexed in the extreme,|of one whose hand like the
{127795}{127991}base indian, threw a pearl|away richer than all his tribe.
{128090}{128140}Set you down this.
{128190}{128290}>> Napisy pobrane z http://napisy.org <<|>>>>>>>> nowa wizja napisów <<<<<<<<
