[INFORMATION]
[TITLE]
[AUTHOR]
[SOURCE]
[PRG]
[FILEPATH]
[DELAY]0
[CD TRACK]0
[COMMENT]
[END INFORMATION]
[SUBTITLE]
[COLF]&H00FFFF,[STYLE]no,[SIZE]19,[FONT]Verdana
00:00:40.02,00:01:02.02
Dogma.1999.720p.BluRay.x264-SEPTiC[br]Edited By FaLee - 15-03-2008

00:02:06.23,00:02:09.79
Ladies and gentlemen, the driving force[br]behind Catholicism WOW! Cardinal Glick.

00:02:17.94,00:02:19.04
Thank you.

00:02:19.11,00:02:21.05
Now we all know[br]how the majority...

00:02:21.11,00:02:23.38
and the media in this country...

00:02:23.45,00:02:25.71
view the Catholic church.

00:02:25.78,00:02:28.88
They think of us as a passé,[br]archaic institution.

00:02:28.96,00:02:32.19
People find the Bible obtuse...

00:02:32.26,00:02:33.75
even hokey.

00:02:33.83,00:02:35.92
Now, in an effort to disprove[br]all that...

00:02:36.00,00:02:39.73
the Church has appointed this year[br]as a time of renewal...

00:02:39.80,00:02:41.77
both of faith and of style.

00:02:42.60,00:02:44.90
For example, the crucifix.

00:02:44.97,00:02:47.60
While it has been a time-honored symbol[br]of our faith...

00:02:47.67,00:02:50.73
Holy Mother Church[br]has decided to retire...

00:02:50.81,00:02:52.40
this highly recognizable...

00:02:52.48,00:02:54.78
yet wholly depressing image...

00:02:54.85,00:02:57.04
of our Lord, crucified.

00:02:57.12,00:03:00.49
Christ didn't come to Earth[br]to give us the willies.

00:03:00.56,00:03:02.42
He came to help us out.

00:03:02.49,00:03:06.19
He was a booster, and it's[br]with that take on our Lord in mind...

00:03:06.26,00:03:09.03
that we've come up with a new,[br]more inspiring Sigil.

00:03:09.86,00:03:13.03
So, it is with great pleasure[br]that I present you with the first...

00:03:13.10,00:03:15.76
of many revamps[br]the Catholicism Wow! Campaign...

00:03:15.84,00:03:19.27
will unveil over the next year,[br]I give you...

00:03:19.34,00:03:20.57
"The Buddy Christ."

00:03:30.39,00:03:33.45
That's not the sanctioned term[br]we're using for the symbol.

00:03:33.52,00:03:35.92
Just something we've been[br]kicking around the office.

00:03:35.99,00:03:37.39
But look at it.

00:03:37.46,00:03:39.29
Doesn't it pop?

00:03:39.36,00:03:40.99
Buddy Christ.

00:03:41.16,00:03:43.19
Well, there you have it.

00:03:43.27,00:03:45.17
Let me get this straight.

00:03:45.24,00:03:48.83
You don't believe in God[br]because of Alice in Wonderland?

00:03:48.91,00:03:50.93
No, Through the Looking Glass.

00:03:51.01,00:03:52.94
That poem,[br]"The Walrus and the Carpenter"...

00:03:53.01,00:03:55.24
that's an indictment[br]of organized religion.

00:03:55.31,00:03:57.34
The Walrus, with his girth[br]and his good nature...

00:03:57.42,00:03:59.44
he obviously represents either Buddha...

00:03:59.52,00:04:02.54
or with his tusks,[br]the Hindu elephant god, Lord Ganesha.

00:04:02.62,00:04:04.61
That takes care[br]of your Eastern religions.

00:04:04.69,00:04:07.42
Now, the Carpenter, which is[br]an obvious reference to Jesus Christ...

00:04:07.49,00:04:11.12
who was raised a carpenter's son,[br]he represents the Western religions.

00:04:11.20,00:04:13.66
Now, in the poem,[br]what do they do?

00:04:13.73,00:04:16.29
They dupe all these oysters[br]into following them...

00:04:16.37,00:04:20.14
and then proceed to shuck and devour[br]the helpless creatures en masse.

00:04:20.21,00:04:23.14
I don't know what that says to you,[br]but to me it says...

00:04:23.21,00:04:26.98
that following these faiths[br]based on mythological figures...

00:04:27.05,00:04:29.78
ensures the destruction[br]of one's inner-being.

00:04:29.85,00:04:31.94
Organized religion destroys[br]who we are...

00:04:32.02,00:04:34.85
by inhibiting our actions,[br]by inhibiting our decisions...

00:04:34.92,00:04:38.29
out of fear of some[br]intangible parent figure...

00:04:38.36,00:04:41.35
who shakes a finger at us[br]from thousands of years ago...

00:04:41.43,00:04:45.33
and says, " Do it...[br]Do it and I'll fuckin' spank you!"

00:04:45.40,00:04:46.77
Oh, Jesus!

00:04:46.84,00:04:50.43
The way you put it, I've never really[br]thought about it like that before.

00:04:51.34,00:04:53.83
What have I been doing[br]with my life?

00:04:54.78,00:04:57.30
- What am I?[br]- Yeah, I know.

00:04:57.38,00:04:59.18
Listen, my advice to you...

00:04:59.25,00:05:01.81
you take this money that you've[br]been collecting for your parish...

00:05:01.88,00:05:05.08
go get yourself a nice dress,[br]fix yourself up.

00:05:05.15,00:05:08.39
Find some man... find some woman... you[br]can connect with, even for a moment...

00:05:08.46,00:05:11.55
'cause that's really all life is,[br]Sister... a series of moments.

00:05:12.70,00:05:14.63
Why don't you seize yours?

00:05:17.87,00:05:19.27
That a girl.

00:05:27.28,00:05:29.21
You know, here's what[br]I don't get about you.

00:05:29.28,00:05:32.11
You know for a fact[br]that there is a God.

00:05:32.18,00:05:35.02
You've been in His presence.[br]He's spoken to you personally.

00:05:35.09,00:05:38.32
- Yet I heard you claim to be atheist.[br]- I like to fuck with the clergy, man.

00:05:38.39,00:05:41.83
I just love it. I love to keep[br]those guys on their toes.

00:05:41.89,00:05:43.83
Here's what I don't get about you.

00:05:43.90,00:05:46.66
Why do you feel the need[br]to come to this place all the time?

00:05:46.73,00:05:49.20
My friend, because[br]this is humanity at its best.

00:05:49.27,00:05:50.46
Look at them.

00:05:50.54,00:05:54.40
All that anger, all that mistrust,[br]all that unhappiness...

00:05:54.47,00:05:58.41
forgotten for that one perfect moment[br]when they get off the plane.

00:05:58.48,00:05:59.74
See those two?

00:05:59.81,00:06:03.11
What that guy doesn't know is that the[br]girl cheated on him while she was away.

00:06:03.18,00:06:05.12
- She did?[br]- Twice.

00:06:05.19,00:06:07.35
- Nice.[br]- But it doesn't matter right now...

00:06:07.42,00:06:10.36
'cause they're just both so relieved[br]to be with one another.

00:06:11.42,00:06:12.69
I like that.

00:06:12.76,00:06:15.06
I wish they all could[br]feel that way more often.

00:06:15.13,00:06:18.29
Is this why I had to come down here[br]and miss my fucking cartoons?

00:06:18.37,00:06:20.80
You call me, you tell me[br]it's important.

00:06:20.87,00:06:24.33
What, to share in your half-assed[br]obsession with Hallmark moments?

00:06:24.41,00:06:26.46
We're going home.

00:06:26.54,00:06:28.80
Somebody sent us this in the mail.

00:06:33.52,00:06:36.75
Take it and quit leering at me. People[br]will think I just broke up with you.

00:06:36.82,00:06:40.25
- You said we're going home, didn't you?[br]- Read.

00:06:40.32,00:06:44.32
"Cardinal Glick Cuts Ribbon On[br]Catholicism Wow! Campaign."

00:06:44.39,00:06:45.86
And?

00:06:46.93,00:06:49.63
You have to keep reading.

00:06:49.70,00:06:51.83
"The rededication of[br]St. Michael's Church..."

00:06:51.90,00:06:54.30
... is the kickoff of a new campaign[br]which seeks to bring...

00:06:54.37,00:06:56.20
Catholicism into the mainstream.

00:06:56.27,00:06:58.80
With a papal sanction,[br]the archway entrance...

00:06:58.88,00:07:01.34
of the century-old Jersey shore[br]house of worship...

00:07:01.41,00:07:03.81
will serve as a passageway[br]of plenary indulgence...

00:07:03.88,00:07:07.21
a little-known Catholic belief offering[br]all that passes through its arches...

00:07:07.28,00:07:09.15
a morally clean slate.

00:07:09.22,00:07:12.38
For Sunday News Brief,[br]I'm Grant Hicks.

00:07:12.46,00:07:15.95
All I gotta do, I walk through the arch[br]thing, and then I can go back home?

00:07:16.03,00:07:19.52
No. By walking through the archway,[br]all your sins are forgiven.

00:07:19.60,00:07:22.23
- Then all we have to do is die.[br]- Die? I don't wanna die.

00:07:22.30,00:07:26.07
- You rather hang around here?[br]- No. We don't know if we can die.

00:07:26.14,00:07:29.23
But what if we can and then[br]the arch thing doesn't work?

00:07:29.31,00:07:31.10
What then, Hell?[br]Fuck that.

00:07:31.18,00:07:33.11
It's impossible.[br]If we cut off our wings...

00:07:33.18,00:07:36.62
and transubstantiate to complete[br]human form, we become mortal.

00:07:36.68,00:07:39.15
If we die with clean souls,[br]there's no way they can keep us out.

00:07:39.22,00:07:42.35
We won't be angels anymore,[br]but at least we get to go home.

00:07:42.42,00:07:45.82
- Who sent the paper?[br]- Who cares who sent the paper?

00:07:45.89,00:07:48.99
All that matters is that after[br]all these years, we found a loophole.

00:07:49.06,00:07:51.00
He can't keep us out anymore.

00:07:51.06,00:07:53.00
Once we're back in,[br]it'll be forgive and forget.

00:07:53.07,00:07:55.16
But this thing,[br]this is Church law.

00:07:55.24,00:07:57.10
It's not Divine Mandate.

00:07:57.17,00:08:00.77
Church laws are fallible[br]because they're created by man.

00:08:00.84,00:08:04.28
One of the last sacred promises[br]imparted to Peter, the first pope...

00:08:04.35,00:08:07.91
by the Son of God[br]before He left was...

00:08:07.98,00:08:11.18
- "Whatever you hold true on Earth..."[br]- "I'll hold true in Heaven."

00:08:11.25,00:08:14.31
It's dogmatic law. If the Church[br]says it's so, God must adhere.

00:08:14.39,00:08:16.05
This thing has a papal sanction...

00:08:16.12,00:08:19.03
Let it never be said your[br]anal retentive attention to detail...

00:08:19.09,00:08:21.03
never yielded positive results.

00:08:21.10,00:08:23.19
You can't be anal retentive[br]if you don't have an anus.

00:08:23.27,00:08:25.53
Outstanding work!

00:08:25.60,00:08:28.50
There's just one thing[br]I think we gotta do before we leave.

00:08:28.57,00:08:30.70
This is gonna help us get back[br]on His good side.

00:08:30.77,00:08:31.93
What?

00:08:32.01,00:08:34.88
Here. I've been dreaming about this[br]for five years. Read that.

00:08:34.94,00:08:36.41
"Mooby, the Golden Calf.

00:08:36.48,00:08:39.24
Creating an Empire[br]Out of Simplicity."

00:08:39.32,00:08:41.22
I wanna hit 'em.

00:08:41.28,00:08:44.01
You really are[br]just a simple creature.

00:08:44.09,00:08:46.39
We finally find a way back[br]and you want to jeopardize that...

00:08:46.46,00:08:48.55
because you've got a soft spot[br]for the good ol' days.

00:08:48.63,00:08:52.08
What better way to repent than by[br]resuming the position I once denied...

00:08:52.16,00:08:53.65
thanks to you?

00:08:53.73,00:08:56.79
I don't think a killing spree[br]is gonna make things better for us.

00:08:56.87,00:08:59.77
Killing spree?[br]I'm talking about Divine Justice here.

00:08:59.84,00:09:03.17
I'm talking about reigning down fire[br]and brimstone, punishing the wicked.

00:09:03.24,00:09:05.87
He's all about that.[br]I know He'd want this done.

00:09:05.94,00:09:08.64
There hasn't been an Angel of Death[br]since you quit.

00:09:08.71,00:09:10.31
Doesn't that mean anything to you?

00:09:10.38,00:09:13.25
And besides, what if you're wrong,[br]like you always are?

00:09:13.32,00:09:15.95
If I'm wrong... which I'm not...[br]it's not gonna matter.

00:09:16.02,00:09:18.29
We're gonna pass through[br]your arch thing anyway.

00:09:18.36,00:09:21.19
We're gonna be forgiven.[br]No harm, no foul.

00:09:21.26,00:09:24.96
Well, He does hate competition.[br]I will say that.

00:09:25.03,00:09:27.33
And your Mooby certainly falls[br]under that heading.

00:09:27.40,00:09:29.43
Where is this church[br]we have to go to?

00:09:29.50,00:09:32.80
New Jersey. Rededication ceremony[br]is in four days.

00:09:32.87,00:09:34.84
Last four days on Earth?

00:09:34.91,00:09:37.27
If I had a dick,[br]I'd go get laid.

00:09:37.34,00:09:39.47
- We can do the next best thing.[br]- What's that?

00:09:39.55,00:09:41.41
Let's kill people.

00:09:41.48,00:09:43.07
Oh, not you.

00:09:50.02,00:09:53.55
The greater Illinois Chapter[br]of the Right to Life Foundation...

00:09:53.63,00:09:55.93
will be holding its[br]biannual softball game...

00:09:56.00,00:09:57.46
against the Cook County...

00:09:57.53,00:09:59.93
Pro-Choice League next Sunday at 2:00.

00:10:00.00,00:10:02.40
Today's second collection[br]will be donated...

00:10:02.47,00:10:05.30
to the John Doe Jersey Life Fund.

00:10:05.37,00:10:07.74
For those of you[br]who haven't been following the news...

00:10:07.81,00:10:09.90
an unidentified homeless man...

00:10:09.98,00:10:14.11
who was accosted and severely beaten[br]at the New Jersey shore last Tuesday...

00:10:14.18,00:10:18.31
lies in critical, but stable condition[br]in one of that area's hospitals.

00:10:18.39,00:10:20.19
He lacks identification...

00:10:20.26,00:10:23.75
and police have had no luck tracking[br]down any possible family.

00:10:23.83,00:10:28.23
The archbishop of the Trenton diocese[br]has disputed the state's decision...

00:10:28.30,00:10:31.53
to remove the indigent man[br]from life-support systems...

00:10:31.60,00:10:34.33
asking that Catholics[br]all over the country...

00:10:34.41,00:10:37.53
join in this protest against euthanasia.

00:10:39.01,00:10:41.04
Well, now please rise[br]for the recession of faith.

00:10:45.02,00:10:47.58
We believe in one God,[br]the Father Almighty...

00:10:47.65,00:10:49.18
Maker of Heaven and Earth.

00:10:49.25,00:10:52.35
We believe in Jesus Christ,[br]His only Son, Our Lord...

00:10:53.96,00:10:55.29
Choose life!

00:10:55.36,00:10:58.82
You're gonna burn in Hell,[br]ya fuckin' baby killer!

00:10:58.90,00:11:00.69
Holy shit. It's the pope.

00:11:00.77,00:11:02.17
- Huh?[br]- Where?

00:11:02.23,00:11:03.57
What are you talking about?

00:11:12.88,00:11:16.54
Jesus! You're a Catholic.[br]Can't you talk to them?

00:11:16.62,00:11:18.74
They hate me more than you,[br]no doubt.

00:11:18.82,00:11:21.69
At least you have an excuse. You're[br]Jewish. You don't know any better.

00:11:21.76,00:11:25.25
We already used that excuse[br]when we killed Christ.

00:11:25.33,00:11:27.39
Where were you yesterday?[br]We went to brunch.

00:11:27.46,00:11:28.83
I went to church.

00:11:28.90,00:11:30.83
That still kills me,[br]you and church.

00:11:30.90,00:11:34.43
If only they knew your weekly tithing[br]came from a Planned Parenthood check.

00:11:34.50,00:11:36.94
I don't know why I still go, Liz.

00:11:38.21,00:11:41.84
I can remember going to church[br]when I was young and being moved.

00:11:41.91,00:11:45.14
Now I sit there every Sunday[br]and I feel nothing.

00:11:45.21,00:11:47.65
I don't think I have any faith left.

00:11:48.92,00:11:51.85
Remember that seminary student[br]I tried to set you up with?

00:11:53.39,00:11:57.33
The 20-year-old. The one I could[br]have baby-sat for in high school.

00:11:57.39,00:11:59.76
The point is,[br]he told me something.

00:11:59.83,00:12:02.39
He said that faith[br]is like a glass of water.

00:12:02.47,00:12:05.44
When you're young, the glass is little,[br]so it's easy to fill.

00:12:05.50,00:12:07.44
As you get older,[br]the glass gets bigger.

00:12:07.50,00:12:09.53
The same amount of liquid[br]doesn't fill it anymore.

00:12:09.61,00:12:12.44
But periodically[br]the glass has to be refilled.

00:12:12.51,00:12:14.41
You're suggesting I need[br]to get filled?

00:12:14.48,00:12:15.71
In more ways than one.

00:12:15.78,00:12:20.22
You need to get laid, Bethany Sloane.[br]You need a man, if only for 10 minutes.

00:12:20.28,00:12:23.12
It's been my experience that[br]the average male is never a man...

00:12:23.19,00:12:25.59
not even for ten minutes[br]in his entire life span.

00:12:25.66,00:12:28.59
That sounds militant. Are you thinking[br]of joining the other side?

00:12:28.66,00:12:30.56
Couldn't do it.[br]Women are insane.

00:12:30.63,00:12:33.83
Then you need to go back to church[br]and ask God for a third option.

00:12:33.90,00:12:35.83
I think God is dead.

00:12:35.90,00:12:38.34
The sign of a true Catholic.

00:12:48.82,00:12:52.15
Good afternoon, Mrs. Reynolds.

00:12:52.22,00:12:53.91
I'm from the EPA.

00:12:55.06,00:12:57.92
We're checking on possible[br]freon leaks.

00:12:57.99,00:13:00.32
Tell me,[br]do you have air conditioning?

00:13:00.39,00:13:02.09
Yes, we have central air.

00:13:02.16,00:13:03.79
In every room?

00:13:03.86,00:13:05.66
Except the bathroom.[br]Why?

00:13:05.73,00:13:07.76
Well, you do know[br]what that means, don't you?

00:13:19.11,00:13:20.71
Move!

00:13:27.32,00:13:30.95
No pleasure, no rapture,[br]no exquisite sin greater...

00:13:31.73,00:13:33.99
than central air.

00:13:34.70,00:13:36.86
Pick that up.

00:13:39.94,00:13:44.13
This will be the base of operations[br]from here on in.

00:13:44.21,00:13:47.11
Now, if I remember[br]the protocol correctly...

00:13:47.18,00:13:48.61
the powers...

00:13:48.68,00:13:52.08
will attempt to contact[br]the last scion.

00:13:52.15,00:13:54.31
I need you three...

00:13:54.38,00:13:57.51
to shuffle her loose[br]the mortal coil.

00:14:01.53,00:14:02.65
Go.

00:14:36.43,00:14:39.33
Behold the Metatron!

00:14:39.40,00:14:42.20
Herald of the Almighty[br]and voice of the one true God!

00:14:42.27,00:14:44.97
Behold the Metatron!

00:14:45.04,00:14:49.10
Herald of the Almighty[br]and voice of the one true God!

00:15:05.69,00:15:08.56
Sweet Jesus![br]Do you have to use the whole can?

00:15:08.63,00:15:11.66
Who the fuck are you and[br]what the fuck are you doing in my room?

00:15:11.73,00:15:14.57
I'm the one that's soaked and she's[br]the one that's surly. That's rich.

00:15:14.64,00:15:16.60
Stupid fucking...

00:15:16.67,00:15:19.00
Get the fuck out of here,[br]now!

00:15:19.07,00:15:21.70
Or you'll do what exactly?

00:15:21.78,00:15:23.97
Hit me with that fish?

00:15:28.82,00:15:31.84
Now, just sit down on the bed[br]and shut up.

00:15:31.92,00:15:34.52
Jesus wept!

00:15:34.59,00:15:36.36
Look at my suit.

00:15:38.00,00:15:40.26
Just take whatever you want,[br]but don't kill or rape me.

00:15:40.33,00:15:44.73
Give over! I couldn't rape you[br]if I wanted to. Angels are ill-equipped.

00:15:46.94,00:15:48.43
See?

00:15:51.11,00:15:53.94
I'm as anatomically-impaired[br]as a Ken doll.

00:15:55.01,00:15:57.21
Make yourself useful[br]and give me that towel.

00:15:58.35,00:16:00.68
You bottom-feeders[br]and your arrogance.

00:16:00.75,00:16:03.45
You think everybody's just trying[br]to get in your knickers.

00:16:03.52,00:16:05.11
What are you?

00:16:05.19,00:16:07.22
I'm pissed off is what I am.

00:16:07.29,00:16:11.35
Do you drench everyone who comes in your[br]room with flame-retardant chemicals?

00:16:11.43,00:16:14.30
No wonder you're single.

00:16:17.94,00:16:19.53
Stand back.

00:16:28.88,00:16:30.87
As I was sayin'...

00:16:30.95,00:16:34.18
prior to your fire-fighting episode...

00:16:34.96,00:16:37.72
I am the Metatron.

00:16:41.13,00:16:43.26
Don't tell me the name[br]doesn't ring a bell?

00:16:45.00,00:16:46.47
You people.

00:16:46.53,00:16:49.73
If there isn't a movie about it,[br]it's not worth knowing, is it?

00:16:51.57,00:16:53.77
I am a seraphim.

00:16:55.14,00:16:58.44
The highest choir of angels.

00:16:59.75,00:17:01.68
You do know what an angel is,[br]don't you?

00:17:04.72,00:17:07.38
Metatron acts as the voice of God.

00:17:07.46,00:17:11.69
Any documented occasion when some yahoo[br]claims that God has spoken to them...

00:17:11.76,00:17:13.49
they're speaking to me.

00:17:13.56,00:17:15.76
Or they're talking to themselves.

00:17:17.83,00:17:19.96
Why doesn't God speak for Himself?

00:17:20.84,00:17:24.21
Glad you decided to join[br]the conversation. To answer that...

00:17:24.28,00:17:27.51
human beings have neither the aural,[br]nor the psychological capacity...

00:17:27.58,00:17:32.04
to withstand the awesome power[br]of God's true voice.

00:17:32.12,00:17:35.55
Were you to hear it, your mind would[br]cave in and your heart would explode.

00:17:35.62,00:17:38.49
We went through five Adams[br]before we figured that one out.

00:17:39.52,00:17:42.39
Well, how do I know[br]you're an angel?

00:17:42.46,00:17:46.80
Aside from the fiery entrance[br]and the expansive wingspan?

00:17:49.60,00:17:51.54
You want more proof?

00:17:51.60,00:17:53.30
Fine.

00:17:53.37,00:17:54.50
How about tequila?

00:18:01.85,00:18:05.75
- Where the hell are we?[br]- Only place you can go for good tequila.

00:18:05.82,00:18:08.91
Dos tequilas, por favor,[br]and an empty glass.

00:18:10.92,00:18:12.69
We're in Mexico?

00:18:12.76,00:18:15.19
Actually, we're in a franchised[br]Mexican family eatery...

00:18:15.26,00:18:17.49
down the street[br]from your apartment, but...

00:18:17.56,00:18:19.43
it's impressive nonetheless.

00:18:19.50,00:18:24.17
You don't mind I lost the wings, do you?[br]I'm trying to keep our profile low.

00:18:24.24,00:18:26.04
What do you want with me?

00:18:28.61,00:18:32.51
I am to charge you[br]with a holy crusade.

00:18:32.58,00:18:35.88
For the record,[br]I work in an abortion clinic.

00:18:35.95,00:18:38.32
Noah was a drunk.[br]Look what he accomplished.

00:18:38.39,00:18:42.29
And no one's asking you to build an ark.[br]All you gotta do is go to New Jersey...

00:18:42.36,00:18:44.92
and visit a small church[br]on a very important day.

00:18:49.43,00:18:50.66
New Jersey?

00:18:51.87,00:18:53.96
That doesn't sound like[br]much of a crusade.

00:18:54.04,00:18:56.56
Aside from the fine print,[br]that's it.

00:18:56.64,00:18:58.70
What's the fine print?

00:18:59.91,00:19:02.71
Stop a couple of angels from entering[br]and thus negating all existence.

00:19:02.78,00:19:04.97
Wait, wait, wait.[br]Repeat that.

00:19:05.05,00:19:08.31
Stop a couple of angels[br]from entering...

00:19:08.39,00:19:11.55
and thus negating all existence.

00:19:11.62,00:19:13.92
I hate it when people[br]need it spelled out for them.

00:19:13.99,00:19:15.82
You might want to clarify that.

00:19:17.06,00:19:21.26
Back in the old days,[br]God was vengeful and hot-tempered.

00:19:21.33,00:19:23.46
And His wrath was bore...

00:19:23.54,00:19:26.77
by the Angel of Death,[br]name of Loki.

00:19:26.84,00:19:29.00
When Sodom and Gomorrah was destroyed...

00:19:29.07,00:19:30.56
that was Loki.

00:19:30.64,00:19:34.70
When the waters wiped out everything[br]except Noah and his menagerie...

00:19:34.78,00:19:37.51
that was Loki...[br]and he was good at what he did.

00:19:37.58,00:19:39.35
But one day...

00:19:39.42,00:19:42.39
he refused to bear God's wrath[br]any longer.

00:19:43.09,00:19:45.96
- Why?[br]- He listened to his friend...

00:19:46.03,00:19:48.08
a Grigori[br]by the name of Bartleby.

00:19:48.16,00:19:49.29
Grigori?

00:19:49.36,00:19:52.59
One of the choirs of angels.[br]They're called Watchers.

00:19:52.67,00:19:54.10
Guess what they do.

00:19:54.17,00:19:58.61
So one day, Loki's wiping out[br]all the firstborn of Egypt...

00:19:58.67,00:20:01.16
The Tenth Plague.

00:20:01.24,00:20:04.04
Tell a person that you're the Metatron[br]and they stare at you blankly.

00:20:04.11,00:20:06.20
Mention something out of[br]a Charlton Heston movie...

00:20:06.28,00:20:08.44
and suddenly everybody's[br]a theology scholar.

00:20:08.52,00:20:10.45
May I continue uninterrupted?

00:20:10.52,00:20:12.61
Once he's done with the firstborn...

00:20:12.69,00:20:17.39
Loki takes his friend Bartleby out[br]for a post-slaughter drink.

00:20:17.46,00:20:19.79
And over many rounds...

00:20:19.86,00:20:21.99
they get into[br]this discussion about...

00:20:22.06,00:20:23.96
whether or not murder[br]in the name of God is okay.

00:20:24.03,00:20:25.40
And in the end...

00:20:25.47,00:20:29.40
Bartleby convinces Loki[br]to quit his position...

00:20:29.47,00:20:31.80
and take one which doesn't[br]involve slaughter.

00:20:31.87,00:20:33.47
So...

00:20:34.94,00:20:37.35
very inebriated...

00:20:37.41,00:20:40.08
Loki tells God he quits...

00:20:40.15,00:20:42.45
throws down his fiery sword...

00:20:42.52,00:20:44.45
and gives Him the finger.

00:20:44.52,00:20:47.72
Which ruins it for the rest of us[br]because from that day forward...

00:20:47.79,00:20:50.85
God decreed that angels[br]could no longer imbibe alcohol.

00:20:50.93,00:20:52.40
Hence all the spitting.

00:20:53.23,00:20:54.89
So, for their insolence...

00:20:54.97,00:20:57.96
God decreed that neither Loki[br]nor Bartleby...

00:20:58.04,00:21:00.60
would ever be allowed[br]back into Paradise.

00:21:00.67,00:21:02.54
- Were they sent to Hell?[br]- Worse.

00:21:02.61,00:21:04.54
Wisconsin...

00:21:04.61,00:21:07.54
for the entire span[br]of human history.

00:21:07.61,00:21:10.78
And when the world ends, they'll have to[br]sit outside the gates for all eternity.

00:21:10.85,00:21:12.84
And this has what to do with me?

00:21:12.92,00:21:17.45
Someone has clued them in[br]to a loophole in Catholic dogma...

00:21:17.52,00:21:20.12
that would allow them[br]to reenter Heaven.

00:21:20.19,00:21:22.89
So what? They beat the system.[br]Good for them.

00:21:22.96,00:21:24.86
It's not that simple.

00:21:24.93,00:21:29.03
If they get in,[br]they will have reversed God's decree.

00:21:30.70,00:21:33.64
Now listen closely because[br]this bit's very important.

00:21:34.81,00:21:38.84
Existence in all its form[br]and splendor...

00:21:38.91,00:21:42.58
function solely on one principle...

00:21:42.65,00:21:45.68
God is infallible.

00:21:45.75,00:21:47.69
To prove Him wrong...

00:21:47.76,00:21:50.72
would undo reality[br]and everything that is.

00:21:50.79,00:21:53.69
Up would become down,[br]black would become white.

00:21:53.76,00:21:56.73
Existence would become nothingness.

00:21:56.80,00:21:58.39
In essence...

00:21:59.47,00:22:01.94
if they're allowed to enter[br]that church...

00:22:03.77,00:22:06.76
they'll unmake the world.

00:22:06.84,00:22:09.74
If this is so major,[br]why are you talking to me?

00:22:09.81,00:22:12.58
- Why doesn't God do something about it?[br]- He could.

00:22:12.65,00:22:15.78
But He'd rather see you[br]take care of this one personally.

00:22:15.85,00:22:17.48
Why me?

00:22:17.55,00:22:19.85
Because of who you are.

00:22:19.92,00:22:21.79
And who am I?

00:22:21.86,00:22:23.99
The girl in the pj's!

00:22:24.06,00:22:27.76
Don't ask so many questions.[br]Just serve your purpose.

00:22:27.83,00:22:29.86
I'm gonna have to pass.

00:22:30.77,00:22:31.93
I beg your pardon?

00:22:32.00,00:22:36.44
When some quiet little infection[br]destroyed my uterus, where was God?

00:22:36.51,00:22:38.13
When my husband decided...

00:22:38.21,00:22:40.64
he couldn't be with a wife[br]who couldn't bear his children...

00:22:40.71,00:22:42.01
where was God?

00:22:44.45,00:22:45.71
To Hell with Him.

00:22:45.78,00:22:50.02
Don't allow eons of history and life[br]to get blinked out of being...

00:22:50.09,00:22:52.39
just because you've got a grudge[br]against your Creator.

00:22:52.46,00:22:54.89
So you lost the ability[br]to make life.

00:22:54.96,00:22:58.45
You're being offered the chance[br]to play mother to the world...

00:22:58.53,00:23:00.83
by acting like one[br]and protecting it...

00:23:00.90,00:23:02.83
saving it!

00:23:05.37,00:23:07.31
But I can't make you.

00:23:08.41,00:23:11.04
However, if you should decide[br]to stop being selfish...

00:23:11.11,00:23:13.60
and accept your responsibility...

00:23:13.68,00:23:15.58
you won't be alone.

00:23:15.65,00:23:17.01
You'll have support.

00:23:17.08,00:23:19.18
What? More angels?

00:23:19.25,00:23:20.84
Prophets.

00:23:22.79,00:23:25.82
In a manner of speaking.[br]Two of 'em.

00:23:28.40,00:23:30.89
The one who speaks...

00:23:30.97,00:23:34.53
and he will, at great length,[br]whether you want him to or not...

00:23:34.60,00:23:36.63
will make mention of himself[br]as a prophet.

00:23:36.70,00:23:38.19
The other one...

00:23:39.17,00:23:40.94
well, he's the quiet type.

00:23:41.01,00:23:42.27
Look, I've gotta go.

00:23:42.34,00:23:44.68
Remember, we're working[br]in a time frame here.

00:23:49.12,00:23:50.31
What's He like?

00:23:50.39,00:23:51.35
God?

00:23:53.42,00:23:55.08
Lonely...

00:23:55.16,00:23:57.06
but funny.

00:23:57.13,00:23:59.29
He's got a great sense of humor.

00:23:59.36,00:24:01.30
Take sex, for example.[br]There's nothing funnier...

00:24:01.36,00:24:04.03
than the ridiculous faces[br]you people make mid-coitus.

00:24:04.10,00:24:06.03
Sex is a joke in Heaven?

00:24:06.10,00:24:09.94
The way I understand it,[br]it's mostly a joke down here too.

00:24:10.01,00:24:11.27
I'll see ya.

00:26:14.34,00:26:17.17
Snootch to the motherfucking nootch!

00:26:53.31,00:26:56.72
Go back to your paper routes,[br]you Mighty Duck Fucks!

00:26:57.85,00:27:00.32
Snoogans.[br]Did you see that shit, man?

00:27:00.39,00:27:04.05
I know they were just kids, but we[br]kicked their fucking pube-less asses!

00:27:09.90,00:27:12.33
I don't know what to say[br]or think, except...

00:27:12.40,00:27:14.37
That you'll offer us sex[br]as a reward?

00:27:14.44,00:27:17.67
That I'd like to know[br]who they and you are.

00:27:17.74,00:27:20.64
I'm Jay, and this is[br]my hetero life mate, Silent Bob.

00:27:20.71,00:27:23.24
I don't know who those kids were,[br]but they would have kicked yours...

00:27:23.31,00:27:26.25
and Lunchbox's asses[br]if I hadn't represented.

00:27:26.32,00:27:29.15
Thanks for being[br]out here so late.

00:27:29.22,00:27:31.41
Wait a minute.[br]Are you protestors?

00:27:31.49,00:27:34.48
You mean those dickheads with the signs[br]and pictures of dead babies?

00:27:34.56,00:27:37.03
Shit no![br]Me and Silent Bob are pro-choice.

00:27:37.09,00:27:39.06
A woman's body[br]is her own fucking business.

00:27:39.13,00:27:41.12
But what are you doing[br]hanging around?

00:27:41.20,00:27:43.22
We're here to pick up chicks.

00:27:43.30,00:27:45.03
Excuse me?

00:27:45.10,00:27:48.27
We figure abortion clinics are[br]a good place to meet loose women.

00:27:48.34,00:27:51.10
Why else would they be here[br]unless they like to fuck?

00:27:52.01,00:27:54.10
Right.

00:27:54.18,00:27:56.98
Well, I should be going.[br]Thanks for the rescue.

00:27:57.05,00:27:58.95
- I think.[br]- Wait a second.

00:27:59.02,00:28:01.61
We just saved your ass,[br]and you're just gonna take off.

00:28:01.69,00:28:02.78
What the shit is that?

00:28:02.86,00:28:06.76
I had a weird night last night and[br]tonight's not shaping up to be better.

00:28:06.83,00:28:09.79
I think I should go home,[br]take some Percosets and lay down.

00:28:11.16,00:28:14.62
Now how about that shit?[br]Fuck this town, man!

00:28:14.70,00:28:17.23
I'm goin' back to Jersey[br]and startin' up the business again.

00:28:17.30,00:28:21.14
I can kick the shit out of kids[br]in Red Bank and make myself a profit.

00:28:21.21,00:28:23.80
Prophets. Two of ‘em.

00:28:23.88,00:28:27.58
- You know what I'm sayin', Silent Bob?[br]- You gotta be kidding me.

00:28:27.65,00:28:30.34
We call this piece "The Fecalator."

00:28:30.42,00:28:33.05
One look at it and the target[br]shits him or herself.

00:28:33.12,00:28:34.55
Try it on.

00:28:35.62,00:28:39.92
It's a lot more compact than the flaming[br]sword, but not nearly as impressive.

00:28:39.99,00:28:43.29
It doesn't have that[br]"Wrath of the Almighty" edge to it.

00:28:43.37,00:28:47.50
How am I supposed to strike fear into[br]hearts of the wicked with this thing?

00:28:47.57,00:28:48.66
Look at this.

00:28:48.74,00:28:53.44
Well, then, you know, don't use a gun.[br]Lay the place to waste like.

00:28:53.51,00:28:56.50
Easy for you to say.[br]You get off light in a razing.

00:28:56.58,00:28:58.77
You got to stand there and read[br]at Sodom and Gomorrah.

00:28:58.85,00:29:00.78
I had to do all the work.

00:29:00.85,00:29:04.12
What work did you do?[br]You lit a few fires.

00:29:04.19,00:29:06.78
I rained down sulfur.[br]There's a subtle difference.

00:29:06.86,00:29:08.59
Okay, I'm sure.

00:29:08.66,00:29:12.72
Fuck you. Any moron with a pack[br]of matches can set a fire.

00:29:12.80,00:29:14.73
Raining down sulfur[br]is like an endurance trial.

00:29:14.80,00:29:17.46
Mass genocide is the most[br]exhausting activity one can engage in...

00:29:17.53,00:29:19.09
next to soccer.

00:29:20.44,00:29:22.30
I'll take this one.

00:29:35.75,00:29:39.21
So, what's up? You have a friend for[br]Silent Bob, or are you gonna do us both?

00:29:39.29,00:29:41.69
If so, I'm first.[br]I hate sloppy seconds.

00:29:41.76,00:29:43.79
You're a man of principle.

00:29:43.86,00:29:47.49
Jersey's pretty far from McHenry.[br]May I ask what brought you here?

00:29:47.57,00:29:50.06
Some fuck named John Hughes.

00:29:50.14,00:29:51.83
Sixteen Candles John Hughes?

00:29:52.67,00:29:56.11
You know that guy too?[br]That fuckin' guy.

00:29:56.18,00:29:58.94
He made this flick Sixteen Candles.[br]Not bad.

00:29:59.01,00:30:01.24
There's tits in it, but no bush.

00:30:01.31,00:30:03.94
But Ebert over here don't give[br]a shit about that kind of thing...

00:30:04.02,00:30:06.42
because he's like in love[br]with this John Hughes guy.

00:30:06.49,00:30:08.65
He goes out and rents[br]every one of his movies.

00:30:08.72,00:30:13.18
Fuckin' Breakfast Club, where stupid[br]kids actually show up for detention.

00:30:13.26,00:30:17.03
Fuckin' Weird Science, where this babe[br]wants to undress and get down...

00:30:17.10,00:30:20.30
but, oh, no, she don't,[br]because it's a PG movie.

00:30:20.37,00:30:24.53
And then Pretty in Pink, which I can't[br]watch with this tubby bitch anymore...

00:30:24.61,00:30:27.97
because when the redhead hooks up[br]with her dream guy...

00:30:28.04,00:30:31.57
he starts sobbin' like a little bitch[br]with a skinned knee and shit.

00:30:31.65,00:30:34.88
And there's nothing worse[br]than watchin' a fuckin' fat man weep.

00:30:34.95,00:30:36.92
What exactly brought you[br]to Illinois?

00:30:36.99,00:30:40.89
All these movies take place in this[br]small town called Shermer, Illinois...

00:30:40.96,00:30:45.09
where all the honeys are top-shelf[br]but all the dudes are whiny pussies.

00:30:45.16,00:30:48.13
Except for Judd Nelson.[br]He was fuckin' harsh.

00:30:48.20,00:30:49.50
But best of all...

00:30:49.57,00:30:51.69
there was no one dealin', man.

00:30:51.77,00:30:54.24
Then it hits me.[br]We could live like phat rats...

00:30:54.30,00:30:56.60
if we were the blunt connection[br]in Shermer, Illinois.

00:30:56.67,00:30:59.84
So we collected some money[br]we were owed and caught a bus.

00:30:59.91,00:31:03.00
But you know what the fuck[br]we found out when we got there?

00:31:03.08,00:31:05.98
There is no Shermer, Illinois.

00:31:06.05,00:31:08.02
Movies are fuckin' bullshit.

00:31:08.09,00:31:12.08
- When are you going back to New Jersey?[br]- This broad asks a lot of questions.

00:31:12.16,00:31:15.32
- Tomorrow.[br]- Tomorrow.

00:31:15.39,00:31:17.26
Yeah. So you do anal?

00:31:17.33,00:31:19.85
Is it true that chicks fart[br]if you blast them in the ass?

00:31:19.93,00:31:21.83
I didn't ask you out for sex.

00:31:21.90,00:31:23.83
I'll take head.

00:31:26.30,00:31:29.83
This is gonna sound really bad. I can't[br]believe I'm even thinking about this.

00:31:32.41,00:31:34.35
I think I should go with you.

00:31:34.41,00:31:37.35
Like steady?[br]You wanna be my girlfriend?

00:31:38.48,00:31:41.42
All right, but Silent Bob gets[br]to live with us and you pay the rent.

00:31:41.49,00:31:44.32
No. I wanna go with you[br]to New Jersey.

00:31:44.39,00:31:45.48
Really?

00:31:45.56,00:31:47.65
You're going to lead me somewhere.

00:31:47.73,00:31:49.39
Me lead you?

00:31:49.46,00:31:52.43
Lady, look at me. I don't even know[br]where I am half the time.

00:31:52.50,00:31:55.49
If we're not gonna fuck, then what[br]the fuck did you ask us out for?

00:31:55.57,00:31:59.63
Someone told me I'd meet you and you'd[br]take me someplace I was supposed to go.

00:31:59.71,00:32:01.70
What the hell are you babbling about?

00:32:01.78,00:32:04.47
We saved your ass from[br]some angry fuckin' dwarves...

00:32:04.55,00:32:08.31
and now we're supposed to take you[br]somewhere as if we know where it is?

00:32:10.25,00:32:12.01
Do you believe in God?

00:32:13.49,00:32:16.75
Holy fuck! All the fine, immoral bitches[br]out in front of that place...

00:32:16.83,00:32:18.76
and we gotta get the one Jesus freak?

00:32:18.83,00:32:20.09
- Let's get the fuck out of here.[br]- Wait.

00:32:20.16,00:32:21.86
- I'll scream rape.[br]- I can pay you.

00:32:22.80,00:32:24.23
Pay?

00:32:26.90,00:32:28.87
A hundred bucks[br]for being my guide.

00:32:28.94,00:32:33.03
You were going to Jersey anyway.[br]All I'm asking is to tag along.

00:32:33.11,00:32:36.60
I feel like Han Solo, you're Chewie,[br]and she's Ben Kenobi...

00:32:36.68,00:32:39.08
and we're in that fucked-up bar!

00:32:39.15,00:32:40.67
What about sex?

00:32:40.75,00:32:42.08
No sex.

00:32:44.16,00:32:48.02
Let's say we're caught in a situation[br]where we have five minutes left to live.

00:32:48.09,00:32:51.58
A bomb or something's gonna go off.[br]Would you fuck us then?

00:32:51.66,00:32:53.69
In that highly unlikely situation?

00:32:57.07,00:32:58.26
Yeah, sure.

00:32:59.81,00:33:01.40
She's a slut.

00:33:03.71,00:33:05.30
All right.

00:33:07.41,00:33:08.88
But I get to drive.

00:33:17.99,00:33:20.46
What gear are you in?

00:33:20.53,00:33:21.72
Gear?

00:33:30.67,00:33:33.27
What do I know about shiftin'?

00:33:36.88,00:33:38.54
Like I ever drove before.

00:33:42.95,00:33:45.28
Indiana, Ohio, Pennsylvania...

00:33:45.35,00:33:46.75
New Jersey.

00:33:46.82,00:33:48.95
Maybe you're wrong[br]about this slaughter thing.

00:33:49.02,00:33:53.15
How can you be sure what incurs the[br]Lord's wrath these days? Times change.

00:33:53.23,00:33:56.96
I remember eating meat on a Friday[br]used to be a Hell-worthy trespass.

00:33:57.03,00:33:59.50
The major sins never change.

00:34:00.97,00:34:05.67
Besides, I can spot[br]a commandment-breaker from a mile away.

00:34:05.74,00:34:07.61
Bet on it.

00:34:07.68,00:34:10.41
This from the guy who still owes me[br]ten bucks over that bet...

00:34:10.48,00:34:13.68
about which was gonna be the bigger[br]movie... ET or Krush Groove.

00:34:13.75,00:34:16.84
Fuck you, man,[br]'cause time's gonna tell on that one.

00:34:20.42,00:34:23.99
Are you insinuating that I don't have[br]what it takes anymore?

00:34:24.06,00:34:25.62
Insinuating, no.

00:34:25.70,00:34:28.26
Flat-out telling you.

00:34:31.27,00:34:33.36
Right there.[br]There's one.

00:34:33.44,00:34:35.84
So? They're kissing.

00:34:35.91,00:34:36.87
Adultery.

00:34:36.94,00:34:39.24
- Adultery?[br]- Adultery.

00:34:39.31,00:34:41.28
You are just a simple creature.

00:34:41.35,00:34:43.94
- Am I right?[br]- I happen to know the truth.

00:34:44.02,00:34:47.04
I'm not gonna tell you. I want to see[br]how boned up on the job you are.

00:34:47.12,00:34:49.92
- What's your proof?[br]- He's wearing a wedding band.

00:34:49.99,00:34:52.68
And it never occurred to you[br]that maybe she's his wife?

00:34:52.76,00:34:55.06
No married man kisses[br]his wife like that.

00:34:55.13,00:34:57.89
Okay. It's a good thing[br]you were never...

00:34:57.96,00:35:00.96
the deciding member on a jury[br]is all I'm saying.

00:35:01.03,00:35:04.90
"No married man kisses[br]his wife like that"? Are you stoned?

00:35:04.97,00:35:06.06
Excuse me.

00:35:08.84,00:35:10.33
Are you married?

00:35:10.41,00:35:12.21
Why?

00:35:12.28,00:35:13.75
I'm just curious.

00:35:13.81,00:35:16.11
What do you think?

00:35:24.59,00:35:27.15
- What?[br]- To her?

00:35:27.23,00:35:29.29
- What?[br]- Are you married to her?

00:35:29.36,00:35:32.80
Not that it's any of[br]your fucking business, but no.

00:35:32.87,00:35:34.70
Why?

00:36:19.38,00:36:21.51
Whose house

00:36:21.59,00:36:24.05
Run's house

00:36:24.12,00:36:26.75
I said, whose house

00:36:26.82,00:36:28.76
Run's house

00:36:28.83,00:36:30.95
Whose house[br]Say what

00:36:31.03,00:36:33.36
Run's house[br]Say what

00:36:33.43,00:36:35.26
Martin

00:36:39.10,00:36:42.16
She's fuckin' pissed, dude.[br]She's never gonna fuck us now.

00:36:42.24,00:36:44.23
Maybe you,[br]but definitely not me.

00:36:44.31,00:36:46.51
Let me know how she is.

00:36:46.58,00:36:49.45
Nobody is fucking me![br]You got that?

00:36:50.28,00:36:52.55
I don't know what I was thinking[br]in that diner...

00:36:52.62,00:36:55.88
but being that I've decided to go home,[br]and not to New Jersey...

00:36:55.96,00:36:58.45
sorry for the inconvenience[br]and good-bye.

00:36:59.23,00:37:00.69
You're breaking up with us?

00:37:02.00,00:37:04.36
Who the hell do you think[br]you are, lady?

00:37:04.43,00:37:07.42
You can't just go around[br]breaking people's hearts like that!

00:37:07.50,00:37:10.80
I fell in love with you![br]We fell in love with you!

00:37:10.87,00:37:14.00
Guys like us just don't fall out[br]of the fuckin' sky.

00:37:21.88,00:37:25.65
Beautiful, naked, big-tittied women[br]just don't fall out of the sky.

00:37:39.64,00:37:41.33
No heartbeat.

00:37:41.40,00:37:44.00
Think someone threw him out of a plane[br]with a message written on him...

00:37:44.07,00:37:45.60
like in Con Air?

00:37:45.68,00:37:48.37
- Did you ever see that flick?[br]- Oh, did that suck!

00:37:48.45,00:37:51.11
- Con Air? Con Shit.[br]- Kill it!

00:37:51.18,00:37:54.28
- Sounds familiar.[br]- Jesus, are you okay?

00:37:54.35,00:37:56.44
Yeah, it's Rufus.[br]And yeah, I'm fine.

00:37:56.52,00:37:58.78
He's the fucking undead![br]Cut his head off!

00:37:58.86,00:38:01.72
What I just did gave me[br]a fucking migraine!

00:38:01.79,00:38:05.89
So if you don't pipe down, I'm gonna[br]yank your sac off like a paper towel.

00:38:05.96,00:38:08.43
Speaking of which,[br]you're awfully nude.

00:38:08.50,00:38:11.26
- Rufus, is it?[br]- Yes, Rufus it is.

00:38:11.34,00:38:15.80
It's usually Long Rufus, but it's[br]a little cold out here. You understand?

00:38:15.88,00:38:19.17
Big Papa, how about lending a brother[br]your coat till I find my own threads?

00:38:21.05,00:38:23.31
Dude, he fell out of thin air.

00:38:24.45,00:38:27.78
Dude, his piece is gonna be rubbing[br]inside of your armor.

00:38:27.85,00:38:30.19
- Dude![br]- Thanks a lot, baby.

00:38:31.39,00:38:33.59
I'll do my best to tuck it back.

00:38:33.66,00:38:36.13
It's been a while since physics[br]but I would think...

00:38:36.20,00:38:39.17
the impact with which you hit[br]the asphalt would have liquefied you.

00:38:39.23,00:38:41.00
Death is a worry of the living.

00:38:41.07,00:38:44.56
The dead, like myself, only worry[br]about decay and necrophiliacs.

00:38:44.64,00:38:47.51
- Told you he was the undead.[br]- Not the undead. The dead.

00:38:47.58,00:38:48.60
I died.

00:38:48.68,00:38:50.91
Christ told me the secret[br]to the resurrection once.

00:38:50.98,00:38:54.57
We were at this wedding in Caanan.[br]I got drunk and forgot it.

00:38:54.65,00:38:56.41
Wait, wait, wait.

00:38:56.48,00:38:58.38
Christ?

00:38:58.45,00:39:00.55
You knew Christ?

00:39:00.62,00:39:02.68
Knew him?[br]Shit, nigga owes me 12 bucks.

00:39:02.76,00:39:04.59
Let me guess.

00:39:04.66,00:39:07.19
- You're another angel?[br]- Oh, I ain't no angel.

00:39:07.26,00:39:10.10
I'm a man, just like you and him.[br]Well, maybe not him.

00:39:10.17,00:39:11.79
At least I was a man.

00:39:11.87,00:39:15.00
Been dead nearly 2,000 years.[br]Here, check this out.

00:39:16.14,00:39:19.34
No wonder he saw Jesus.[br]Homey's rockin' the ganj.

00:39:19.41,00:39:21.60
It's not a joint.

00:39:21.68,00:39:23.98
I can't read this.

00:39:24.05,00:39:29.14
It's Aramaic. It says,[br]"Rufus, see you in two years. Jesus."

00:39:29.22,00:39:32.35
Freaked me out because He basically[br]told me when my number was up.

00:39:32.42,00:39:35.26
Took all the flavor out of the[br]remaining years. We gotta get moving.

00:39:35.33,00:39:38.99
Let's say we continue this discussion[br]over a two-piece and a biscuit. Come on.

00:39:39.06,00:39:41.62
I'm starvin'.[br]Back off, Kato.

00:39:41.70,00:39:42.96
Wait a second!

00:39:44.24,00:39:46.76
Between guys with wings,[br]guys falling out of the sky...

00:39:46.84,00:39:48.90
and guys trying like hell[br]to fuck me...

00:39:48.97,00:39:51.97
I think I've been a pretty good sport[br]about all this so far.

00:39:52.04,00:39:55.48
But I'm not going anywhere until[br]I find out where the hell you came from.

00:39:55.55,00:39:57.48
Me? I came from Heaven.

00:39:57.55,00:39:59.07
Now let's start walkin'.

00:39:59.15,00:40:01.99
Walk? Fuck you! Do you know[br]how far we are from anywheres?

00:40:02.05,00:40:06.29
Hey, man, back in the old days[br]with J.C., we used to walk everywhere.

00:40:06.36,00:40:08.62
Did you ever hear of[br]a fat apostle?

00:40:13.23,00:40:15.50
What the hell's an apostle?

00:40:39.23,00:40:40.52
Let me get this straight.

00:40:40.60,00:40:42.86
She's already met the prophets...

00:40:42.93,00:40:45.06
and the apostle's with them?

00:40:48.00,00:40:50.27
I think that our best course[br]of action...

00:40:50.34,00:40:53.87
is to ensure that our parcel[br]is not found.

00:40:53.94,00:40:58.54
And being that I can't even[br]trust you enough to kill a woman...

00:41:00.18,00:41:02.81
well, I'm left with no choice...

00:41:02.89,00:41:06.95
but to seek outside assistance[br]in guarding said package.

00:41:10.36,00:41:12.45
I'm gonna have to summon[br]the Golgothan.

00:41:15.57,00:41:18.00
I appreciate the loan, brother.[br]You can have that back.

00:41:18.07,00:41:21.44
Man, I remember when all we used to have[br]for breakfast was fish and goat's milk.

00:41:21.51,00:41:23.97
- What do you call this shit?[br]- Egga Mooby Muffin.

00:41:24.04,00:41:27.20
Now, how 'bout you start explaining[br]some things, like for starters...

00:41:27.28,00:41:28.71
how did you know[br]where to find us?

00:41:28.78,00:41:31.04
Do you know what the dead do[br]with most of their time?

00:41:31.12,00:41:33.98
Watch the living.[br]Especially in the shower.

00:41:34.05,00:41:35.68
I can't wait to die.

00:41:35.75,00:41:37.59
And why are you watching me?

00:41:37.66,00:41:40.25
Because you're the one who's gonna[br]help me get some changes made...

00:41:40.33,00:41:42.02
in that book[br]you put so much stock in.

00:41:42.09,00:41:44.43
- Hustler?[br]- The Bible!

00:41:44.50,00:41:47.83
- What's your beef with the Bible?[br]- For starters, I'm not in it.

00:41:47.90,00:41:50.50
Neither are any of us, but you[br]don't hear us bitchin' and moanin'.

00:41:50.57,00:41:54.03
But I'm supposed to be in it.[br]I was the 13th Apostle.

00:41:55.58,00:41:59.67
I've gone to church my whole life and[br]never heard of Rufus, the 13th Apostle.

00:41:59.75,00:42:02.51
But you heard of[br]the other 12 Apostles.

00:42:02.58,00:42:06.21
They were all white boys, I might add.[br]But no mention of me, Rufus.

00:42:06.29,00:42:08.81
And why is that?[br]'Cause I'm a black man.

00:42:08.89,00:42:10.95
But you know what?[br]That's just my pet peeve.

00:42:11.03,00:42:15.49
I'm mainly here to correct a major error[br]you've been basing your faith on.

00:42:15.56,00:42:19.12
- What's that?[br]- Jesus wasn't white. Jesus was black.

00:42:19.20,00:42:20.36
I don't buy it.

00:42:20.44,00:42:24.63
If that's true, why did He get[br]written about and you were left out?

00:42:24.71,00:42:26.94
Well, He is the Son of God.

00:42:27.01,00:42:29.17
Kind of hard to have[br]a New Testament without him.

00:42:29.24,00:42:32.04
So you fudge a few facts,[br]you put a spin on his ethnicity.

00:42:32.11,00:42:35.74
Leaving me out is okay 'cause you[br]still got 12 white boys to choose from.

00:42:35.82,00:42:39.45
- Are you gonna listen to this shit?[br]- That's what people of Antioch said...

00:42:39.52,00:42:41.35
right before they stoned my ass.

00:42:41.42,00:42:42.58
You were martyred?

00:42:42.66,00:42:44.59
That's one way of puttin' it.

00:42:44.66,00:42:47.69
Another way is to say I was bludgeoned[br]to shit by big fucking rocks.

00:42:47.76,00:42:50.56
White folks only wanna hear[br]the good shit...

00:42:50.63,00:42:52.93
life eternal,[br]a place in God's Heaven.

00:42:53.00,00:42:55.56
But as soon as you hear[br]that you're gettin' this good shit...

00:42:55.64,00:42:57.33
from a black Jesus, ya freak.

00:42:57.41,00:42:59.67
And that, my friends,[br]is called hypocrisy.

00:42:59.74,00:43:04.41
A black man can steal your stereo,[br]but he can't be your savior.

00:43:04.48,00:43:05.81
You gonna eat that hash brown?

00:43:06.92,00:43:08.82
So, you went to Heaven?

00:43:08.89,00:43:12.15
Damn right I went to Heaven![br]That's the least He could do.

00:43:12.22,00:43:15.66
In the three years I followed His ass[br]around Jerusalem, did I ever get laid?

00:43:15.73,00:43:18.89
Hell no.[br]And I was in my prime.

00:43:18.96,00:43:21.43
I could have been knee-deep[br]in shepherds' daughters...

00:43:21.50,00:43:24.09
not to mention fine-ass[br]Mary Magdalene.

00:43:24.17,00:43:26.10
She had a thing for dark meat,[br]if you follow me.

00:43:26.17,00:43:29.40
Maybe this is just me talking,[br]but if I were in Heaven...

00:43:29.48,00:43:32.41
I wouldn't care what the Bible said[br]as long as they got the message right.

00:43:32.48,00:43:34.61
The message is what counts.

00:43:34.68,00:43:38.48
But folks who build their faith[br]on that message should be colorblind.

00:43:38.55,00:43:41.61
And all my rabble-rousing[br]is not doing that much above.

00:43:41.69,00:43:43.62
So I'm gonna need[br]some help down here.

00:43:43.69,00:43:47.42
That's why I'm gonna help you stop those[br]angels from gettin' into that church...

00:43:47.49,00:43:50.09
in exchange for you helping me[br]with my campaign.

00:43:50.16,00:43:52.93
How do you know about that,[br]the angels?

00:43:53.00,00:43:56.13
- Isn't much I don't know about you.[br]- I find that hard to believe.

00:43:56.20,00:44:00.50
When you were five, you let a kid[br]from next door piss on your hand.

00:44:00.57,00:44:03.98
You did that shit?[br]You're nasty.

00:44:04.05,00:44:06.57
I never told anybody about that.

00:44:06.65,00:44:08.34
Neither did he.

00:44:08.42,00:44:11.25
Two years later,[br]that kid died of leukemia.

00:44:11.32,00:44:14.02
His name was Brian Johnson.

00:44:14.09,00:44:16.22
Your exploits,[br]no matter how inane...

00:44:16.29,00:44:18.35
are well documented in Heaven.

00:44:18.43,00:44:20.26
Probably Hell too.

00:44:25.47,00:44:27.10
Where are you going?

00:44:27.17,00:44:29.00
Tell me somethin' about me.

00:44:29.07,00:44:32.06
You masturbate more than anyone[br]on the planet.

00:44:32.14,00:44:35.01
Fuck. Everyone knows that.[br]Tell me something nobody knows.

00:44:35.08,00:44:37.55
When you do it,[br]you're thinking about guys.

00:44:40.88,00:44:43.82
- Dude, not all the time.[br]- Sorry if I scared you.

00:44:46.92,00:44:50.86
Two-thirds of me wants to[br]forget about this and go home.

00:44:50.93,00:44:53.56
Yesterday, I wasn't sure[br]God even existed.

00:44:53.63,00:44:57.12
Now I'm up to my ass[br]in Christian mythology.

00:44:57.20,00:45:01.07
Let me let you in[br]on a little inside info.

00:45:01.14,00:45:05.87
God hates it when[br]it's referred to as "mythology."

00:45:06.95,00:45:11.54
Oh, well, then let's ask the "prophets"[br]what we should call it instead.

00:45:14.72,00:45:17.31
Where did those two assholes go?

00:45:34.88,00:45:36.90
What are you doing?

00:45:36.98,00:45:39.00
Proving to this bastard[br]I ain't gay.

00:45:39.08,00:45:41.07
- What?[br]- Long story. Forget it.

00:45:41.15,00:45:43.48
We gotta get movin'.[br]How can we get to Jersey?

00:45:43.55,00:45:45.58
We'll take the train.[br]I'll call for reservations.

00:46:42.41,00:46:45.38
I thought she looked familiar.

00:46:45.45,00:46:47.08
- Who?[br]- Serendipity.

00:47:00.40,00:47:01.49
Morning, shoppers.

00:47:01.57,00:47:03.33
Good morning.

00:47:04.24,00:47:06.67
- Has anyone seen the overnights?[br]- No, sir.

00:47:08.01,00:47:09.60
We creamed 'em.

00:47:12.28,00:47:14.94
Last night was a rerun,[br]which says to me...

00:47:17.48,00:47:19.42
Do I smell onions?

00:47:25.36,00:47:27.23
Excuse me.

00:47:30.63,00:47:33.12
May I ask what you're doing[br]in my boardroom?

00:47:34.07,00:47:37.00
You may proceed, mon ami.

00:47:40.48,00:47:42.64
I'm gonna have to start[br]by apologizing.

00:47:42.71,00:47:45.65
My friend has a bit of a penchant[br]for the dramatic.

00:47:45.71,00:47:47.31
Oh, come on!

00:47:50.62,00:47:52.55
Relax. I'm doing it.

00:47:54.36,00:47:56.85
Mooby, the Golden Calf.

00:47:56.93,00:48:01.33
Created by Nancy Goldruff,[br]a former kindergarten teacher in 1989.

00:48:01.40,00:48:04.16
Bought by the Complex Corporation[br]in 1991.

00:48:04.23,00:48:08.00
Broadcast nationally[br]as the "Mooby Fun-Time Hour."

00:48:08.07,00:48:12.57
Since its inception,[br]has spawned two theatrical films...

00:48:12.64,00:48:16.64
16 records,[br]8 prime-time specials...

00:48:16.71,00:48:21.31
and a library[br]of priced-to-own videocassettes.

00:48:21.39,00:48:25.35
Not to mention[br]bicoastal theme parks...

00:48:25.42,00:48:27.98
dubbed "Mooby World."

00:48:28.06,00:48:30.39
Did I miss anything?

00:48:30.46,00:48:32.23
You forgot Mooby Magazine.

00:48:32.30,00:48:33.73
Damn it!

00:48:33.80,00:48:35.53
Is there a point to this?

00:48:35.60,00:48:39.37
You and your board are idolaters.

00:48:41.41,00:48:44.27
I can't believe you forgot[br]the magazine.

00:48:46.41,00:48:47.97
That's you.

00:48:49.22,00:48:51.41
Do you know much about voodoo?

00:48:52.89,00:48:56.19
That's a fascinating practice.[br]No real doctrine of faith to speak of.

00:48:56.26,00:48:58.99
More an arrangement[br]of superstitions...

00:48:59.06,00:49:01.05
the most well-known of which...

00:49:01.13,00:49:02.65
is the voodoo doll.

00:49:02.73,00:49:04.20
You see...

00:49:12.54,00:49:15.57
a mockup of an individual[br]is subjected...

00:49:15.64,00:49:17.77
to various pokes and prods.

00:49:17.85,00:49:21.98
The desired result is that[br]the individual will feel those effects.

00:49:22.05,00:49:23.61
Call security, now!

00:49:28.16,00:49:31.02
All lines are currently down.

00:49:31.09,00:49:33.49
- I'm gonna have to apologize...[br]- Would you knock it off?

00:49:33.56,00:49:36.03
You're doing it again.[br]Stop. What did we talk about?

00:49:37.17,00:49:40.53
You are responsible[br]for raising an icon...

00:49:40.60,00:49:42.57
which draws worship[br]from the Lord.

00:49:42.64,00:49:44.94
You have broken[br]the First Commandment.

00:49:45.01,00:49:48.00
More than that,[br]I'm afraid not a one of you...

00:49:48.08,00:49:50.84
passes for a decent human being.

00:49:50.91,00:49:55.35
Your continued existence[br]is a mockery of morality.

00:49:55.42,00:49:57.35
Like you, Mr. Burton.

00:49:57.42,00:50:00.91
Last year, you cheated on your wife[br]of 17 years 8 times.

00:50:00.99,00:50:03.22
You even had sex[br]with her best friend...

00:50:03.29,00:50:07.63
while you were supposed to be home[br]watching the kids.

00:50:07.70,00:50:11.19
In the bed that you[br]and your wife share, no less.

00:50:11.27,00:50:12.40
Mr. Newman.

00:50:12.47,00:50:15.20
You got your girlfriend drunk[br]at last year's Christmas party...

00:50:15.27,00:50:17.57
and then paid a kid[br]from the mail room...

00:50:17.64,00:50:20.17
to have sex with her[br]while she was passed out...

00:50:20.25,00:50:22.87
just so you could break up[br]with her guilt-free...

00:50:22.95,00:50:25.32
when she sobbingly confessed[br]in the morning.

00:50:26.75,00:50:29.59
She killed herself[br]three months later.

00:50:29.66,00:50:32.59
Mr. Brace disowned his gay son.

00:50:32.66,00:50:34.59
Very compassionate.

00:50:34.66,00:50:37.76
Mr. Ray put his mother[br]in a third-rate nursing home...

00:50:37.83,00:50:41.17
and used the profits[br]from the sale of her home...

00:50:41.24,00:50:45.07
to buy an Oriental rug for himself.

00:50:45.14,00:50:46.83
Heavens.

00:50:46.91,00:50:49.67
Mr. Barker flew to Thailand[br]on the company account...

00:50:49.74,00:50:53.41
to have sex[br]with an eleven-year-old boy.

00:50:53.48,00:50:56.54
Mr. Holtzman okayed the production[br]of Mooby Dolls...

00:50:56.62,00:50:59.38
from materials he knew[br]to be toxic and unsafe...

00:50:59.45,00:51:01.85
because it was... survey says...

00:51:03.33,00:51:05.19
less costly.

00:51:05.26,00:51:08.25
You, on the other hand...

00:51:08.33,00:51:10.60
are an innocent.

00:51:10.67,00:51:12.53
You lead a good life.

00:51:12.60,00:51:13.69
Good for you.

00:51:14.60,00:51:17.66
But you, Mr. Whitland...

00:51:17.74,00:51:19.71
you have more skeletons[br]in your closet...

00:51:19.78,00:51:21.71
than this assembled party.

00:51:21.78,00:51:24.47
I cannot even mention them aloud.

00:51:28.32,00:51:31.95
You're his father,[br]you sick fuck!

00:51:35.03,00:51:36.62
- Good.[br]- Not bad, man.

00:51:36.69,00:51:38.63
That's great work.[br]Very good.

00:51:39.90,00:51:41.49
Well...

00:51:42.67,00:51:44.83
alone at last.

00:51:44.90,00:51:47.43
With the exception of Miss Pryce here...

00:51:47.51,00:51:51.31
there isn't a decent human being[br]amongst you.

00:51:51.38,00:51:53.14
Not one.

00:51:53.21,00:51:56.81
Do you know what makes[br]a human being decent?

00:51:56.88,00:51:58.14
Fear.

00:51:58.22,00:52:00.31
And therein lies the problem.

00:52:00.39,00:52:03.32
None of you has anything[br]left to fear anymore.

00:52:03.39,00:52:06.85
You rest comfortably in seats[br]of inscrutable power...

00:52:06.93,00:52:10.16
hiding behind your false idol,[br]far from judgment...

00:52:10.23,00:52:13.50
lives shrouded in secrecy,[br]even from one another.

00:52:15.24,00:52:17.17
But not from God.

00:52:22.18,00:52:24.27
Forgot my little voodoo doll.

00:52:26.38,00:52:30.01
Man, it really looks[br]just like you, doesn't it?

00:52:30.08,00:52:33.85
Look, if I believed enough in this...

00:52:33.92,00:52:35.51
I wonder...

00:52:52.27,00:52:55.04
Come on.[br]I don't believe in voodoo.

00:52:59.75,00:53:01.34
Voodoo.

00:53:08.73,00:53:11.32
But I do believe in this.

00:53:11.40,00:53:13.80
Don't run! Don't run!

00:53:13.86,00:53:16.66
Fakes! Fakes![br]All of you, fakes!

00:53:19.14,00:53:21.40
"But I do believe in this."

00:53:21.47,00:53:22.91
What does that mean?

00:53:22.97,00:53:24.44
And one to grow on.

00:53:30.52,00:53:31.61
Gum?

00:53:32.95,00:53:35.55
Go on. It's okay.

00:53:35.62,00:53:37.68
You've done nothing wrong.

00:53:37.76,00:53:40.85
These guys were fakes.

00:53:40.93,00:53:43.26
You're a pure soul.

00:53:44.86,00:53:47.46
But you didn't say "God bless you"[br]when I sneezed.

00:53:48.53,00:53:49.97
Loki!

00:53:52.04,00:53:53.47
You're getting off light.

00:53:53.54,00:53:55.57
- Loki![br]- I know. I'm comin'.

00:53:59.58,00:54:01.01
You're so lucky.

00:54:05.39,00:54:08.25
I forgot you were down here.[br]How long now?

00:54:08.32,00:54:09.76
Three years this August.

00:54:09.82,00:54:13.49
Let me guess... the 14th Apostle, left[br]out of the Bible because she's a woman?

00:54:13.56,00:54:14.79
This girl's no woman.

00:54:14.86,00:54:17.89
Oh. Those weren't tits[br]I saw Jay cozying up to?

00:54:17.97,00:54:19.69
What, these?

00:54:19.77,00:54:23.97
You should know better than anyone here[br]that tits don't make a woman.

00:54:24.04,00:54:26.44
Hell, the tubby, coat-wearing[br]motherfucker's got tits.

00:54:26.51,00:54:30.04
What traditionally defines a woman[br]falls between two things...

00:54:30.11,00:54:31.81
her legs.

00:54:31.88,00:54:34.31
But as you can see...

00:54:34.38,00:54:36.15
I lack definition.

00:54:36.22,00:54:39.95
Hey, they're gettin' a free show![br]Let me see that shit!

00:54:40.02,00:54:43.05
Oh, God,[br]another angel like Metatron.

00:54:43.13,00:54:45.79
How do you...[br]How does she know Metatron?

00:54:45.86,00:54:47.85
This is the last scion.

00:54:48.77,00:54:51.53
You're kidding.

00:54:51.60,00:54:53.26
Wow.

00:54:53.34,00:54:54.36
I'm confused.

00:54:54.44,00:54:58.53
Bethany, Serendipity here[br]isn't technically an angel.

00:54:58.61,00:55:02.31
Nor is she, by any means,[br]a human being like I was and you are.

00:55:02.38,00:55:06.15
- I used to be an abstract.[br]- Now I'm really confused.

00:55:06.22,00:55:07.78
I'm a muse, stupid.

00:55:08.85,00:55:11.45
I can't take much more of this.

00:55:11.52,00:55:13.22
So you, what, inspire people?

00:55:13.29,00:55:16.02
What just went down[br]with your friends over there...

00:55:16.09,00:55:19.00
It doesn't really take a muse to inspire[br]horny retards to empty their wallets.

00:55:19.06,00:55:21.06
I used to specialize[br]in entertainment.

00:55:21.13,00:55:26.63
For example, I'm responsible for 19 of[br]the 20 top-grossing films of all time.

00:55:26.71,00:55:29.30
- Nineteen?[br]- Yeah.

00:55:29.38,00:55:32.31
The one about the kid[br]by himself in his house...

00:55:32.38,00:55:35.40
burglars trying to come in[br]and he fights them off...

00:55:35.48,00:55:37.75
I had nothing to do[br]with that one.

00:55:37.82,00:55:42.15
Somebody sold their soul to Satan to get[br]the grosses up on that piece of shit.

00:56:00.48,00:56:02.88
What are you doing stripping?

00:56:02.94,00:56:04.38
Remember why I left?

00:56:04.45,00:56:07.88
Because you were tired of getting[br]none of the credit for your ideas.

00:56:07.95,00:56:11.11
So I opted to quit being a muse[br]and write for myself.

00:56:11.19,00:56:15.09
I gave my two weeks notice,[br]got a body, 50 bucks...

00:56:15.16,00:56:18.22
and got sent out into the world[br]to make my fortune.

00:56:18.29,00:56:19.85
So what happened?

00:56:21.10,00:56:22.69
Writer's block.

00:56:22.77,00:56:25.63
Can you believe it?[br]Me, a muse, for God's sake.

00:56:25.70,00:56:29.73
I can inspire anyone I meet and give out[br]a zillion and nine ideas a second...

00:56:29.81,00:56:31.74
but I can't keep any for myself.

00:56:33.34,00:56:35.74
Her quirky sense of humor.

00:56:35.81,00:56:38.08
- Whose?[br]- God's.

00:56:38.15,00:56:41.08
- You're saying God's a woman?[br]- Was there ever a doubt in your mind?

00:56:41.15,00:56:42.95
He's always referred to as "Him."

00:56:43.02,00:56:44.85
That's not how I wrote it.

00:56:44.92,00:56:46.86
But one of the drawbacks[br]to being intangible...

00:56:46.92,00:56:49.65
is that you have no say[br]in the editorial process.

00:56:49.73,00:56:52.79
The people that held the pens[br]added their own perspective...

00:56:52.86,00:56:55.39
and all the penholders were men.

00:56:55.47,00:56:59.40
So She became a He.[br]Doesn't stop with God either.

00:56:59.47,00:57:01.53
The whole book's gender-biased.

00:57:01.61,00:57:03.84
A woman's responsible[br]for original sin.

00:57:03.91,00:57:06.10
A woman cuts Samson coif of power.

00:57:06.18,00:57:09.58
A woman asks for the head[br]of John the Baptist.

00:57:09.65,00:57:11.12
Read that book again.

00:57:11.18,00:57:14.31
Women are painted as bigger antagonists[br]than the Egyptians and Romans combined.

00:57:14.39,00:57:15.65
It stinks.

00:57:22.03,00:57:23.79
Why is the last scion here?

00:57:23.86,00:57:26.83
Bartleby and Loki.[br]They found a way back.

00:57:26.90,00:57:30.10
- Not the plenary indulgence loophole.[br]- You know about that?

00:57:30.17,00:57:33.11
I always knew that thing[br]was a bad idea.

00:57:33.17,00:57:35.11
Leave it to the Catholics[br]to destroy existence.

00:57:35.18,00:57:37.70
You have issues with Catholicism,[br]I take it?

00:57:37.78,00:57:41.34
I have issues with anyone who treats God[br]like a burden instead of a blessing...

00:57:41.42,00:57:42.78
like some Catholics.

00:57:42.85,00:57:45.82
You people don't celebrate your faith,[br]you mourn it.

00:57:45.89,00:57:50.12
- If we're wrong, what religion is right?[br]- It's not about who's right or wrong.

00:57:50.19,00:57:52.13
No denomination's nailed it yet...

00:57:52.19,00:57:54.82
because they're all[br]too self-righteous to realize...

00:57:54.90,00:57:59.83
that it doesn't matter what you have[br]faith in, just that you have faith.

00:57:59.90,00:58:04.34
Your hearts are in the right place,[br]but your brains gotta wake up.

00:58:06.74,00:58:09.30
They made me and Silent Bob[br]part of the gang.

00:58:15.22,00:58:17.15
Who fuckin' farted?

00:58:18.66,00:58:21.89
Not born.[br]Shit into existence.

00:58:25.33,00:58:28.16
Sweet Christ,[br]somebody wants you bad!

00:58:28.23,00:58:30.72
- What is that thing?[br]- An excremental.

00:58:30.80,00:58:33.07
- The Golgothan.[br]- A what?

00:58:33.14,00:58:34.54
A shit demon!

00:58:34.61,00:58:38.27
No man of woman born!

00:58:39.04,00:58:42.21
- Friend of yours?[br]- Is this smelly fuck with us?

00:58:42.28,00:58:43.91
It came for Bethany!

00:58:43.98,00:58:46.92
Smoke that motherfucker[br]like it ain't no thang!

00:58:46.99,00:58:49.45
I knew I's gonna[br]whack somebody today!

00:58:49.52,00:58:51.46
Get your fuckin' hand back.

00:58:51.52,00:58:52.75
Represent!

00:58:54.13,00:58:56.56
Go! Go! Go!

00:59:17.89,00:59:20.32
Looks like we're in charge[br]of the gang now.

00:59:21.69,00:59:23.21
Over the bar!

00:59:32.70,00:59:36.14
- Where did that thing come from?[br]- Ever heard of Golgotha?

00:59:36.20,00:59:38.23
The hill where Christ[br]was crucified.

00:59:38.31,00:59:41.07
It wasn't just Christ.[br]The Romans crucified everyone there.

00:59:41.14,00:59:44.67
Christ excluded, they were criminals...[br]killers, brigands, thieves, rapists.

00:59:44.75,00:59:47.88
Whenever the crucified expired,[br]their bodies lost muscle control...

00:59:47.95,00:59:50.48
spilling bowel and bladder[br]in the process...

00:59:50.55,00:59:53.42
the result of which[br]is that walking pile of crap...

00:59:53.49,00:59:56.58
the Golgothan shit demon,[br]Hell's chief assassin.

00:59:56.66,00:59:58.46
It's here for you, girlie.

01:00:03.03,01:00:05.26
- Bob, get down![br]- Matches! Matches!

01:00:38.14,01:00:40.40
- Hey, man.[br]- How?

01:00:42.51,01:00:44.17
"Knocks strong odors out."

01:00:44.24,01:00:47.18
- Way to go, biggie.[br]- Why would you ever carry this?

01:00:49.28,01:00:50.98
What?

01:00:51.05,01:00:52.99
Whoever sent this might send more.

01:00:53.05,01:00:57.01
I suggest you take the princess[br]and get as far away as possible.

01:00:57.09,01:00:59.65
I'll try to get something[br]out of poopy boy here.

01:00:59.73,01:01:02.49
If he tells me something,[br]I'll let you know.

01:01:03.80,01:01:06.10
Hello. We'd like two tickets[br]to New Jersey, please.

01:01:06.17,01:01:07.86
Jersey's sold out, sir.

01:01:07.94,01:01:10.53
- What?[br]- There's one at the same time tomorrow.

01:01:10.61,01:01:14.54
Don't underestimate the staggering[br]drawing power of the Garden State.

01:01:14.61,01:01:16.94
Show up two hours in advance.

01:01:19.21,01:01:20.65
Nice.

01:01:20.72,01:01:23.65
Your hard-on for smiting[br]has prevented us from negotiating...

01:01:23.72,01:01:27.85
what ought to be the relatively simple[br]matter of catching or staying on a bus.

01:01:27.92,01:01:29.59
Bus, schmuss.

01:01:29.66,01:01:34.26
Why should we fall victim to gravity[br]when we can just as easily rise above?

01:01:34.33,01:01:36.76
- You mean fly?[br]- We got wings, right?

01:01:36.83,01:01:38.43
Fuck, let's use 'em!

01:01:38.50,01:01:40.94
I wouldn't suggest that.

01:01:42.34,01:01:44.17
You see, kids...

01:01:44.24,01:01:47.68
you wouldn't want to look like[br]a couple of fairies, now, would you?

01:01:53.32,01:01:55.41
How'd you get out of Hell?

01:01:55.49,01:01:57.75
I told them I was coming up[br]on a routine possession.

01:01:57.82,01:02:01.05
I don't have much time. If they figure[br]out my ruse, they'll come after me.

01:02:01.13,01:02:04.86
- What's with bringing us in here?[br]- You two are inches from getting caught.

01:02:04.93,01:02:08.42
Going around killing people,[br]about to uncase your wings.

01:02:08.50,01:02:10.43
Don't you know what's going on?

01:02:10.50,01:02:12.44
Well, we're going home.

01:02:12.51,01:02:16.97
Really. Are you so clueless as to think[br]you can just waltz back into Heaven?

01:02:17.04,01:02:19.60
- Why not?[br]- Everybody is looking for you.

01:02:19.68,01:02:22.61
Both sides.[br]Above and below.

01:02:22.68,01:02:24.98
Orders are to terminate you[br]on sight.

01:02:25.05,01:02:26.45
- Really?[br]- Why?

01:02:26.52,01:02:28.68
Because you're pissing people off,[br]that's why.

01:02:30.02,01:02:32.69
Word is that God's pissed off[br]at your presumption...

01:02:32.76,01:02:36.02
and I know Lucifer's pissed because[br]you assholes might make him look bad...

01:02:36.10,01:02:38.03
by succeeding[br]where he's failed so many times.

01:02:38.10,01:02:41.19
- So they're just gonna kill us?[br]- They're gonna try.

01:02:41.27,01:02:44.20
That's why you have to travel[br]incognito.

01:02:44.27,01:02:47.33
Tone down your behavior.[br]Stay off their respective radars.

01:02:47.41,01:02:49.34
Quit killing people.[br]That's high profile.

01:02:49.41,01:02:52.31
- Oh, lighten up.[br]- I can't believe they wanna kill us.

01:02:52.38,01:02:54.31
Oh, believe it, boys.

01:02:55.55,01:02:57.82
They've even got the last scion[br]looking for you.

01:02:57.89,01:02:59.65
- Really?[br]- You're kidding.

01:02:59.72,01:03:02.71
This is huge. Your reentry[br]is a thorn in a lot of sides.

01:03:02.79,01:03:04.73
They'll stop at nothing[br]to prevent it.

01:03:04.79,01:03:08.06
In the meantime, I suggest you find[br]an alternate mode of transportation.

01:03:08.13,01:03:10.19
If anything else comes up,[br]I'll contact you.

01:03:10.27,01:03:13.46
Thank you, Azrael.[br]You're a true friend.

01:03:13.54,01:03:16.47
I have to get back to the pit[br]before they get suspicious.

01:03:16.54,01:03:20.20
And remember, incognito.

01:03:24.61,01:03:27.24
How you coping, kid?

01:03:27.32,01:03:29.01
It's weird.

01:03:29.09,01:03:31.68
Just when I think[br]I have a handle on things...

01:03:31.76,01:03:35.02
something wholly unbelievable[br]presents itself.

01:03:35.09,01:03:37.65
Sometimes I wish[br]I'd just stayed home.

01:03:37.73,01:03:40.39
You sound like the Man.

01:03:40.46,01:03:41.86
What's he like?

01:03:41.93,01:03:44.49
He likes to listen to people talk.

01:03:44.57,01:03:48.01
Christ loved to sit around the fire,[br]listen to me and the other guys.

01:03:48.07,01:03:50.44
Whenever we were going on[br]about unimportant shit...

01:03:50.51,01:03:52.70
he always had a smile[br]on his face.

01:03:52.78,01:03:54.84
His only real beef with mankind...

01:03:54.91,01:03:58.18
is the shit that gets carried out[br]in His name.

01:03:58.25,01:04:01.65
Wars, bigotry, televangelism.

01:04:01.72,01:04:05.38
The big one, though,[br]is the factioning of all the religions.

01:04:05.46,01:04:07.39
He said mankind[br]got it all wrong...

01:04:07.46,01:04:10.95
by taking a good idea[br]and building a belief structure on it.

01:04:11.03,01:04:13.69
You're saying having beliefs[br]is a bad thing?

01:04:13.77,01:04:15.86
I just think it's better[br]to have ideas.

01:04:15.94,01:04:19.06
You can change an idea.[br]Changing a belief is trickier.

01:04:19.14,01:04:21.63
People die for it.[br]People kill for it.

01:04:21.71,01:04:24.14
The whole of existence[br]is in jeopardy right now...

01:04:24.21,01:04:29.38
because of the Catholic belief structure[br]regarding this plenary indulgence shit.

01:04:29.45,01:04:31.72
Bartleby and Loki,[br]whether they know it or not...

01:04:31.79,01:04:33.72
are exploiting that belief...

01:04:33.79,01:04:35.26
and if they're successful...

01:04:35.32,01:04:39.52
you, me, all of this[br]ends in a heartbeat.

01:04:39.59,01:04:41.59
All over a belief.

01:04:43.83,01:04:47.79
I haven't seen the moron twins[br]in a while. How about you?

01:04:47.87,01:04:50.96
One time we were at the mall,[br]we tied Tubby to the ceiling...

01:04:51.04,01:04:54.37
and he went flying through the air,[br]fuckin' crashed through the wall.

01:04:54.44,01:04:55.88
It was fucked up.

01:04:55.95,01:04:58.88
You two aren't getting into[br]any trouble, are you?

01:04:58.95,01:05:02.21
We're just about to smoke a fatty[br]with these two suave motherfuckers...

01:05:02.29,01:05:05.52
who just got on at the last stop...[br]Larry and Barry.

01:05:07.12,01:05:09.68
So, Jay tells us[br]you're gonna sleep with him.

01:05:14.40,01:05:16.83
Hit this shit, man.[br]It's good stuff.

01:05:18.20,01:05:19.64
Oh, fuck.

01:05:23.21,01:05:25.64
That's some bad shit, dude.

01:05:25.71,01:05:27.64
You hit that?

01:05:30.05,01:05:31.98
Yeah, you're bad, dude.

01:05:35.19,01:05:36.65
Bad shit.

01:05:37.66,01:05:40.15
Why are you[br]heading to New Jersey?

01:05:40.23,01:05:43.66
It's just this thing I have to do.

01:05:43.73,01:05:45.22
We're going home.

01:05:45.30,01:05:48.06
Oh.[br]Do you two live together?

01:05:48.13,01:05:50.00
Unfortunately, yes.

01:05:52.64,01:05:55.40
So, how long have you two[br]been together?

01:05:56.68,01:05:58.51
A while.

01:05:58.58,01:06:02.31
He can be pretty flaky sometimes,[br]but we have a lot in common.

01:06:02.38,01:06:03.98
How'd you meet?

01:06:04.05,01:06:05.64
We were stationed together.

01:06:05.72,01:06:08.09
See, that's beautiful.

01:06:08.16,01:06:12.02
Everybody's always up in arms[br]about this "out in the military" issue.

01:06:13.13,01:06:14.22
Pardon?

01:06:14.30,01:06:18.60
You know, there's all the macho bullshit[br]about it being "this man's army."

01:06:18.67,01:06:20.93
You two meet there, hook up...

01:06:21.90,01:06:25.07
You think we're lovers?[br]No, no. We're not gay.

01:06:25.14,01:06:27.57
Oh, God.[br]I'm sorry.

01:06:27.64,01:06:30.77
- I just assumed.[br]- Do I come off as gay?

01:06:33.58,01:06:36.78
My ex-husband sort of screwed up[br]my relationship awareness barometer.

01:06:36.85,01:06:39.41
- You're divorced.[br]- That's a nice way of putting it.

01:06:39.49,01:06:41.08
I call it being dumped.

01:06:41.16,01:06:43.15
I was...

01:06:43.23,01:06:44.89
dumped once.

01:06:44.96,01:06:47.90
Don't you just constantly[br]question your value?

01:06:47.97,01:06:50.59
Like, why was I so easy[br]to cast aside?

01:06:50.67,01:06:54.26
And you wonder if the other party[br]is gonna come to their senses...

01:06:54.34,01:06:55.77
and call you back.

01:06:55.84,01:06:59.30
They always tell you[br]it'll hurt less with time.

01:06:59.38,01:07:01.47
When actually...

01:07:01.55,01:07:03.24
it hurts more.

01:07:06.65,01:07:08.88
You know what we need?

01:07:08.95,01:07:10.78
What do we need?

01:07:10.86,01:07:12.38
We need drinks.

01:07:14.03,01:07:15.93
We need a lot of drinks.

01:07:17.53,01:07:19.46
Garçon.

01:07:25.87,01:07:27.90
You still go to church?

01:07:27.97,01:07:30.14
Every Sunday.

01:07:30.21,01:07:32.61
Does it do anything for you?

01:07:32.68,01:07:35.84
It gives me time to balance[br]my checkbook every week.

01:07:35.92,01:07:39.98
That's what I'm saying. People don't[br]go to church to feel spiritual anymore.

01:07:40.05,01:07:42.32
They go to church and feel bored...

01:07:42.39,01:07:45.79
but they keep going every week[br]just out of habit.

01:07:45.86,01:07:48.16
I am so buzzed.

01:07:49.76,01:07:52.70
When do you think[br]you lost your faith?

01:07:52.77,01:07:55.00
I remember the exact moment.

01:07:57.64,01:08:01.37
I was on the phone with my mother...

01:08:01.44,01:08:05.40
and she was trying to counsel me[br]through this...

01:08:06.55,01:08:07.98
this thing.

01:08:10.09,01:08:14.52
And when nothing she was saying[br]was making me feel any better...

01:08:14.59,01:08:16.53
she said...

01:08:16.59,01:08:18.49
"Bethany...

01:08:18.56,01:08:20.50
God has a plan."

01:08:23.90,01:08:27.60
I was... I was so angry with her.

01:08:29.71,01:08:31.30
I was like...

01:08:31.38,01:08:33.31
"What about my plans?"

01:08:33.38,01:08:35.24
- You know?[br]- Mm-hmm.

01:08:35.31,01:08:38.34
I had planned[br]to have a family...

01:08:38.42,01:08:40.08
with my husband.

01:08:40.15,01:08:43.09
Wasn't that plan[br]good enough for God?

01:08:46.99,01:08:48.93
Apparently not.

01:08:52.23,01:08:56.22
How about you?[br]How'd you lose your faith?

01:08:57.40,01:08:59.63
A long time ago.

01:08:59.70,01:09:03.20
One day God just stopped listening.

01:09:03.28,01:09:07.84
I kept talking, but I got the distinct[br]impression He wasn't listening anymore.

01:09:07.91,01:09:11.41
How did you know She was listening[br]in the first place?

01:09:14.25,01:09:16.19
Well, I guess I don't.

01:09:16.26,01:09:18.49
I hate thoughts like that.

01:09:19.63,01:09:22.69
But, you know,[br]they come to you with age.

01:09:22.76,01:09:27.13
'Cause when you're a kid you never[br]question the whole faith thing.

01:09:28.67,01:09:31.43
God's in Heaven, and He's...

01:09:31.51,01:09:34.94
She's always got her eye on you.

01:09:39.45,01:09:42.38
I'd give anything[br]to feel that way again.

01:09:47.49,01:09:50.72
Guess that's why[br]I got talked into this pilgrimage.

01:09:58.90,01:10:01.13
Where is this pilgrimage to?

01:10:01.20,01:10:04.40
- You wouldn't believe me if I told you.[br]- Try me.

01:10:04.47,01:10:06.81
All right, but I warned you.

01:10:06.88,01:10:08.57
Okay.

01:10:08.65,01:10:12.24
I'm going to this church[br]in New Jersey.

01:10:12.32,01:10:14.11
Really.

01:10:14.18,01:10:18.62
Kerwood Mandel to car three.[br]Kerwood Mandel to car three.

01:10:18.69,01:10:22.15
See, I'm supposed to stop[br]a couple of angels...

01:10:22.23,01:10:24.16
from going into the church.

01:10:26.06,01:10:27.93
They're trying...

01:10:28.00,01:10:29.43
Shit.

01:10:31.24,01:10:33.67
They're trying[br]to get back into Heaven.

01:10:37.04,01:10:39.64
See, they got tossed[br]out of Heaven...

01:10:39.71,01:10:41.18
years ago, right?

01:10:42.25,01:10:44.44
And if they get back in...

01:10:44.52,01:10:46.38
it proves God wrong...

01:10:46.45,01:10:49.62
and since God is infallible...

01:10:49.69,01:10:51.45
to prove Her wrong...

01:10:51.52,01:10:54.79
would, you know, unmake existence.

01:10:56.56,01:10:58.69
May I have your attention, please.

01:10:58.77,01:11:03.03
The dining car will be closing[br]in five minutes. Thank you.

01:11:03.10,01:11:05.73
I feel so stupid...

01:11:05.81,01:11:07.74
just saying it.

01:11:09.21,01:11:11.54
The thing I don't get is...

01:11:11.61,01:11:14.31
how am I supposed to stop[br]an angel?

01:11:14.38,01:11:15.81
Two, even!

01:11:20.96,01:11:24.32
I guess I'm supposed to[br]talk them out of it or something.

01:11:24.39,01:11:26.52
Maybe you're supposed to kill them.

01:11:26.59,01:11:29.79
Oh, yeah, right.[br]Kill them.

01:11:31.13,01:11:35.63
I mean, even if that were the case,[br]which it's not...

01:11:36.87,01:11:39.90
how do you kill an angel, Barry?

01:11:40.68,01:11:42.70
Oh...

01:11:42.78,01:11:44.68
I don't suppose[br]it's much different from...

01:11:45.75,01:11:47.18
killing a human.

01:11:48.62,01:11:51.21
Where is everybody?[br]I wake up and...

01:11:53.16,01:11:55.09
- The apostle.[br]- Holy shit!

01:11:55.16,01:11:58.18
Rufus, I want you to meet[br]my new friend Barry.

01:12:01.53,01:12:03.52
Don't be such a show-off, Barry.

01:12:03.60,01:12:06.37
Take it easy, Bartleby.[br]Just let her go.

01:12:06.44,01:12:08.70
- We can talk about this.[br]- Bartleby?

01:12:08.77,01:12:12.37
After all this time, it comes down[br]to slaughter by a meat puppet?

01:12:12.44,01:12:15.34
Get your fucking hands off me,[br]you dickless son of a bitch!

01:12:15.41,01:12:18.32
Save it. Five minutes ago[br]you were aching to top me off.

01:12:18.38,01:12:19.32
Loki!

01:12:20.39,01:12:21.65
Holy shit. The apostle.

01:12:21.72,01:12:23.81
I didn't come in you, Pete,[br]I swear.

01:12:23.89,01:12:25.88
What are you doing here?

01:12:25.96,01:12:27.89
This woman has to stop two angels[br]from entering a church.

01:12:27.96,01:12:29.89
- Us?[br]- No, two other fucking angels.

01:12:29.96,01:12:33.63
I'd say there's a pretty good chance.[br]Rufus, we're to be liquidated?

01:12:33.70,01:12:36.50
You haven't thought about[br]the consequences of your reentry.

01:12:36.57,01:12:38.26
Consequences, schmonsequences.

01:12:38.34,01:12:41.27
We're going home,[br]no matter whose pride it may hurt.

01:12:41.34,01:12:43.83
- It's not a matter of pride![br]- Loki, kill the girl.

01:12:43.91,01:12:46.61
What are you, high? I can't kill her[br]if she hasn't done anything.

01:12:46.68,01:12:48.11
Fine.[br]I'll kill her myself.

01:12:48.18,01:12:50.51
I fall asleep[br]and everyone takes off?

01:12:50.58,01:12:53.14
- These guys are fuckin' flat-leavers.[br]- Shut his mouth.

01:13:03.20,01:13:04.79
Oh, shit!

01:13:06.23,01:13:07.70
Jay!

01:13:08.87,01:13:10.10
Biggie!

01:13:10.17,01:13:12.64
The door! The door!

01:13:16.44,01:13:18.71
Can't we talk about this?

01:13:24.19,01:13:27.18
Why don't I just get off[br]at the next stop!

01:14:07.17,01:14:08.60
No ticket.

01:14:11.90,01:14:14.60
- The apostle is here.[br]- I noticed.

01:14:14.67,01:14:18.17
- Then you know who she was, don't you?[br]- The scion, I imagine!

01:14:19.05,01:14:21.07
Maybe we should rethink[br]this whole thing.

01:14:21.15,01:14:24.34
I mean, you heard the guy.[br]He said there are consequences.

01:14:24.42,01:14:28.38
And Azrael tells us we're marked?[br]There's more to this than we thought of.

01:14:28.46,01:14:30.48
I was close.

01:14:30.56,01:14:33.72
You know? I was so close[br]to slitting that bitch's throat.

01:14:33.79,01:14:34.89
Whoa.

01:14:34.96,01:14:38.23
You know how I felt?[br]Righteous.

01:14:38.30,01:14:39.89
Justified.[br]Eager, even.

01:14:39.97,01:14:42.03
You all right?[br]Your eyes are kinda...

01:14:42.10,01:14:44.23
My eyes are open.

01:14:44.31,01:14:46.24
For the first time I get it.

01:14:46.31,01:14:50.11
When that little innocent girl[br]let her mission slip, I had an epiphany.

01:14:50.18,01:14:53.94
See, in the beginning it was[br]just us and Him... angels and God.

01:14:54.02,01:14:55.78
Then He created humans.

01:14:55.85,01:14:58.88
Ours was designed to be[br]a life of servitude and worship...

01:14:58.95,01:15:02.22
and bowing and scraping and adoration.

01:15:02.29,01:15:06.73
He gave them more than He ever gave us.[br]He gave them a choice.

01:15:06.80,01:15:10.10
They choose to acknowledge God[br]or choose to ignore Him.

01:15:10.17,01:15:12.10
All this time[br]we've been down here...

01:15:12.17,01:15:14.76
I've felt the absence[br]of the Divine Presence...

01:15:14.84,01:15:18.14
and it's pained me,[br]as I'm sure it must have pained you.

01:15:18.21,01:15:22.17
And why?[br]Because of the way He made us.

01:15:22.25,01:15:25.58
Had we been given free will we could[br]choose to ignore the pain, like they do.

01:15:25.65,01:15:27.45
But no, we're servants.

01:15:27.52,01:15:29.54
Okay.

01:15:29.62,01:15:33.15
All I'm saying here is that[br]one of us might need a little nap.

01:15:33.22,01:15:37.13
Wake up! These humans have besmirched[br]everything He's bestowed upon them.

01:15:37.20,01:15:39.13
They were given paradise;[br]they threw it away.

01:15:39.20,01:15:41.63
They were given this planet;[br]they destroyed it.

01:15:41.70,01:15:44.26
They were favored best[br]among all His endeavors...

01:15:44.34,01:15:47.67
and some of them[br]don't even believe He exists!

01:15:47.74,01:15:49.83
And in spite of it all...

01:15:49.91,01:15:53.64
He has shown them[br]infinite fucking patience...

01:15:53.71,01:15:55.51
at every turn.

01:15:55.58,01:15:57.11
What about us?

01:15:58.28,01:16:01.22
I asked you once...

01:16:01.29,01:16:04.22
to lay down the sword[br]because I felt sorry for them.

01:16:04.29,01:16:06.12
What was the result?

01:16:06.19,01:16:08.46
Our expulsion from paradise.

01:16:08.53,01:16:11.12
Where was His[br]infinite fucking patience then?

01:16:11.20,01:16:14.03
It's not right![br]It's not fair!

01:16:14.10,01:16:16.04
We've paid our debt!

01:16:17.50,01:16:20.27
Don't you think it's time?

01:16:20.34,01:16:23.21
Don't you think it's time[br]we went home?

01:16:24.91,01:16:29.87
And to do that, I think we may have to[br]dispatch our would-be dispatchers.

01:16:29.95,01:16:32.65
Wait. Wait, wait.[br]Kill them?

01:16:33.76,01:16:36.49
You're talking about the last scion,[br]for Christ's sake.

01:16:36.56,01:16:39.49
And what about Jay and Bob?[br]Those guys were all right.

01:16:39.56,01:16:41.12
Don't.[br]Don't, my friend.

01:16:41.20,01:16:44.83
Don't let your sympathies[br]get the best of you.

01:16:44.90,01:16:46.39
They did me once.

01:16:46.47,01:16:48.37
Scion or not...

01:16:48.44,01:16:49.87
she's just a human...

01:16:49.94,01:16:53.10
and by passing through that arch[br]our sins are forgiven.

01:16:53.18,01:16:55.17
No harm, no foul.

01:16:56.35,01:16:59.28
My God.[br]I've heard a rant like this before.

01:17:00.82,01:17:02.18
What did you say?

01:17:02.25,01:17:05.35
- I've heard a rant like this before.[br]- Don't you do that to me.

01:17:05.42,01:17:08.45
- You sound like the morning star.[br]- You shut your fucking face!

01:17:08.53,01:17:11.62
You sound like Lucifer, man![br]You've fucking lost it!

01:17:11.70,01:17:14.29
You're not talking about[br]going home, Bartleby.

01:17:14.37,01:17:16.93
You're talking about[br]fucking war on God.

01:17:18.34,01:17:19.93
Well, fuck that.

01:17:20.01,01:17:24.37
I have seen what happens to the proud[br]when they take on the Throne.

01:17:25.38,01:17:27.47
I'm going back to Wisconsin.

01:17:28.51,01:17:30.74
We're going home, Loki...

01:17:30.82,01:17:34.88
and no one, not you,[br]not even the Almighty Himself...

01:17:34.95,01:17:36.89
is gonna make that otherwise.

01:17:43.40,01:17:44.83
Shit.

01:17:46.03,01:17:49.66
Why couldn't we stay on the train?[br]You threw those guys off.

01:17:49.74,01:17:51.47
Very basic strategy.

01:17:51.54,01:17:54.97
If your enemies know where you are,[br]then don't be there.

01:17:55.04,01:17:56.17
Why are we enemies?

01:17:56.24,01:17:59.61
Well, I know I'd perceive the person[br]sent to kill me as an enemy.

01:17:59.68,01:18:03.08
What does that mean? Since when[br]am I supposed to kill anybody?

01:18:03.15,01:18:06.81
I'm tired[br]of all this cryptic bullshit.

01:18:06.89,01:18:09.45
I'm physically and psychologically[br]exhausted, Rufus...

01:18:09.52,01:18:12.79
and I'm ready to kick back[br]and welcome the end of existence...

01:18:12.86,01:18:15.26
unless you come clean right now.

01:18:15.33,01:18:17.42
Why me?

01:18:17.50,01:18:20.99
Out of all the people[br]on the goddamn planet, why was I tapped?

01:18:21.07,01:18:24.01
Imagine you're a 12-year-old boy.

01:18:25.24,01:18:29.27
You're told you're God's only son,[br]but more than that, you're God.

01:18:29.35,01:18:32.94
How long do you think it would take to[br]come to grips with something that huge?

01:18:33.02,01:18:35.68
Maybe, say, 18 years?

01:18:35.75,01:18:40.85
In the Bible, Jesus suddenly[br]goes from age 12 to 30. 12 to 30.

01:18:40.92,01:18:43.15
Now, that's some pretty bad[br]storytelling.

01:18:43.23,01:18:46.16
Where are the volumes of text[br]dealing with the missing 18 years?

01:18:46.23,01:18:47.56
I'll tell you where.

01:18:47.63,01:18:52.37
They were offered up as a sacrifice[br]to the god of ecumenical politics.

01:18:52.44,01:18:55.46
You make it sound like[br]there's some church conspiracy...

01:18:55.54,01:18:58.30
to cover up[br]"the truth about Christ."

01:19:00.65,01:19:02.08
Oh, bullshit.

01:19:02.15,01:19:04.14
Any important material[br]about Christ...

01:19:04.22,01:19:06.81
would give people a better understanding[br]of the nature of God.

01:19:06.89,01:19:10.91
- Why would they leave any of it out?[br]- Because it's tied in with His family.

01:19:10.99,01:19:14.02
- His mother and father.[br]- His brothers and sisters.

01:19:14.09,01:19:18.36
Jesus didn't have brothers and sisters.[br]Mary was a virgin.

01:19:18.43,01:19:22.80
Mary gave birth to Christ without having[br]known a man's touch. This is true.

01:19:22.87,01:19:24.80
But she did have a husband.

01:19:24.87,01:19:28.57
Do you really think he would've stayed[br]married to her for all those years...

01:19:28.64,01:19:30.23
if he wasn't gettin' laid?

01:19:30.31,01:19:33.75
The nature of God and the Virgin Birth,[br]those are leaps of faith.

01:19:33.81,01:19:38.08
But to believe a married couple never[br]got down, that's just plain gullibility.

01:19:38.15,01:19:39.28
Meaning?

01:19:39.35,01:19:41.29
The blood that flows[br]through your veins...

01:19:41.36,01:19:44.05
shares a chromosome or two[br]at the genetic level...

01:19:44.12,01:19:45.89
with the one you call Jesus.

01:19:46.96,01:19:48.86
Bethany, you are...

01:19:48.93,01:19:53.96
the great-great-great-great-great-great-[br]great-great-great-great-grandniece...

01:19:54.04,01:19:55.97
of Jesus Christ.

01:19:59.84,01:20:03.87
So, that would make Bethany[br]part black?

01:20:08.58,01:20:10.52
I can't do this anymore.

01:20:15.66,01:20:18.96
Where you gonna go?[br]You know what I'm saying is right.

01:20:19.03,01:20:20.83
- It's bullshit.[br]- Bethany.

01:20:20.90,01:20:22.49
It's bullshit!

01:20:26.17,01:20:28.54
Let her go, man.

01:20:28.61,01:20:30.10
Give her time.

01:20:37.42,01:20:39.44
Why?

01:20:39.52,01:20:42.45
What the fuck do You want from me?

01:20:42.52,01:20:44.92
I fucking hate You!

01:20:45.86,01:20:47.52
I hate You.

01:20:47.59,01:20:49.86
He can't hear you, you know.

01:20:55.60,01:20:57.66
That's why we needed you.

01:20:57.74,01:21:00.03
Why didn't you tell me?

01:21:00.11,01:21:01.27
Would you...

01:21:02.34,01:21:04.64
Could you have believed me?

01:21:05.41,01:21:07.94
It was something[br]you had to come to gradually.

01:21:08.85,01:21:11.15
Only after everything you've seen...

01:21:12.29,01:21:13.38
everything you've heard...

01:21:15.39,01:21:18.48
could you possibly be able[br]to accept the truth.

01:21:18.56,01:21:20.55
I don't want this.

01:21:23.80,01:21:25.86
It's too big.

01:21:25.93,01:21:27.63
That's what Jesus said.

01:21:29.80,01:21:31.74
I had to tell Him.

01:21:34.94,01:21:37.97
You can imagine[br]how that hurt the Father...

01:21:39.05,01:21:41.38
not to be able[br]to tell the Son Himself...

01:21:41.45,01:21:44.44
because one word from His lips would[br]destroy the boy's frail human form.

01:21:44.52,01:21:47.89
So I had to deliver the news[br]to a scared child...

01:21:47.96,01:21:50.19
who wanted nothing more[br]than to play with other children.

01:21:50.26,01:21:54.39
I had to tell this little boy[br]that He was God's only son...

01:21:54.46,01:21:57.40
and it meant a life of persecution[br]and eventual crucifixion...

01:21:57.47,01:22:00.70
at the hands of the very people[br]He'd come to enlighten and redeem.

01:22:02.91,01:22:05.07
He begged me to take it all back.

01:22:06.48,01:22:08.07
As if I could.

01:22:09.78,01:22:12.58
He begged me to[br]"make it all not true."

01:22:12.65,01:22:17.05
I'll let you in on something, Bethany,[br]something I've never told anyone before.

01:22:18.52,01:22:20.46
If I had the power...

01:22:21.93,01:22:23.36
I would have.

01:22:24.10,01:22:25.29
It's unfair.

01:22:25.36,01:22:29.03
It's unfair to ask a child[br]to shoulder that responsibility...

01:22:29.10,01:22:31.40
and to ask you to do the same now.

01:22:31.47,01:22:33.20
I sympathize. I do.

01:22:33.27,01:22:35.71
I wish I could take it all back.

01:22:38.18,01:22:39.77
But I can't.

01:22:42.65,01:22:44.08
This...

01:22:45.32,01:22:47.41
is who you are.

01:22:49.32,01:22:51.92
Everything I am has been a lie?

01:22:55.96,01:23:00.56
Knowing what you now know[br]doesn't mean you're not who you were.

01:23:00.63,01:23:01.76
You are...

01:23:01.84,01:23:03.43
Bethany Sloane.

01:23:03.50,01:23:06.44
No one can take that away from you,[br]not even God.

01:23:08.31,01:23:13.04
All this means is[br]a redefinition of that identity.

01:23:13.11,01:23:16.74
The incorporation of this new data[br]into who you are.

01:23:16.82,01:23:19.01
Be who you've always been.

01:23:20.09,01:23:21.25
Just...

01:23:22.19,01:23:23.82
be this as well...

01:23:25.56,01:23:28.09
from time to time.

01:23:31.67,01:23:34.60
Guess this means[br]no more cheating on my taxes.

01:23:34.67,01:23:36.94
To say the least.

01:23:45.08,01:23:47.64
Do you mind if we adjourn[br]to somewhere...

01:23:47.72,01:23:50.35
a tad more habitable...

01:23:50.42,01:23:52.01
and a bit warmer?

01:24:06.87,01:24:09.57
Fuck, I think this shit[br]just kicked in.

01:24:09.64,01:24:12.51
Weren't we just in the woods?[br]What are we doing here now?

01:24:12.58,01:24:14.57
Going out in style.

01:24:14.65,01:24:17.24
- The voice.[br]- The apostle.

01:24:17.32,01:24:19.15
Now, who's this motherfucker?

01:24:19.22,01:24:21.41
The voice of God.[br]Show some respect.

01:24:21.49,01:24:23.92
Oh, the voice of God.[br]Where's the rest of Him?

01:24:23.99,01:24:26.25
Funny you should mention that.[br]We're not sure.

01:24:26.33,01:24:29.09
- What?[br]- Didn't it ever occur to you...

01:24:29.16,01:24:33.19
that this Bartleby-Loki situation was[br]well within the sphere of His control?

01:24:33.27,01:24:35.03
Yes, but then why was she tapped?

01:24:35.10,01:24:39.10
You know those constitutionals[br]that He likes to take?

01:24:39.17,01:24:40.43
"Constitutionals"?

01:24:40.51,01:24:43.00
I think we're beyond euphemisms[br]at this point.

01:24:43.08,01:24:45.01
God's a skeeball fanatic.

01:24:46.28,01:24:49.34
The Lord has quite a fancy for the game.[br]He's been playing it for years.

01:24:49.42,01:24:51.44
He assumes a human form once a month[br]and indulges.

01:24:51.52,01:24:55.05
Doesn't tell anyone where He's playing.[br]He just goes away for a couple of hours.

01:24:55.12,01:24:58.75
And He always gives His free points away[br]to neighborhood children.

01:24:58.83,01:25:00.26
Isn't that sweet?

01:25:00.33,01:25:03.92
But She hasn't come back[br]from one of these day trips?

01:25:04.00,01:25:06.40
No, "She" hasn't...

01:25:06.47,01:25:09.30
and we've been unable to locate "Her."

01:25:09.37,01:25:12.70
He could've been killed.[br]Human form does have that drawback.

01:25:12.78,01:25:16.64
No, there's a different sort[br]of foul play afoot, children.

01:25:17.78,01:25:21.27
Whomever has set the renegade angels[br]on their path...

01:25:21.35,01:25:23.79
and is keeping them[br]quite well hidden...

01:25:23.85,01:25:26.85
is also responsible[br]for the Lord's whereabouts.

01:25:26.92,01:25:29.19
Were He to be killed in human form...

01:25:29.26,01:25:31.92
He'd have returned[br]immediately to Heaven.

01:25:32.00,01:25:33.99
Someone knew enough...

01:25:34.06,01:25:36.19
to keep Him biologically alive...

01:25:36.27,01:25:39.24
but incapacitate Him[br]in another fashion.

01:25:39.30,01:25:42.07
And as omnipotent as we are above...

01:25:42.14,01:25:45.60
I have to admit that we're[br]more or less lost without His presence.

01:25:45.68,01:25:47.61
We've looked everywhere for Him.

01:25:47.68,01:25:52.55
I tapped her because I thought we'd be[br]able to smoke out whoever's behind this.

01:25:52.62,01:25:55.92
But whoever he is has been clever enough[br]to send some lackeys after you...

01:25:55.99,01:25:58.08
as opposed to showing up[br]themselves.

01:25:58.16,01:25:59.92
Could it be Lucifer?

01:25:59.99,01:26:01.39
Not Lucifer.

01:26:01.46,01:26:04.99
If he was, he'd have made[br]his move by now to conquer Heaven.

01:26:05.06,01:26:08.00
And I know he's not responsible[br]for Bartleby and Loki...

01:26:08.07,01:26:11.30
because he's had just as much to lose[br]by their return as anybody else.

01:26:11.37,01:26:12.84
What do we do now?

01:26:12.91,01:26:15.77
I say we get drunk,[br]'cause I'm all out of ideas.

01:26:15.84,01:26:18.81
Why don't we just ask this guy[br]to close the church?

01:26:18.88,01:26:20.71
I beg your pardon?

01:26:20.78,01:26:22.71
The guy in charge[br]of the church thing.

01:26:25.55,01:26:27.45
Cardinal Glick?

01:26:27.52,01:26:29.68
Maybe we can ask him[br]to shut down the church.

01:26:29.76,01:26:33.12
If it's closed that day, those guys[br]can't get blessed or whatever, right?

01:26:33.19,01:26:34.49
Good Lord.

01:26:34.56,01:26:36.62
The little stoner's got a point.

01:26:36.70,01:26:41.29
Maybe we could talk this guy Glick into[br]cancelling the rededication ceremony.

01:26:41.37,01:26:43.39
"We"?

01:26:43.47,01:26:46.57
Are you saying you're back in,[br]Ms. I-Don't-Think-I-Can-Do-This-Anymore?

01:26:50.88,01:26:54.21
I wouldn't want to let the family down,[br]now would I?

01:26:57.09,01:26:58.02
Well...

01:26:59.26,01:27:03.09
the prophets finally[br]live up to their titles.

01:27:03.16,01:27:06.32
Mass attendance is at[br]an all-time low in this country...

01:27:06.40,01:27:10.89
but if we can let 'em know the[br]Catholic Church has a little panache...

01:27:10.97,01:27:14.03
we can win 'em back,[br]even get some new ones.

01:27:14.10,01:27:15.70
Excuse me.

01:27:17.74,01:27:19.37
Fill them pews, people.

01:27:19.44,01:27:22.38
That's the key.[br]Grab the little ones as well.

01:27:22.45,01:27:24.94
Hook 'em while they're young.

01:27:25.02,01:27:29.18
- Kinda like the tobacco industry.[br]- Christ, if only we had their numbers.

01:27:29.25,01:27:32.38
We really appreciate you seeing us[br]this late in the day, Your Eminence.

01:27:32.46,01:27:36.05
My friends and I have been traveling[br]all night in hope of talking to you...

01:27:36.13,01:27:38.62
about the St. Michael's[br]rededication ceremony.

01:27:38.70,01:27:41.19
You looking to help out in some way?

01:27:41.27,01:27:44.06
We'd like you to cancel the ceremony.

01:27:45.14,01:27:46.76
I beg your pardon.

01:27:46.84,01:27:50.87
There's gonna be a world of trouble if[br]tomorrow's ceremony goes on as planned.

01:27:51.94,01:27:54.78
Are you pro-choice?

01:27:54.85,01:27:56.44
The trouble's not from us.

01:27:56.52,01:27:59.88
It's from these renegade angels that've[br]been stuck on Earth since the plagues.

01:28:02.62,01:28:05.15
These guys,[br]they think they're renegade angels.

01:28:05.23,01:28:07.42
See, Padre, it goes down like this.

01:28:07.49,01:28:12.23
These guys think that by passing through[br]that archway, they can go to Heaven.

01:28:12.30,01:28:15.93
You want me to call off the ceremony[br]for that.

01:28:17.00,01:28:18.13
Who sent you?

01:28:20.21,01:28:23.27
We were sent[br]by Him who is called I Am!

01:28:23.34,01:28:25.94
Cute. Really cute.

01:28:26.01,01:28:28.41
Playtime with the cardinal is over.

01:28:28.48,01:28:31.11
- Worked for Moses.[br]- Stay out of this.

01:28:31.19,01:28:32.81
It's not a joke.

01:28:32.89,01:28:35.98
I'm telling you, man,[br]this ceremony's a big mistake.

01:28:36.06,01:28:39.03
The Catholic Church[br]does not make mistakes.

01:28:39.10,01:28:42.03
Please! What about the Church's[br]silent consent of the slave trade?

01:28:42.10,01:28:44.66
And its platform of noninvolvement[br]during the Holocaust?

01:28:44.73,01:28:47.17
All right, mistakes were made.

01:28:47.24,01:28:50.33
But one can hardly hold the current[br]incarnation of Holy Mother Church...

01:28:50.41,01:28:52.43
responsible for the oversights of old.

01:28:52.51,01:28:56.28
I'm a very important man with important[br]matters that demand my attention...

01:28:56.35,01:28:57.84
so if you please...

01:28:57.92,01:29:00.68
- But tomorrow...[br]- Tomorrow goes off without a hitch.

01:29:00.75,01:29:02.12
Do I make myself clear?

01:29:02.19,01:29:06.85
Neither you nor any other influence[br]short of the hand of God Himself...

01:29:06.92,01:29:09.86
is gonna keep this thing[br]from going off without a hitch.

01:29:30.85,01:29:32.87
I can see the headlines now...

01:29:32.95,01:29:34.89
if there were gonna be any.

01:29:34.95,01:29:36.58
"Existence Erased."

01:29:36.66,01:29:38.89
Don't worry about it.[br]We evened the score.

01:29:38.96,01:29:41.33
Hand it over, Silent Bob.

01:29:43.83,01:29:44.99
What up.

01:29:45.07,01:29:47.33
You stole the cardinal's driver?

01:29:47.40,01:29:49.56
That's what he gets[br]for messin' with our girlfriend.

01:29:49.64,01:29:51.40
Cross-dressin' fuck.

01:29:51.47,01:29:53.91
That's sort of sweet.[br]Thanks, guys.

01:29:55.68,01:29:58.61
What do we do now[br]about Bartleby and Loki?

01:29:58.68,01:30:01.88
I guess we're gonna[br]have to try and kill 'em.

01:30:01.95,01:30:04.08
- You said they couldn't be killed.[br]- Correction.

01:30:05.69,01:30:08.42
They won't be killed.

01:30:08.49,01:30:11.55
And just to ensure that,[br]we're all gonna sit tight...

01:30:11.63,01:30:12.89
right here...

01:30:12.96,01:30:16.02
until those two idiots[br]pass through that arch.

01:30:17.13,01:30:19.19
There's only one idiot here,[br]Azrael...

01:30:22.50,01:30:24.67
and I'm looking right at him.

01:30:24.74,01:30:26.27
Muse!

01:30:27.61,01:30:30.74
Just in time to join us[br]for a drink.

01:30:32.22,01:30:33.31
Hey.[br]Where'd you come from?

01:30:35.15,01:30:37.09
- Where'd you come from?[br]- Me?

01:30:37.15,01:30:38.68
Nothingness.

01:30:38.76,01:30:42.49
And that's where I'm returning to[br]in approximately, oh, one hour.

01:30:42.56,01:30:46.12
All right, Plato,[br]sounds like you've had enough already.

01:30:46.20,01:30:48.69
- Let's go.[br]- Oh, darn it!

01:30:48.77,01:30:52.43
Come on, barkeep, just one drink.[br]One for the road, then I'm gone?

01:30:52.50,01:30:55.63
I was trying to find you to tell you[br]I figured out who was behind all this.

01:30:55.71,01:30:57.47
Is that who I think it is?

01:30:57.54,01:30:58.84
- None other than.[br]- Who is he?

01:30:58.91,01:31:01.67
All right, one drink.[br]Then you're gone.

01:31:01.75,01:31:03.91
Give me a...

01:31:03.98,01:31:06.45
Holy Bartender.

01:31:06.52,01:31:08.42
Never heard of it.

01:31:08.49,01:31:12.36
He doesn't know how to make[br]a Holy Bartender.

01:31:12.43,01:31:14.36
You do, don't you, Muse?

01:31:14.43,01:31:15.49
Don't.

01:31:16.60,01:31:17.76
Anybody?

01:31:17.83,01:31:19.32
No?

01:31:19.40,01:31:22.93
Well, I know how to make[br]a Holy Bartender.

01:31:31.51,01:31:32.60
Get it?

01:31:32.68,01:31:34.94
Sweet Jesus, Azrael![br]Why?

01:31:35.02,01:31:38.54
Come on, Demon! Try that shit[br]on somebody who's already dead!

01:31:38.62,01:31:42.06
Oh, Apostle, you maintain[br]that kind of an attitude...

01:31:42.12,01:31:45.15
and you and the barkeep won't be[br]the only corpses in the room.

01:31:45.23,01:31:47.39
The Christ bitch will join you.

01:31:47.46,01:31:50.63
Are you really that stupid?

01:31:50.70,01:31:54.23
You do know what's gonna happen[br]if those two jerks enter that church.

01:31:54.30,01:31:56.67
I'm actually counting on it.

01:31:57.91,01:32:00.07
And if my calculations[br]are correct...

01:32:00.14,01:32:02.87
the pawns are moving into checkmate[br]as we speak.

01:32:07.85,01:32:11.38
"Holy Bartender." I get it.[br]That's a great one!

01:32:11.45,01:32:15.69
I'd also like to acknowledge this great[br]state's governor, Elizabeth Dalton...

01:32:15.76,01:32:17.56
for coming this morning.

01:32:17.63,01:32:20.56
She's a Protestant, but we're[br]not gonna hold that against her.

01:32:22.23,01:32:26.93
Now, let me just tell you a little bit[br]of history about this particular...

01:32:27.00,01:32:29.67
hundred-years-young house of God.

01:32:29.74,01:32:31.04
God's house?

01:32:32.41,01:32:35.14
God doesn't live here anymore.

01:32:35.21,01:32:38.01
He's grown weary[br]of your superficial faith.

01:32:38.08,01:32:41.02
He's turned a deaf ear[br]to your lip-service prayers.

01:32:41.09,01:32:44.42
- He has abandoned you, his favorites...[br]- Sorry.

01:32:44.49,01:32:46.42
To the whim of judgment.

01:32:46.49,01:32:49.02
Hypocrites, charlatans...

01:32:50.70,01:32:53.32
prepare to taste God's wrath.

01:32:53.40,01:32:56.33
- Maybe we should just leave.[br]- You wanted your body count. You got it.

01:32:56.40,01:32:59.03
This lot is rife with sin.[br]We'll judge them all.

01:32:59.11,01:33:00.37
Officer McGhee.

01:33:01.17,01:33:02.94
All right, mouthpiece...

01:33:03.01,01:33:05.81
let's leave the nice cardinal alone[br]and go for a ride.

01:33:05.88,01:33:08.28
Mr. McGhee, don't make me angry.

01:33:08.35,01:33:10.28
You wouldn't like me when I'm angry.

01:33:10.35,01:33:12.22
Is that so?

01:33:16.49,01:33:18.25
Ladies and gentlemen...

01:33:18.33,01:33:23.82
you have been judged as guilty of[br]violations against our Almighty God...

01:33:23.90,01:33:26.30
and this very day...

01:33:26.37,01:33:30.13
I assure you you will all[br]pay for your trespasses...

01:33:30.21,01:33:31.97
in blood.

01:33:32.04,01:33:34.34
- Wings. Now.[br]- I'm feeling a little exposed here.

01:33:34.41,01:33:35.47
Do it!

01:33:36.68,01:33:39.41
- So he's a muse too?[br]- Former muse.

01:33:41.08,01:33:44.48
He was kicked out.

01:33:44.55,01:33:47.02
Ever the fucking apple polisher.

01:33:47.09,01:33:48.18
Then what happened?

01:33:48.26,01:33:50.42
Yes, what?

01:33:50.49,01:33:54.45
Well, Lucifer just had to start[br]his little war for the throne.

01:33:54.53,01:33:57.09
Heaven became divided[br]into two factions...

01:33:57.17,01:33:59.36
the faithful and the renegades.

01:33:59.44,01:34:02.27
Oh, the Ethereal Plains[br]were chaotic with battle.

01:34:02.34,01:34:05.14
Angel against angel.

01:34:05.21,01:34:08.64
And when it was all over,[br]God cast the rebels into perdition.

01:34:08.71,01:34:10.61
But Azrael refused to fight.

01:34:10.68,01:34:14.17
He remained in the middle,[br]waiting to see who came out victorious.

01:34:14.25,01:34:16.35
What are you,[br]some kind of fuckin' chicken?

01:34:16.42,01:34:17.72
No.

01:34:17.79,01:34:19.65
I was an artist...

01:34:19.72,01:34:21.85
stupid!

01:34:21.93,01:34:23.59
I was inspiration!

01:34:23.66,01:34:26.15
A muse has no place in battle.

01:34:26.23,01:34:28.96
So after the fallen[br]were banished to Hell...

01:34:29.03,01:34:30.97
God turned on those[br]that wouldn't fight...

01:34:31.04,01:34:33.40
and Azrael was sent down[br]with the demons...

01:34:33.47,01:34:36.27
something he considers[br]a great injustice.

01:34:36.34,01:34:38.50
Oh, come on.

01:34:38.58,01:34:41.64
Don't tell me you never questioned[br]the judgment, Serendipity.

01:34:41.71,01:34:44.48
No.[br]It never bothered me.

01:34:44.55,01:34:46.58
So you were an artist.

01:34:46.65,01:34:48.42
Big deal!

01:34:48.49,01:34:50.55
Elvis was an artist...

01:34:50.62,01:34:53.99
but that didn't stop him from[br]joining the service in time of war.

01:34:54.06,01:34:55.99
That's why he is the king...

01:34:56.06,01:34:58.00
and you're a schmuck.

01:34:58.07,01:34:59.23
Nice.

01:34:59.30,01:35:01.20
So all this is about revenge.

01:35:01.27,01:35:04.26
You're gonna unmake existence[br]because you have a grudge against God?

01:35:04.34,01:35:08.10
After the first million years?[br]No.

01:35:08.18,01:35:12.01
Escape from Hell[br]became my all-consuming reason.

01:35:12.08,01:35:16.57
So I studied the religions and waited[br]for my opportunity to present itself...

01:35:16.65,01:35:18.18
which it finally did...

01:35:18.25,01:35:20.22
in Catholicism.

01:35:20.29,01:35:21.55
Plenary indulgence.

01:35:21.62,01:35:23.52
But I couldn't exercise it.

01:35:23.59,01:35:26.06
Demons can't become human.

01:35:26.13,01:35:28.29
No, we can't transubstantiate.

01:35:29.77,01:35:31.23
But angels can.

01:35:32.47,01:35:33.80
Bartleby and Loki.

01:35:35.50,01:35:38.53
After that it was a simple matter[br]of waiting for a church...

01:35:38.61,01:35:40.40
to celebrate their centennial...

01:35:40.48,01:35:46.11
and when that finally happened I sent[br]the pair an article laced with ideas.

01:35:46.18,01:35:48.12
An incantation[br]I picked up in the pit...

01:35:48.19,01:35:50.31
kept them cloaked[br]and off Heaven's radars.

01:35:50.39,01:35:53.55
And aside from the triplets here[br]and the Golgothan...

01:35:53.62,01:35:57.42
no soul in Hell had a clue[br]as to what was going on.

01:35:57.50,01:36:00.49
But the Almighty[br]could still putsch the whole deal...

01:36:00.57,01:36:04.06
so I dispatched Him[br]in a fairly ingenious fashion.

01:36:04.14,01:36:06.57
Her. And how?

01:36:06.64,01:36:09.23
That's the only thing[br]I couldn't figure out.

01:36:09.31,01:36:12.24
Oh, no, I've seen[br]way too many Bond movies to know...

01:36:12.31,01:36:15.25
that you never reveal[br]all the details of your plan...

01:36:15.31,01:36:18.75
no matter how close[br]you may think you are to winning.

01:36:18.82,01:36:22.01
The only "X" factor was the involvement[br]of the last scion here.

01:36:23.36,01:36:27.45
But fat lot of good that did, right?[br]I mean, here you all are.

01:36:30.23,01:36:33.39
Powerless to stop the inevitable.

01:36:33.47,01:36:37.60
Look, asshole, I don't know[br]if anyone explained the rules to you...

01:36:37.67,01:36:41.57
but if you succeed everything gets[br]blinked out of existence, even you.

01:36:41.64,01:36:44.61
Human, have you ever been to Hell?

01:36:44.68,01:36:46.87
I think not.

01:36:46.95,01:36:49.21
I'd rather not exist[br]than go back to that.

01:36:49.28,01:36:53.62
And if everyone has to[br]go down with me, so be it.

01:36:53.69,01:36:56.21
Still thinking only about yourself...

01:36:56.29,01:36:58.23
you fucking child!

01:36:58.29,01:37:00.39
Now, now, now.

01:37:01.26,01:37:04.29
Things are getting[br]too intense in here.

01:37:04.37,01:37:06.93
Hey! What say[br]we watch a little TV?

01:37:07.00,01:37:08.97
Yo, put on channel 9.[br]Davey and Goliath.

01:37:10.37,01:37:14.78
Actually, I was thinking[br]more along the lines of current events.

01:37:14.84,01:37:17.28
Keep rolling! Keep rolling!

01:37:17.35,01:37:20.21
I repeat,[br]men with huge fucking wings...

01:37:20.28,01:37:22.44
have laid waste to St. Michael's!

01:37:22.52,01:37:24.88
Bullets don't seem to affect them!

01:37:25.69,01:37:28.62
The remainder of the crowd[br]have dropped to their knees...

01:37:28.69,01:37:31.06
identifying this[br]as the fabled apocalypse.

01:37:31.13,01:37:34.00
Now, I'm not a man of faith,[br]but I'm inclined to agree.

01:37:34.06,01:37:38.26
Oh, God, please, don't come any closer![br]God, no!

01:37:46.34,01:37:49.58
You see that?[br]And I told them to keep a low profile.

01:37:49.65,01:37:53.24
I'd be pissed, but in a couple minutes[br]it's not going to matter anyway.

01:37:57.39,01:37:58.41
Oh?

01:37:59.89,01:38:02.33
Oh, now what was that[br]all about?

01:38:02.39,01:38:04.02
What?

01:38:04.10,01:38:06.59
Oh, nothing.

01:38:06.67,01:38:08.83
I had something in my eye.

01:38:08.90,01:38:11.67
Now who's the fucking child?

01:38:12.84,01:38:16.04
What did you tell him,[br]to hit me with the golf club?

01:38:16.71,01:38:20.37
Are you serious? I'm a fucking demon.[br]You'd have him assault me with a putter?

01:38:21.41,01:38:23.51
You want to play?[br]Then we'll play.

01:38:23.58,01:38:25.38
One side, Red.

01:38:26.12,01:38:27.81
Go ahead, then.[br]Pick it up.

01:38:27.89,01:38:29.05
Call it a gift.

01:38:30.53,01:38:32.52
Come on.

01:38:32.59,01:38:34.03
That's it.

01:38:35.56,01:38:37.16
Take a shot.

01:38:37.23,01:38:40.83
Take your best fucking shot.

01:38:42.30,01:38:44.70
Seriously. I'm not kidding.[br]Take it. Come on.

01:38:45.87,01:38:47.81
Come on, bright boy.

01:38:55.65,01:38:58.42
Don't you know anything?

01:39:13.90,01:39:15.84
Bethany, bless the sink!

01:39:15.91,01:39:17.77
- What?[br]- Just do it!

01:39:17.84,01:39:19.83
Bless the sink, damn it!

01:39:44.10,01:39:46.30
That's what you get,[br]motherfucker.

01:39:48.84,01:39:51.04
But I'm a fucking demon.

01:39:58.35,01:39:59.61
What just happened?

01:39:59.69,01:40:02.35
He said it himself:[br]"I'm a fucking demon."

01:40:02.42,01:40:06.79
Hit a demon with an instrument of God,[br]the pure side so it'll do some damage.

01:40:06.86,01:40:08.92
Silent Bob's an instrument of God?

01:40:09.00,01:40:12.93
No, but Glick's the kind of asshole[br]who'd bless his clubs for a better game.

01:40:13.00,01:40:16.06
- But the sink?[br]- You've got the divine heritage.

01:40:16.14,01:40:18.40
Sanctifying is just[br]one of the fringe benefits.

01:40:18.47,01:40:20.91
Remind me to try the water-to-wine thing[br]at my next party.

01:40:20.98,01:40:24.17
- How far away is this church?[br]- Three towns over, about ten miles.

01:40:24.25,01:40:26.18
- Rufus, grab the gun.[br]- Ten steps ahead of you.

01:40:26.25,01:40:28.48
Take the bartender's car.[br]He won't need it.

01:40:28.55,01:40:31.78
The whole fucking world's against us,[br]dude, I swear to God.

01:40:43.60,01:40:45.30
Oh, my God.

01:40:58.08,01:41:00.81
And people wonder why[br]I don't go to church anymore.

01:41:00.89,01:41:02.15
Are we too late?

01:41:02.22,01:41:04.81
To save these poor schmucks?

01:41:06.59,01:41:07.68
Yeah.

01:41:07.76,01:41:10.42
But we still exist.

01:41:10.49,01:41:12.33
Where are they?

01:41:12.40,01:41:14.89
They could already be[br]in the church.

01:41:14.97,01:41:17.06
Which means if they come out,[br]nobody touches them.

01:41:17.14,01:41:18.57
Are you shitting me?

01:41:18.64,01:41:22.66
The brother here is gonna shred 'em with[br]his angel-be-good special. Huh, homey?

01:41:22.74,01:41:24.68
If they pass through that arch,[br]they come out clean.

01:41:24.74,01:41:26.87
And if they die,[br]they go straight up.

01:41:26.95,01:41:29.38
And hello![br]We know what happens then, right?

01:41:29.45,01:41:31.85
- Why don't they just kill themselves?[br]- It's a mortal sin.

01:41:31.92,01:41:34.75
Die with a mortal sin on your soul and[br]you burn. They don't want to go to hell.

01:41:34.82,01:41:38.69
Then what, are we supposed to just wait[br]for a solution to fall from the sky?

01:41:42.90,01:41:44.26
Friend of yours?

01:41:44.33,01:41:46.27
No, that was a cardinal.

01:41:46.33,01:41:50.17
You can't tell from his face,[br]but the rosaries are a dead giveaway.

01:41:50.24,01:41:52.83
It's one of them![br]Kill that motherfucker!

01:41:52.91,01:41:54.17
Don't you listen?

01:41:54.24,01:41:57.23
- We can't touch him![br]- I wasn't. I was gonna shoot his ass.

01:41:57.31,01:41:59.61
He's been at it for a while now.

01:41:59.68,01:42:01.27
Please! Please!

01:42:02.45,01:42:04.38
We ran out of parishioners...

01:42:04.45,01:42:08.79
so he just started picking up folk[br]off the road and just dropping 'em.

01:42:08.86,01:42:12.09
This is just eons of repression[br]getting purged.

01:42:13.09,01:42:15.22
If only they'd let us jerk off.

01:42:16.60,01:42:18.36
Whoops.[br]Take a step back.

01:42:22.71,01:42:24.14
Let me go!

01:42:25.27,01:42:27.57
Why?[br]What are you trying to prove?

01:42:27.64,01:42:31.05
- All these people![br]- Hey, this wasn't my idea!

01:42:32.05,01:42:33.48
Jesus Christ!

01:42:34.82,01:42:36.75
I just wanted to go home.

01:42:36.82,01:42:38.65
But him, you know...

01:42:38.72,01:42:41.12
he just lost it.

01:42:41.19,01:42:44.42
He realized who you were[br]and what you were gonna have to do.

01:42:44.49,01:42:45.96
He just snapped.

01:42:46.03,01:42:49.66
The funny thing is, this guy[br]could never even stand to see me work.

01:42:49.73,01:42:52.83
He said he felt sorry[br]for you people.

01:42:53.87,01:42:55.43
Now look at him.

01:42:55.51,01:42:57.57
This guy's fuckin' drunker than hell.

01:42:57.64,01:43:00.13
Which means he's human now.

01:43:01.51,01:43:03.61
His wings have been cut off.

01:43:10.22,01:43:12.16
The muse?

01:43:12.22,01:43:14.32
Oh, no way!

01:43:14.39,01:43:17.19
I haven't seen you...[br]You look terrific. Wow!

01:43:17.26,01:43:19.42
What's with the tits?[br]Can I...

01:43:19.50,01:43:21.76
Have you walked[br]through the arch yet?

01:43:25.14,01:43:28.70
Tell me. Have you gone in[br]and come out through the archway yet?

01:43:28.78,01:43:30.14
No!

01:43:35.22,01:43:36.65
He's back.

01:43:59.98,01:44:01.91
We were awaiting your arrival.

01:44:01.98,01:44:05.04
Bartleby, wait. Stop.[br]Listen to me.

01:44:05.11,01:44:07.84
You can't go through with this.[br]Azrael was just using you.

01:44:07.92,01:44:09.18
If you go back...

01:44:10.05,01:44:13.04
I've become aware of the repercussions.[br]I know what I'm doing.

01:44:14.49,01:44:16.19
You sick, twisted fuck!

01:44:17.76,01:44:19.02
Bethany.

01:44:22.20,01:44:25.53
You, of all people, should understand[br]what I'm trying to accomplish here.

01:44:25.60,01:44:28.54
You too know what it feels like[br]to be cast aside.

01:44:28.61,01:44:31.67
But you've only dealt with the pain[br]a few years.

01:44:31.74,01:44:34.84
I've dealt with it for a millennia.

01:44:34.91,01:44:39.35
While you never see your ex-husband or[br]how blissful he is with his new wife...

01:44:40.92,01:44:42.18
and he is...

01:44:45.36,01:44:50.09
seeing you people every day on this[br]perfect world He created for you...

01:44:50.16,01:44:51.89
is a constant reminder...

01:44:51.96,01:44:55.02
that though my kind came first...

01:44:55.10,01:44:57.19
your kind was most revered.

01:44:58.44,01:45:00.80
And while you know forgiveness...

01:45:00.87,01:45:02.81
we know only regret.

01:45:03.88,01:45:05.71
The lesson must be taught.

01:45:05.78,01:45:07.71
All are accountable...

01:45:07.78,01:45:09.04
even God.

01:45:10.32,01:45:12.51
Soon a cadre of police will arrive...

01:45:12.59,01:45:15.85
just in time to kill us[br]as we exit the church.

01:45:17.09,01:45:20.58
Then this failed experiment[br]called existence...

01:45:20.66,01:45:22.15
will cease to be.

01:45:22.23,01:45:23.79
No. Hey. Hey!

01:45:26.50,01:45:28.43
I can't let you do that,[br]Bartleby.

01:45:28.50,01:45:30.60
This has gone too far.

01:45:32.57,01:45:35.01
I might have to take you down.

01:45:36.55,01:45:38.38
It's okay. Shh.

01:45:38.45,01:45:40.04
I'll do it.

01:45:44.82,01:45:46.75
My compatriot.

01:45:48.09,01:45:50.65
Genocide takes a lot out of him.

01:45:50.73,01:45:51.99
He's weakened.

01:45:52.06,01:45:53.53
You're weak.

01:45:53.60,01:45:56.43
More importantly,[br]he's also a human being...

01:45:56.50,01:45:58.69
a condition which carries[br]two liabilities...

01:46:00.50,01:46:02.30
a conscience...

01:46:03.11,01:46:04.54
and...

01:46:07.54,01:46:10.14
a short life span.

01:46:10.21,01:46:13.01
I'm sorry, old friend,[br]but you lost the faith.

01:46:40.78,01:46:42.71
He's lost it.[br]We're fucked.

01:46:42.78,01:46:45.08
- We're absolutely fucked![br]- I hear that shit.

01:46:46.45,01:46:47.89
I can't believe this.

01:46:47.95,01:46:50.58
We're on the brink of nonexistence,[br]and God's still nowhere to be found.

01:46:50.66,01:46:53.75
- What kind of deity gets kidnapped?[br]- Amen to that.

01:47:00.63,01:47:02.76
What the hell are you doing?

01:47:02.84,01:47:06.36
If the whole world's gonna end,[br]you said you'd fuck me.

01:47:10.41,01:47:13.35
- You're a pig.[br]- Nobody's gonna beat that thing.

01:47:13.41,01:47:17.01
We can lay here all comatose like that[br]John Doe Jersey bastard over there...

01:47:17.09,01:47:20.02
- or we can get makin' with the love.[br]- What did you say?

01:47:20.09,01:47:22.18
Make with the love.[br]It's a nice way of saying boning.

01:47:22.26,01:47:23.78
No, about John Doe Jersey.

01:47:27.60,01:47:30.59
That guy, the one they won't take[br]off life support... John Doe Jersey.

01:47:30.67,01:47:32.73
This is where he's at...[br]St. Michael's Hospital.

01:47:34.27,01:47:35.74
Where's the nearest boardwalk?

01:47:35.81,01:47:38.43
I ain't got time to win you a prize.[br]We gotta get to the fucking.

01:47:38.51,01:47:40.98
- Where is it?[br]- Asbury Park, about five miles away.

01:47:41.04,01:47:43.10
- Have you ever been there?[br]- Once, with this chick.

01:47:43.18,01:47:46.21
We were about to fuck on the carousel[br]and I got sick, started puking.

01:47:46.28,01:47:48.15
- Do they have skeeball there?[br]- Yeah.

01:47:51.56,01:47:53.49
That's what I'm talkin' about.

01:48:01.50,01:48:04.59
Whatever you do, stall Bartleby[br]from going into that church.

01:48:04.67,01:48:06.83
Bob, come with me.[br]Come on!

01:48:06.91,01:48:09.60
- How am I supposed to do that?[br]- Think of something!

01:48:09.67,01:48:11.90
I already did,[br]but it takes two of us!

01:48:12.74,01:48:14.97
I repeat, this is not a drill.

01:48:15.05,01:48:16.84
This is the apocalypse.

01:48:16.92,01:48:19.65
Please exit the hospital[br]in an orderly fashion.

01:48:19.72,01:48:21.48
Thank you.

01:48:36.90,01:48:38.53
Hey, Big Bird!

01:48:39.41,01:48:41.10
Ready for the counting game?

01:48:45.88,01:48:47.85
Count the shells, Suck-a-Duck.

01:49:16.05,01:49:18.01
No more bullets.

01:49:18.08,01:49:20.28
Now, what the fuck[br]would you do that for?

01:49:20.35,01:49:23.29
Angels have to cut their wings off[br]to become human.

01:49:23.35,01:49:25.41
You just did him a favor,[br]stupid!

01:50:12.17,01:50:14.87
I hope you're the skeeball type.

01:50:55.99,01:50:58.42
Oh, Bartleby.

01:50:58.49,01:51:02.15
Was Wisconsin really that bad?

01:51:02.22,01:51:04.32
Bow down, stupid!

01:51:22.88,01:51:24.81
I'm sorry.

01:51:47.21,01:51:50.40
Anyone who isn't dead[br]or from another plane of existence...

01:51:50.48,01:51:54.24
would do well to cover their ears[br]right about now.

01:51:54.31,01:51:56.37
What the fuck?

01:52:02.52,01:52:04.55
Thank you.

01:52:36.36,01:52:38.02
It never ends!

01:52:58.05,01:53:00.14
Get off of me.[br]I wanna see what's up.

01:53:00.22,01:53:02.71
What the fuck is this shit?

01:53:02.79,01:53:04.52
Who the fuck are you, lady?

01:53:04.59,01:53:07.06
Why the fuck did you hug my head?

01:53:07.13,01:53:10.06
Quite a little mouth on him,[br]isn't there?

01:53:10.13,01:53:13.10
What the fuck is this, The Piano?[br]Why ain't this broad talkin'?

01:53:13.16,01:53:18.50
I believe the answers that you seek[br]lie within my companion's eyes.

01:53:18.57,01:53:21.87
What the fuck does that mean?[br]Has everyone gone fuckin' nuts?

01:53:21.94,01:53:24.91
What the fuck happened[br]to that guy's head?

01:53:24.98,01:53:26.97
Shh.

01:53:42.50,01:53:44.19
Where was she?

01:53:44.26,01:53:46.82
Imprisoned in a body.

01:53:46.90,01:53:49.84
Bethany figured it all out.[br]She's a clever girl, that one.

01:53:51.34,01:53:52.93
Hang on a minute.

01:54:27.41,01:54:29.34
You missed a bit.

01:54:30.88,01:54:33.82
Well, then, you ready[br]to go back, apostle?

01:54:33.88,01:54:36.35
You ready to make some of those[br]changes I been talking about?

01:54:36.42,01:54:37.58
We'll see.

01:54:37.66,01:54:39.21
Muse?

01:54:39.29,01:54:41.88
Seeing as how you[br]just had to get involved...

01:54:41.96,01:54:44.22
you're welcome[br]to return with us as well.

01:54:44.30,01:54:47.23
First I gotta say good-bye to Bethany.[br]Where is she?

01:54:47.30,01:54:48.73
Oh, no.

01:55:09.99,01:55:12.46
Metatron, is she...

01:55:12.53,01:55:14.86
Afraid so.

01:55:14.93,01:55:18.92
One of the drawbacks to being a martyr[br]is that you have to die.

01:55:19.00,01:55:21.56
But no matter.

01:55:31.08,01:55:33.01
All is being taken care of.

01:55:34.11,01:55:35.55
How so?

01:55:36.68,01:55:39.78
Wax on, wax off.

01:56:03.35,01:56:04.47
How did I...

01:56:04.55,01:56:06.24
She can rebuild you.

01:56:06.32,01:56:07.91
She has the technology.

01:56:07.98,01:56:12.08
She can make you better,[br]stronger, faster.

01:56:17.86,01:56:18.99
That's...

01:56:20.06,01:56:22.86
A very relieved deity.

01:56:24.64,01:56:27.33
You did well, little girl.[br]I knew you'd come 'round.

01:56:27.41,01:56:29.84
Your kind always does.

01:56:31.04,01:56:33.51
You might want to[br]take good care of yourself.

01:56:33.58,01:56:36.38
We're gonna need you down the road.

01:56:36.45,01:56:38.92
I know.[br]I'm the last scion.

01:56:41.59,01:56:44.71
Well, you're half right.

01:56:44.79,01:56:47.73
You were the last scion.

01:56:49.46,01:56:50.89
But now...

01:56:51.96,01:56:53.49
this...

01:56:54.23,01:56:56.33
is the last scion.

01:56:59.37,01:57:01.31
I'm pregnant?

01:57:03.64,01:57:05.80
Can't put anything past you.

01:57:09.12,01:57:11.64
Take care of that parcel for us.

01:57:11.72,01:57:15.66
She has a world of work[br]ahead of her.

01:57:27.07,01:57:29.13
Thank you for...

01:57:29.20,01:57:31.20
I don't know...

01:57:31.27,01:57:32.53
everything.

01:57:36.28,01:57:39.71
God, there's a million things[br]I wish I could ask you...

01:57:39.78,01:57:43.84
most of it questioning your great plan,[br]and that'd be arrogant of me, I know.

01:57:44.62,01:57:46.75
But there is one I need to ask.

01:57:46.82,01:57:50.45
I'm sure you get it all the time, but[br]how many chances like this will I get?

01:57:52.43,01:57:54.40
Why are we here?

01:58:10.98,01:58:13.92
Didn't I tell you she was funny?

01:58:20.79,01:58:23.39
I really enjoyed meeting you.

01:58:24.13,01:58:26.29
It was an honor.

01:58:30.97,01:58:33.90
You did so well.

01:58:38.55,01:58:41.48
I told you She was a woman.

01:58:43.45,01:58:45.82
She's not really a woman.

01:58:45.89,01:58:48.35
She's not really anything.

01:58:48.42,01:58:50.08
She's something, all right.

01:58:51.29,01:58:53.52
Crisis of faith over?

01:58:53.59,01:58:56.53
I think I'm now burdened[br]with an overabundance.

01:58:56.60,01:58:58.53
When it rains, it pours.

01:58:58.60,01:59:00.83
Are you saying you believe?

01:59:02.14,01:59:04.13
But I have a good idea.

01:59:04.21,01:59:05.64
Yes!

01:59:09.58,01:59:11.51
The Man was right about you.

01:59:11.58,01:59:14.61
Now I'm gonna go home[br]and tell Him so.

01:59:15.52,01:59:17.45
And if you clean up your language...

01:59:17.52,01:59:19.99
I just might put in[br]a good word for you too.

01:59:20.06,01:59:21.65
Thanks.

01:59:23.19,01:59:25.63
Why don't you name the kid[br]after me?

01:59:28.46,01:59:30.23
Rufus.

01:59:56.63,01:59:59.06
Yo, we should go to Quick Stop.

02:00:03.90,02:00:05.84
Youse guys[br]wanna hear something sick?

02:00:05.90,02:00:08.84
I got half a stalk[br]when she kissed me.

02:00:08.91,02:00:11.34
I couldn't help it.[br]The bitch was hot.

02:00:11.41,02:00:15.97
You can't talk to me that way anymore.[br]I'm gonna be somebody's mother.

02:00:16.05,02:00:17.54
You're pregnant?

02:00:19.22,02:00:22.75
You know, when you're pregnant you can[br]have sex until the third trimester.

02:00:22.82,02:00:24.76
I'll keep that in mind.

02:08:04.81,02:08:08.72
So, that would make Bethany[br]part black?

