{7747}{7804}Your attention, please.
{7805}{7841}Your attention, please.
{7842}{7969}There has been an accident|at Maison Blanche.
{7970}{8121}It involved Porsche number 64,|driven by Michael Delaney
{8122}{8243}and Ferrari number 18,|driven by Fioro Belgetti.
{8518}{8554}Senora Belgetti,
{8604}{8669}{y:i}Attention, attention...
{21368}{21449}Good afternoon,|ladies and gentlemen.
{21450}{21547}On this circuit, the world's|most famous motor race is run.
{21549}{21619}Conceived by Charles Faroux|and Georges Durand
{21620}{21649}shortly after|the first World War,
{21649}{21697}shortly after|the first World War,
{21698}{21743}the course was named after|the nearest town
{21744}{21815}and the number of hours|that men and machines
{21817}{21901}are put to the supreme test|of speed and stamina.
{21902}{22061}The circuit is 13.469|kilometers, or 8.418 miles.
{22062}{22169}Composed of country roads linked|with the main highway
{22170}{22277}nearly all of it open to traffic|363 days a year.
{22277}{22366}Along the 3.2- Mile|Mulsanne straight
{22367}{22533}the cars reach a maximum speed|in excess of 230 miles per hour.
{22534}{22617}The first race was run in 1923.
{22618}{22705}The lap record was nine minutes,|39 seconds.
{22706}{22829}The average speed,|66.69 miles per hour.
{22830}{22937}Last year, the lap record|was three minutes, 22 seconds.
{22937}{23060}The average speed,|145.508 miles per hour.
{23061}{23134}The race is open|to six classes of cars...
{23135}{23211}from the smallest|production models
{23212}{23281}to the largest sports|and turbo-type engines...
{23282}{23372}all competing at the same time|on the same circuit.
{23373}{23512}There are 55 cars|and 110 drivers
{23513}{23589}representing countries|from all over the world.
{23590}{23692}They will drive day and night,|through sun and rain.
{23693}{23740}Beneath his racing suit,
{23742}{23828}each driver must wear|fireproof underwear
{23829}{23932}capable of withstanding|2,400 degrees Fahrenheit...
{23933}{24039}the temperature of burning|gasoline... for 15 seconds.
{24041}{24108}His blood type must be indicated
{24109}{24188}on either suit or crash helmet.
{24189}{24292}Each car has two alternating|drivers.
{24293}{24376}No driver may total more|than 14 out of the 24 hours.
{24434}{24492}Each driver must have|at least one hour rest
{24493}{24566}between turns at the wheel.
{24567}{24669}No one may drive more|than four consecutive hours.
{24929}{24998}For the first time|in the history of this race,
{24999}{25054}the running start,
{25055}{25136}with the drivers lined up on|the opposite side of the track
{25137}{25173}then running to their cars
{25174}{25222}at the fall|of the tri-colored flag,
{25223}{25282}tests speed of action|for reasons of safety.
{25283}{25342}This year, the drivers will be
{25343}{25394}securely strapped|into their driving seats
{25395}{25435}prior to the start of the race.
{25483}{25566}Yellow flags and yellow lights|along the circuit
{25567}{25634}indicate the presence|of an accident
{25635}{25739}or as it is called|in the racing world, a "shunt".
{25757}{25819}Yellow means danger.
{25820}{25844}No overtaking.
{25845}{25915}The race will start|4:00 p.m. Saturday,
{25916}{25971}and finish 4:00 p. M Sunday.
{25972}{26072}The car covering the greatest|distance in 24 hours
{26073}{26123}shall be the winner.
{26124}{26204}In the case|of the last two cars,
{26205}{26336}this will be the supreme test|of 3,000 miles.
{26337}{26406}And so, ladies and gentlemen,
{26407}{26488}welcome to the most famous|motorcar race in the world...
{26489}{26541}the 38th running|of the grand prix
{26542}{26607}of endurance|and efficiency...
{26608}{26704}the 24 hours of Le Mans.
{31682}{31776}We're pleased to welcome|Michael Delaney back to Le Mans
{31777}{31852}after his unfortunate accident|here last year
{31853}{31912}and to see that he is|in such good form
{31913}{31984}following his exciting race,|a fortnight ago
{31985}{32026}at the Nurburgring
{32027}{32096}where Ferrari's top driver,|Erich Stahler,
{32097}{32129}narrowly beat him.
{32130}{32203}The Delaney-Stahler rivalry
{32205}{32293}will be interesting to follow|on this very different circuit
{32294}{32340}where the endurance of the car
{32341}{32424}is as important as is the skill|of the driver.
{32738}{32804}It is now five minutes to four.
{32805}{32856}Five minutes to start.
{32857}{32912}Will all drivers be|in their cars
{32913}{32978}in one minute's time, please.
{33391}{33457}Drivers... to your cars, please.
{33457}{33528}Drivers... to your cars, please.
{33761}{33823}Four minutes to start.
{34633}{34712}Three minutes to start.
{35273}{35352}Two-and-a-half minutes to start.
{35635}{35695}Two minutes to start.
{35802}{35916}And once again, here are the|first ten qualifying positions:
{35917}{36023}Number 25,|driven by Kurt Ahrens;
{36024}{36129}number 15,|driven by Michael Parkes;
{36130}{36260}number 21,|driven by Johann Ritter...
{36334}{36463}...number 22,|driven by Paul-Jacques Dion;
{36464}{36612}number eight,|driven by Erich Stahler...
{36659}{36762}...number five,|driven by Lugo Abratte;
{36763}{36909}number six,|driven by Vito Scaliso;
{36910}{37055}number seven,|driven by Claude Aurac;
{37056}{37175}number 20,|driven by Michael Delaney...
{37200}{37319}...number 14,|driven by Gilles Marnier.
{45333}{45396}Over three minutes have passed.
{45397}{45472}We may expect the cars through|the check gate any moment now.
{45473}{45526}Will it be Porsche or Ferrari|in the lead?
{51692}{51744}Here's the leading car,|Porsche number 25,
{51746}{51789}in for its first pit stop|for fuel
{51790}{51836}and possible driver change.
{52379}{52452}And here comes Erich Stahler,|Ferrari number eight,
{52453}{52534}closely followed by the first|of the Gulf-Porsche cars,
{52535}{52589}number 20,|driven by Michael Delaney.
{52645}{52695}Watch out|for the red Lola.
{52774}{52813}Okay.
{53677}{53733}Pretty quick pit stop|for the Ferrari...
{53850}{53942}...and here comes 20,|back on the track.
{53943}{54010}Still in first place.
{54011}{54126}Gulf-Porsche number 21,|driven by Johann Ritter,
{54127}{54207}entering the pit.
{54393}{54447}And... Porsche|number 20 Delaney.
{54448}{54471}20 by four.
{54472}{54516}Okay, thank you.
{54517}{54603}My colleague has just handed me|a weather report,
{54604}{54680}and it looks as if|the possibility of rain...
{54681}{54782}which was previously forecast...|will shortly be upon us.
{55105}{55188}Just one more, Mr. Delaney.
{55398}{55424}Hello.
{55425}{55452}Hello.
{55453}{55540}You had a very good start.
{55541}{55604}It's a long race.
{55605}{55630}Are you well?
{55882}{55936}Excuse me.
{57797}{57844}Thank you.
{58007}{58057}What will you tell|Peter and Erica
{58058}{58094}when they get old enough
{58095}{58160}to ask what their father|does for a living?
{58161}{58206}I'll tell them|that their father
{58207}{58262}is the greatest|chauffeur in the world.
{58263}{58346}If you had a choice,
{58347}{58396}would you like to tell them|something else?
{58397}{58476}For example,
{58477}{58565}"Well, this week, daddy's|flying to Switzerland."
{58624}{58712}Yes. The new motor factory|is almost completed
{58713}{58758}and I have to interview
{58759}{58788}various applicants for...
{58789}{58826}What are you trying|to tell me?
{58827}{58934}Would you like that better?
{58935}{59029}Only if you'd like it better.
{59086}{59144}If they ask me what their mother|does for a living,
{59145}{59170}I'll say "she lies."
{59245}{59290}"She can look straight|into your eyes
{59291}{59324}"and tell the biggest lies
{59324}{59372}you've ever heard|in your life."
{59373}{59408}Really?
{59409}{59447}Yes.
{59469}{59540}It's the right time to stop.
{59541}{59632}I can finish quite well|in this race.
{59633}{59672}Perhaps even...
{59735}{59848}Well, in any case,|it's the right time to stop.
{60123}{60199}As was forecast,|we have our first touch of rain.
{60200}{60252}It's going to be|very interesting
{60253}{60333}to see what tactics|the team manages in the rain.
{60334}{60369}If it's only a shower,
{60370}{60442}they won't change|from dry to rain tires.
{60443}{60513}But if it does continue,|they must.
{61964}{62026}Your attention to the pit area.
{62027}{62118}The longtail Porsche,|number 25, is coming in,
{62119}{62163}after having been|out on the circuit
{62164}{62212}for only 14 minutes,|since its last stop
{62213}{62267}for fuel and driver change.
{62268}{62312}The team of Kurt Ahrens|and Vic Elford
{62313}{62355}has built up|a formidable early lead
{62356}{62403}on the factory Ferraris
{62404}{62436}and the Gulf-Porsche team.
{62437}{62467}However, it appears now
{62468}{62524}that something definitely|out of the ordinary
{62525}{62567}has befallen the Austrian entry.
{62568}{62636}You will recall that|this is the car which,
{62636}{62725}for the first time|in the history of Le Mans,
{62728}{62811}averaged a speed in excess|of 150 miles per hour.
{63096}{63124}Mr. Delaney.
{63125}{63181}You know the white longtail|is out of the race
{63183}{63212}with a blown engine.
{63212}{63249}Yeah, well, that's bad luck.
{63250}{63280}Do you think|it will be
{63280}{63319}another|Ferrari-Porsche race?
{63320}{63377}A little early to say,|but I think so.
{63378}{63434}What kind of race|will you drive?
{63435}{63508}Try to save the machine,|go as fast as I can, try to win.
{63509}{63575}Do you think it will be|like Nurburgring...
{63576}{63616}a race between|you and Stahler?
{63616}{63640}I hope not, ma'am.
{63641}{63683}And what do you|think of Stahler?
{63684}{63716}Stahler?|I think he's probably
{63716}{63755}one of the best drivers|in the world.
{63757}{63793}Excuse me.
{63820}{63865}What do you think|is the most difficult thing
{63866}{63889}about Le Mans?
{63890}{63927}To go as fast as possible,
{63928}{63984}and keep the car on the road|for 24 hours.
{63985}{64022}That's difficult.
{64146}{64183}Would this be|the same kind of race
{64184}{64228}you had with Delaney|at the Nurburgring?
{64228}{64252}Well, this is Le Mans.
{64253}{64288}It's a different thing,|you know?
{64289}{64325}Do you think|that you and Delaney
{64326}{64366}will end up having|a close race here?
{64367}{64451}Maybe. He's fast, I'm fast,|so we're always together.
{64454}{64478}Good luck.
{64640}{64666}Michael...
{64851}{64887}How's that German|car running?
{64888}{64950}Fast. Ferrari?
{64951}{64983}Fast.
{64984}{65019}It's getting wetter.
{65020}{65048}Slipping and sliding.
{65049}{65095}Michael, uh...|the press is making
{65096}{65143}a big thing about us.
{65182}{65265}Yeah. But it's money.
{65294}{65334}That's American.
{65373}{65462}Michael...
{65463}{65508}be careful.
{65549}{65611}Now don't be a pain|in the ass, Erich.
{65896}{65955}And here are|the official positions,
{65956}{66000}two hours into the race.
{66000}{66051}In first place,|Ferrari number eight
{66052}{66112}finished 35 laps|at an average speed
{66113}{66200}of 144.981 miles per hour.
{66201}{66272}In second position|is Gulf-Porsche number 20
{66274}{66313}at 35 laps...
{68136}{68178}All cars have come into the pits
{68179}{68246}to change to rain tires,|with the notable exception
{68247}{68289}of the three|Gulf-Porsche entries
{68290}{68332}and the four Ferrari team cars.
{68332}{68452}It is apparent that neither|Porsche manager David Townsend
{68453}{68503}or Ferrari manager|Loretto Fuselli
{68505}{68579}wants to call his cars in|for an unscheduled pit stop
{68580}{68630}during this closely|contested race.
{68631}{68681}Looks kind of hairy|out there.
{68774}{68804}At practice|it didn't rain,
{68804}{68843}so this is really|your first time
{68844}{68879}out in the weather|at Le Mans.
{68880}{68922}J"a," it is.
{69004}{69097}Why doesn't Townsend|bring them in for rain tires?
{69098}{69147}Why don't you ask him?
{69400}{69450}It's raining worse|at Mulsanne.
{69451}{69481}They're due in,|in 11...
{69482}{69525}In 11 minutes. I know.
{71553}{71620}Your attention, please.
{71620}{71664}Your attention, please.
{71665}{71719}There has been an accident...
{71769}{71855}It involves Lola number 11,|and Porsche
{71856}{71927}number 47.
{71928}{71982}Fortunately,|the drivers are not hurt.
{71983}{72041}Bring them in|for rain tires.
{74164}{74203}Here we are.
{74204}{74239}Ferrari's decided|to change at last.
{74377}{74452}And Porsche number 20|has come into the pits, also.
{74453}{74522}Now we should see a race develop|between the mechanics,
{74523}{74552}and they will determine
{74553}{74629}who's going|to be the first to go out.
{75803}{75868}20 is away first.
{75869}{75923}Delaney now leads Le Mans.
{75988}{76036}And there goes Stahler,
{76037}{76081}now in second place.
{76448}{76484}- No problem.|- No problem, yes, yes.
{76485}{76509}It's nothing!
{77280}{77336}It's going well, Claude,|isn't it?
{77336}{77372}Ou"i." I can feel it.
{77373}{77409}The machine is good.
{77410}{77452}This might be the year.
{77453}{77495}Well, let's hope so.
{77496}{77533}It's a long race.
{77534}{77560}I know.
{77561}{77609}Don't think|too far ahead.
{77610}{77637}Lisa?
{77638}{77663}Yes?
{77664}{77701}Would you like|some coffee?
{77744}{77794}No, thank you.
{77866}{77911}{y:i}Ciao.
{82497}{82548}What problems|have you got out there?
{82549}{82607}Only thing is,|that off the Mulsanne,
{82608}{82655}in the middle of the road...
{82703}{82750}...if you stay|a little bit to the right
{82751}{82803}and watch it when you come up|over the hump,
{82804}{82857}has a little bit of tendency|to go this way.
{83111}{83183}Be a little careful|before you go into the cape,
{83184}{83235}and you can out-brake|the Ferrari.
{83423}{83482}Hey, guys, move it!
{83912}{83943}All right, Mike...
{83973}{84021}How long?
{84763}{84799}{y:i}Merci.
{85121}{85169}"Monsie"u"r."
{85853}{85901}{y:i}Bon soir,|Monsieur Delaney.
{85902}{85950}{y:i}Bon soir.
{86062}{86096}Hello, Mike.
{86097}{86125}How you doing?
{86127}{86175}Cheese, please.
{86972}{87037}Seems to be|the only seat left.
{87039}{87068}May I sit down?
{87628}{87670}Where are you living now?
{87671}{87719}In Paris.
{87853}{87903}I have to watch myself|in Paris.
{87904}{87942}I always get fat there.
{88087}{88120}I heard you and Erich
{88120}{88176}had quite a race|at the Nurburgring.
{88177}{88226}Well, he keeps me honest.
{88263}{88316}Can I, can I|get you something?
{88317}{88353}No, thank you.
{88637}{88688}Were you hurt badly|in the accident?
{88731}{88765}No.
{88769}{88897}Was it difficult|to get back to racing?
{88974}{89024}Not really.
{89071}{89130}But it must have been|very difficult for you.
{89286}{89334}It was, in the beginning.
{89335}{89396}I'm better now.
{89493}{89590}I was just wondering...
{89591}{89644}why you came back here.
{89878}{89961}For myself.
{92662}{92691}Delaney's on his way.
{92692}{92742}Dixie.
{92743}{92818}Check the rear uprights|on 20, 21 and 22.
{92819}{92851}All right.
{92981}{93050}It is 5:00 a.m.,
{93051}{93092}the 13th hour of the race,
{93093}{93168}and the Ferrari-Porsche battle|continues unabated
{93169}{93247}with only 12 seconds|separating the two lead cars:
{93248}{93320}Gulf-Porsche number 20,|Ferrari number eight.
{93321}{93404}As of this moment,
{93405}{93465}there are 25 cars|left in the race.
{93465}{93493}I shall give you
{93494}{93559}a precise listing of|the most recent abandonments
{93560}{93605}in a few moments' time.
{93779}{93827}Watch the handling,|Michael.
{93828}{93909}Just a slight return|about the rear uprights.
{94806}{94874}Here's the second|Ferrari team car coming in.
{94876}{94935}Number seven,|piloted by Chris Barnett.
{94936}{95000}Another driver change|should be in order.
{95266}{95357}Yes, Claude Aurac|will take over.
{104526}{104589}Your attention, please.
{104590}{104625}Your attention,|please.
{104626}{104687}There has been an accident.
{104688}{104755}It involves|Ferrari number seven,
{104756}{104808}Porsche number 20.
{104809}{104865}Both cars are out of the race.
{104866}{104939}I shall tell you about|the drivers' condition
{104940}{105042}as soon as I get word|from hospital.
{105565}{105614}This way.
{106092}{106143}Please sit down|there, please.
{107053}{107077}Yes.
{109046}{109116}Can you tell us about Aurac?
{109117}{109167}Do you know if Michael|caused the accident?
{109168}{109211}We just want to ask you...
{109584}{109623}I don't know.
{109679}{109717}I don't know
{109718}{109778}and I don't want|to talk about it!
{110058}{110110}Do you compare this|to last year's shunt,
{110111}{110163}the one in which this lady's|husband was killed?
{110748}{110828}I have just received word from|the pit box that Marta Simca...
{110876}{110936}...that Marta Simca number 30,
{110937}{111006}out of the race|due to gear box problems.
{111058}{111131}Just got word from|the hospital about Claude.
{111132}{111205}It's bad, but they say|he will pull through.
{111470}{111520}And Delaney?
{111521}{111601}Nothing serious,|but he's out of the race.
{112157}{112199}Are you all right, Michael?
{112200}{112223}I'm fine.
{112224}{112250}You sure?
{112251}{112278}Yeah. I'm all right.
{112279}{112307}Where are we running?
{112308}{112341}Third and fourth.
{112489}{112537}Michael, are you all right?
{112538}{112571}Yeah, I'm okay.
{112572}{112599}It was a bad shunt.
{112600}{112639}Yeah.
{112640}{112668}Where are you running?
{112669}{112696}Third.
{112697}{112744}If you try to nail Scaliso
{112745}{112806}do it down through|Maison Blanche.
{112807}{112853}He doesn't like it there.
{112854}{112891}Thank you.
{114160}{114221}Michael, are you all right?
{114222}{114249}I'm okay.
{114250}{114277}Are you sure?
{114278}{114301}No. I'm fine.
{114302}{114366}Then what happened to the car?
{114410}{114437}It was my fault.
{114438}{114471}I made a mistake.
{114472}{114548}I wrote the car off, David.
{114666}{114717}David.
{117526}{117579}This isn't just|a thousand-to-one shot.
{117582}{117649}This is a professional|blood sport.
{117650}{117715}And it can happen to you.
{117716}{117778}And then it can happen|to you again.
{117920}{117990}When people risk their lives...
{117991}{118102}shouldn't it be for something|very important?
{118180}{118224}Well, it better be.
{118225}{118319}But what is so important
{118320}{118426}about driving faster|than anyone else?
{118515}{118586}A lot of people go through life|doing things badly.
{118588}{118677}Racing's important to men|who do it well.
{118678}{118763}When you're racing it's...
{118764}{118813}it's life.
{118814}{118891}Anything that happens|before or after...
{118892}{118960}it's just waiting.
{121942}{121991}What happened|on the Delaney shunt?
{121992}{122042}There was a problem|with the maul,
{122043}{122087}slower traffic|got in the way.
{122089}{122130}The car is finished?
{122131}{122159}Yes, the car|is finished.
{122247}{122310}Hey, David,|21's coming in!
{122311}{122349}Get the jack!
{122543}{122588}It's a wishbone.
{122666}{122706}Your attention in the pit area
{122707}{122765}with the leading car:|Gulf-Porsche number 21
{122766}{122836}is experiencing something|other than a routine stop.
{122836}{122900}From the action of the|mechanics, it would appear
{122901}{122969}that there is a problem|with the rear suspension.
{123372}{123416}Here is the second place car,
{123417}{123457}Ferrari number eight,
{123458}{123491}coming in for what should be
{123492}{123542}its last stop for fuel|and driver change.
{123543}{123584}Erich Stahler will
{123585}{123645}take over for the final|driving session, and no doubt
{123647}{123693}will resume the lead|from Gulf-Porsche number 21
{123695}{123752}still in the pit.
{123794}{123831}Too slow.
{124766}{124815}Stahler's in trouble.
{124852}{124919}The bonnet's up|on Ferrari number eight.
{124920}{124952}Ladies and gentlemen,
{124953}{125025}the first and second place cars|are in the pits
{125026}{125084}experiencing|mechanical difficulties.
{126050}{126099}Yeah?
{126100}{126134}Hello, David.
{126135}{126177}Are you fit, Michael?
{126178}{126217}Well, I'm a little stiff...
{126218}{126249}I say, are you fit?
{126250}{126295}My knees are sore.
{126296}{126335}Stahler's Ferrari's|in the pits
{126336}{126364}with ignition problems.
{126365}{126398}We got 21 in|with a broken
{126399}{126423}rear wishbone.
{126424}{126469}Dixie's fixing it now.
{126470}{126500}I want you to replace Ritter.
{126501}{126527}He's not quick enough.
{126556}{126596}Excuse me.
{127202}{127288}Michael, I want you|to drive flat-out.
{127290}{127343}I want Porsche|to win Le Mans.
{127730}{127772}Your attention, please.
{127773}{127826}Your attention, please.
{127827}{127901}Announcing a change of drivers.
{127902}{127950}Gulf-Porsche number 21|will be driven
{127951}{128035}by Michael Delaney,|replacing Johann Ritter.
{128036}{128096}Repeat:|Gulf-Porsche number 21
{128097}{128163}will be driven|by Michael Delaney,
{128164}{128217}replacing Johann Ritter.
{128840}{128885}The car is running good.
{128886}{128931}Brakes are okay.
{129216}{129276}Darling,|does it really matter?
{129276}{129336}Yes, it does.
{129336}{129399}But you were|going to quit anyway.
{129400}{129447}Yeah...
{129448}{129496}but not this way.
{129936}{129966}Ladies and gentlemen,
{129967}{130043}through the Chicane and|along the grandstand straight,
{130044}{130107}here is the new leader,|Ferrari number five,
{130108}{130136}driven by Lugo Abratte,
{130137}{130199}with only eight minutes|remaining
{130200}{130249}in the 24 hours of Le Mans.
{130320}{130397}And now, in second place
{130398}{130463}is Larry Wilson,|in Gulf-Porsche number 22.
{136188}{136248}And now, through the Chicane,
{136249}{136291}and going into the final lap,
{136292}{136338}is the Veida Ferrari|number five,
{136339}{136398}driven by Lugo Abratte.
{136399}{136451}And in second place
{136452}{136509}is Larry Wilson,|in Gulf-Porsche number 22.
{136971}{137035}And, on the same lap,|having made up nine seconds
{137036}{137067}on the two leaders,
{137068}{137134}are Ferrari number eight|and Porsche number 21,
{137135}{137176}running third and fourth...
{137177}{137224}Erich Stahler|and Michael Delaney,
{137225}{137271}pushing their cars to the limit|in this,
{137272}{137311}the most closely|contested finish
{137313}{137355}in the history of Le Mans.
{140469}{140507}Your attention, please.
{140508}{140547}I have just received word
{140550}{140602}that the first place car,|Ferrari number five,
{140603}{140632}driven by Lugo Abratte,
{140633}{140680}is out of the race|with tire trouble.
{140681}{140743}With only two minutes|remaining in the race,
{140744}{140804}the lead has been taken over|by Gulf-Porsche number 22,
{140805}{140853}driven by Larry Wilson.
{145371}{145432}Larry Wilson in 22.
{145433}{145481}Porsche wins Le Mans!
{145558}{145645}And second, Michael Delaney|in Gulf-Porsche number 21.
{145646}{145716}And third, Ferrari number eight,
{145717}{145790}driven by Erich Stahler.
{149664}{149706}Thank you, Michael.
