{1102}{1197}JACKIE CHAN IS THE PRISONER
{1737}{1797}[Woman On P.A., Indistinct]|...now arriving from Taipei.
{1809}{1893}[Woman]|Andy, overhere!
{1953}{1989}Oh, I missed you, honey.
{2001}{2037}Hey, good to see you, buddy.
{2049}{2109}- Wish I could say the same.|- [ Laughing ]
{2121}{2157}Come on. Let's go.
{2336}{2372}[Man] Thanks for coming|on such short notice, Andy .
{2384}{2444}Anything for you, Commissioner.
{2456}{2492}Cheers.
{2600}{2684}I'm sorry for all the secrecy,|but this is a special case.
{2696}{2756}I need a fresh face|to go undercover.
{2792}{2852}Many of my men,|they're too recognizable.
{2864}{2924}We can't take any chances.
{2936}{2972}You report to Jerry|tomorrow, okay ?
{2984}{3044}Can you talk shop later, Dad ?
{3056}{3092}Come on, guys.|I slaved over this feast all day,
{3104}{3164}- and I don't want it to get cold.|- [ Chuckling ]
{3176}{3236}That sounds like an order.
{3248}{3308}- Dig in.|- Yes, sir. [ Chuckling ]
{3344}{3404}- Welcome aboard.|- While he's here,
{3416}{3452}I wanna spend some|quality time with him.
{3464}{3523}Got that ?
{3535}{3595}That's another order.|[ Chuckling ]
{3607}{3691}Listen, you guys.|You've always meant a lot to me.
{3703}{3739}The both of you.
{3751}{3835}Hell, I became a cop|because of you.
{3847}{3883}Bottom line:
{3919}{4003}This case is my chance|to... make you proud of me,
{4015}{4123}to prove myself to you.
{4135}{4171}Jerry. Sir.
{4351}{4411}It's really coming down.
{4423}{4483}- You need a ride,Jerry?|- No, I'm just up the street.
{4495}{4555}Thankyou, sir.|Good night.
{4567}{4651}So, I'll take Andy|back to the hotel, Dad.
{4663}{4722}Thanks for the dinner,|sir, and the case.
{4734}{4770}Good night.
{4782}{4818}[Thunder Rumbling]
{5286}{5322}Whoo! Wow.
{5862}{5921}[ Chuckling ] I'm not doing it|in the car again.
{5933}{5993}It's too cramped. Wait till|we get back to the hotel.
{6005}{6065}- Okay? |- Okay.
{6101}{6137}[Engine Starting]
{6197}{6257}- [ Doorbell Ringing ]|- Who's visiting your dad ?
{6317}{6353}- [ Gunshots ]|- [ Screaming ]
{6365}{6425}Freeze!
{6437}{6497}Stop, asshole!
{6845}{6881}[ Woman Sobbing ]
{7180}{7240}Looks like the killer's gun.|Must've dropped it.
{7564}{7600}[Jerry]Nothing handier|than a severed thumb...
{7612}{7648}when you want to|run some prints, huh?
{7972}{8032}[Keyboard Clacking]
{8044}{8128}[Andy] Carl Chang? |He's a member of the Zing triad.
{8140}{8176}[Jerry] This guys's got|a record as long as my dick.
{8284}{8367}[Andy]|Executedby firing squad ?
{8475}{8535}How does a dead man...
{8571}{8583}commit murder ?
{8619}{8655}It can't be.
{8667}{8775}Unless... prison is supplying|false information.
{8811}{8871}Maybe the Commissioner|wanted us...
{8883}{8943}to investigate this.
{9339}{9399}We've gotta find a way...
{9411}{9447}to investigate that prison.
{9483}{9518}I'll think about it.
{9578}{9662}I'll think about it.|Okay ? Good night.
{9842}{9926}-Where's the rest of the money ?|-That's all learned, baby. I swear.
{9938}{9974}You worthless bitch !
{9986}{10046}Hey, pretty boy down there|is watching us.
{10562}{10622}I saw you watching us.|Hey, I'm talking to you.
{10921}{10957}He broke my tooth.
{11041}{11077}[Sirens Approaching]
{11689}{11725}What were you thinking ?
{11785}{11845}I fiigured...|[ Exhaling ]
{11857}{11988}what better way to investigate|the prison than...
{12000}{12036}from the inside.
{12048}{12084}You're nuts.
{12240}{12300}What about Sally ?
{12312}{12372}I'm undercover.|She doesn't have to know where.
{12480}{12516}Andy,
{12528}{12564}assault and battery is two years.
{12576}{12636}Maximum security.
{12648}{12708}And if I interfere,
{12720}{12756}I'll blow your cover.
{12768}{12828}You realize that ?
{12840}{12876}You know, it's up to you.
{13199}{13235}[Men Chattering]
{13271}{13307}[Guard]|WeIcome to your new home.
{13319}{13379}You will refer to the guards|as ''boss''or ''sir. ''
{13415}{13499}We run a clean shop here. Smoke in|your cell , that's ten days in the hole.
{13511}{13571}Spit, piss, shit on the prison|floor, that'll get you 20.
{13583}{13667}Unsupervised fiighting gets you|a month without daylight.
{13679}{13787}Don't talk back, disobey|an order or break any rule.
{13799}{13859}If you can follow these rules during|your stay in this fine institution,
{13895}{13931}you and I will|get along just fine.
{13943}{13979}That is all you need|to remember.
{13991}{14075}Oh, and if you drop the soap|in the shower,
{14087}{14123}you are on your own.
{14302}{14386}- Enjoy your stay.|- [ Crowd Clamoring ]
{14398}{14434}Back off, you slobs!
{14446}{14530}Excuse me.|My friend Goliath and I...
{14566}{14602}like the upper bunk,|so if you couId--
{14614}{14674}Thanks. Hey, how about that asshole ?
{14686}{14722}And his stupid rules.
{14926}{14986}Hey. What does|that idiot know, huh?
{15118}{15178}If we followed rules,|we wouldn't be in here. Right ?
{15478}{15513}Go ahead.
{15717}{15777}- Charlie.|- Andy.
{15789}{15849}- [ Laughing ]|-[Man]Bed check. Bed check!
{15861}{15897}Hey, hand over that smoke.
{16005}{16065}- Oh, shit.|- Fell for it again. You're too easy.
{16077}{16137}- Thanks a lot.|- Don't mention it.
{16149}{16185}What do you want, anyway ?
{16197}{16233}We got heavy-duty odds|on the new guy-- 20 to 1 .
{16269}{16329}Hey, Charlie. What's up?
{16341}{16425}The prison champ fights the new guy|tonight. You're the new guy: you fight.
{16437}{16521}- No fucking way.|- Play it smart and put on the gloves.
{16533}{16617}- Don't be stupid. Right, Charlie ?|- You're right. Do it.
{16629}{16665}[ Chanting ]|Go, champ! Go, champ!
{16940}{16976}Come on. Look out!
{17036}{17096}Hey, Andy! 20 to 1|ifyou go thirty seconds!
{17132}{17192}I got everything riding on you!|You better not let me down!
{18283}{18319}That's the way!
{18451}{18463}[ Chanting Continues ]
{19122}{19158}Get up!|Don't puss out now!
{19170}{19230}Seven! Eight!
{19242}{19302}Nine! Ten! He's done!
{21041}{21101}[Man]|Mail call Come on, guys !
{21113}{21149}Here you go,Jimmy.
{21161}{21245}- How's your son doin' ?|- Yeah.
{21257}{21341}He's in a fucking boarding school.
{21377}{21413}His birthday's tomorrow.
{21425}{21461}Gotta find a way|to get out and see him.
{21473}{21556}You mean escape ?|Don't joke around, man. [ Chuckles ]
{21856}{21916}Hey, you hungry ? Why don't|you let me down in the kitchen ?
{21928}{21988}I'll fix you a feast like I did|last month. You remember ?
{22096}{22132}I remember that.|Let him in.
{22216}{22252}Oh, thank you, sir.
{22336}{22396}You gonna have some of this ?
{22408}{22444}I'm not hungry.
{22504}{22588}You'll come around once you|get a whiff of my cooking.
{22600}{22636}[ Chuckling ]|Oh, yeah, right.
{22648}{22707}Nobody can resist my cooking.
{22719}{22755}You'll see. Nobody.
{22863}{22923}- I'll bet I can.|- It's a bet.
{22935}{22971}Now check this out.
{23127}{23187}Saute the onions,
{23199}{23307}frythe meat,|and add plenty of chillies.
{23367}{23403}Cook it up neat.
{23463}{23499}And must remember...
{23535}{23571}to use the pepper.
{23583}{23643}[ Sneezing ]
{23655}{23715}[ Laughing ]|Et voila !
{23727}{23763}[ Sniffiing ]
{23799}{23859}You're drooling.
{23918}{23954}I'll turn it off.
{24950}{24986}Stay.
{25261}{25321}Hey, brother, got a light ?
{25381}{25417}[Dog Whining]
{25525}{25561}Thanks.
{25573}{25657}[ Sighing ]|Graveyard shift really sucks, man.
{25669}{25729}But how else can I pay|for my mom's operation ?
{25741}{25825}[ Chuckling ]
{25885}{25921}Hey. I say something funny ?
{25933}{26017}No. I don't mean anything. It's--
{26029}{26065}[Dog Sniffing]
{26077}{26137}[Dog GrowIs, Barks]
{26604}{26616}Note to self:
{26652}{26712}Next time escaping|from prison on foot,
{26724}{26760}lose... weight... fiirst.
{26772}{26808}[ Panting ]
{26916}{26976}Hey! Hey!
{27036}{27072}Slow down. Police inspection.
{27132}{27168}Get out. Get out.
{27276}{27360}- Oh, boy. It's not my day.|- Huh ?
{27372}{27432}Care to explain yourself, offiicer ?
{27659}{27767}I've heardofstrip searches,|but this is fucking ridiculous!
{27875}{27911}I'll get it.
{27971}{28055}- Hey,Joey.|- Pa!
{28115}{28151}Ah!|[ Laughing ]
{28451}{28487}Cheese!
{28667}{28750}-[Joey ] I wish today would never end.|-Me too, son.
{28762}{28822}Car 41 7 reporting from|the Li Chin Boarding School.
{28834}{28918}Fugitive's vehicIe has|just enteredthe courtyard.
{28930}{28966}Requesting backup.
{29098}{29134}[Joey Laughing ]
{29170}{29230}I've got to go now,|but I'll visit next year.
{29266}{29302}You promise ? Shake.
{29338}{29374}[SirensApproaching]
{29434}{29470}Today was great.
{29482}{29566}I have to get back to my top-secret job|as a spy for the government.
{29578}{29614}Aw, do you have to, huh?
{29626}{29710}I want you to run up those steps|and not look back.
{29722}{29806}- Why not?|- I told you. It's top secret.
{29818}{29878}If I tell you, then|they'd have to kill you.
{29889}{29973}You're just like|James Bond, Dad ?
{30009}{30045}You remember,Joey, I love you.
{30057}{30117}One, two, three.
{30129}{30237}Bye, 007.|[ Laughing ]
{30657}{30693}Don't move. Hands up.
{30969}{31029}[ Groaning ]
{31184}{31220}You've done it this time, boy.
{31232}{31292}Earned yourself a beating...
{31304}{31340}and a visit from the warden.
{31496}{31532}That's enough!
{32000}{32084}Your escape made|the prison and me...
{32096}{32132}look bad.
{32144}{32252}Not to mention|what you did to Rambo.
{32287}{32323}[ Whining ]
{32383}{32419}Go ahead ! Apologize!
{32479}{32539}I'm sorry.
{32551}{32587}You flea-bitten bitch.
{32671}{32755}[Announcer] The beautiful Kiki is|wearing a hot-pink combination.
{32767}{32827}Perfect for a night out|at the hottest cIubs.
{33247}{33283}It's about tonight's match.
{33319}{33355}Listen carefully, huh ?
{33367}{33427}Mr. Bing wants you to lose.
{33439}{33522}We have ways of being persuasive.
{33654}{33690}I won't throw the match.
{33798}{33882}You win tonight, I'll feed you|your gonads, okay? 
{33942}{33978}[ Chuckling ]
{34206}{34242}Steve! Have fun.
{34350}{34386}- How was I ?|- Great, honey.
{34446}{34482}What's this ?
{34614}{34674}These make me look like a midget.
{34757}{34793}[AppIause]
{34949}{34985}I have the touch tonight, honey.
{35237}{35273}[AppIause]
{36868}{36904}Don't be stupid.
{37131}{37191}- [AppIause]|- [Man] Winner-- Steve Tong!
{37203}{37239}You did it !
{37419}{37479}Sorry I'm late, honey.|I was trying to--
{37491}{37527}I don't wanna hear it!
{37539}{37575}I'm really sorry.
{37731}{37767}- All right ?|- All right.
{37899}{37935}Let's get something to eat.
{38139}{38175}The big pool champ, huh?
{38235}{38294}- You leave us alone!|- Kiki--
{38570}{38606}[ Chuckles ]
{38786}{38822}Back off !
{39050}{39086}[ Screams ]
{39362}{39422}Kiki! Kiki.
{39458}{39493}Oh, Kiki.
{39505}{39541}Someone help!
{39553}{39613}-[Machine Beeping]|-[Steve]Is she going to make it ?
{39625}{39709}Not unless she has|a liver transplant within 24 hours.
{39721}{39757}Your only hope is to buy one|on the blackmarket.
{39769}{39853}But it will cost at least $100,000.
{39865}{39925}I oly know one way to get|that kind of quick cash.
{39937}{39973}[Beeping Continues]
{40225}{40261}Fold.
{40393}{40477}-Just you and me.|- All of it.
{40561}{40597}Call. Let's see it.
{40609}{40669}Okay. Six of clubs.|That's a straight flush.
{40752}{40788}Damn!
{40896}{40980}-Thanks, guys.|-Hey, we need a chance to win it back.
{40992}{41052}- Sorry, I can't. Not now.|- Stop him !
{41088}{41124}Hey, buddy,|my brother said hold on.
{41640}{41724}- Stop him!|- [ People Screaming ]
{42791}{42827}Okay.
{43486}{43546}- Hey, boss, it's Eddie.|- What's up, brother ?
{43726}{43738}Damn it.
{43870}{43906}- Let me through !|- Get back.
{43918}{44002}- You-- You-- Get back.|- That's my brother.
{44038}{44074}Move it.
{44206}{44242}Who did it ?
{44254}{44289}- He's over there.|- Okay.
{44397}{44433}Out of my way!|Let me at him!
{44445}{44481}That was my brother|you kiIIed, asshole !
{44493}{44553}You're history !|You hear me ?
{44565}{44649}Come on!|You're dead, motherfucker !
{44661}{44697}- Okay.|- Enough!
{44709}{44745}How are we gonna kill him while|he's under police protection ? 
{44757}{44793}Shut up!
{44877}{44937}There's always a way. Let's go!
{44949}{44985}Welcome to your new home.
{44997}{45057}You'll refer to the guards|as ''boss'' or ''sir.''
{45069}{45153}We run a clean shop here. Smoke in|your cell, that's ten days in the hole.
{45165}{45249}Spit, piss, shit|on the prison floor, that's 20.
{45261}{45345}Unsupervised fighting gets you|a month without daylight.
{45357}{45393}Don't talkback, disobey--
{45405}{45441}[ Chattering ]
{45908}{45944}Hey, Charlie.|Who's the new guy ?
{46028}{46088}Believe me,|you don't wanna know.
{46124}{46136}How come?
{46220}{46280}That guy killed Boss Lee's brother.
{46292}{46328}His days are numbered.
{46556}{46640}Don't forget your protein.|[ Chuckling ]
{49313}{49349}- Son of a bitch !|- The warden !
{49745}{49805}Let go!|Get him outta here!
{50009}{50069}Sir, warden.|Those two tried to kill him.
{50177}{50284}Bullshit. They were fighting.|We tried to stop it.
{50296}{50356}Let's have the truth.
{50368}{50428}Search him.|He's got the shiv.
{50632}{50692}No shiv.
{50704}{50764}Well, that's because|he ditched it.
{50776}{50812}Here it is.
{50944}{51004}Do you have a brain inside there ?
{51088}{51148}- The hole.|- Let's go!
{51471}{51507}I need a vacation.
{53534}{53570}Lucas.
{53654}{53714}You fuck up again,
{53726}{53786}I promise, you'll die down here.
{53869}{53953}You're the kind of guy that can fart.
{53965}{54025}Doesn't have the shit to back it up.
{54181}{54217}[ Men Cheering ]
{54685}{54721}Brothers!
{54733}{54793}If they can't take a joke,|then fuck 'em!
{54805}{54841}[ Cheering ]
{55308}{55344}Come in.
{55500}{55560}Y-You wanted to see me ?
{55572}{55608}Sit down.
{55860}{55920}I hear you've been|asking about Carl Chang.
{55932}{55968}- Yeah. So ?|- Be straight!
{55980}{56016}Be straight ?|[ Screams ]
{56028}{56088}You see, I've noticed something.
{56100}{56136}You've got pretty, small hands.
{56148}{56208}They're little sissy hands,
{56220}{56256}like the hands of a cop.
{56267}{56327}You've got it wrong.
{56387}{56423}[Lucas]|TaIk!
{56459}{56567}A few years ago, Chang and I|were in the army together.
{56579}{56639}- We kept in touch and--|- What do I care?
{56651}{56759}He borrowed money to buy|his... girlfriend a new set of tits.
{56771}{56831}- I just wanna collect.|- That's bullshit.
{56915}{56999}[ Screaming ]|Come on, Lucas.
{57011}{57047}Think about it.
{57059}{57143}Would I really make up|a story that stupid ?
{57155}{57191}[ Groaning ]|Please, Lucas !
{57371}{57455}You're tougher than I thought,|but not as tough as Carl Chang.
{57490}{57574}And he's dead. Understand ?
{57754}{57790}- Andy, over here.|- Okay.
{57922}{57982}- Is that chicken ?|- Ifwe're lucky.
{57994}{58030}What's with your hand?
{58138}{58198}Um, ask your wife about it.
{58210}{58246}All right.
{58258}{58318}Just for that, funny boy,|you go to bed hungry.
{58881}{58917}Eat up.
{58953}{59013}Thanks anyway, Lucas, but...|you'll get busted.
{59169}{59229}- What's your problem ?|- On a diet.
{59241}{59277}We got a dieter here!
{59409}{59445}Move it.
{59529}{59589}We like our convicts strong|for the chain gang.
{59601}{59661}So eat every grain,
{59673}{59733}or it's back to the hole foryou.
{60200}{60212}[ Chuckling ]
{61135}{61195}Lucas, save some for me.
{62838}{62898}Now listen up, you maggots,|and pay attention!
{62910}{62994}This road has to be|completely finished by tonight.
{63006}{63090}If it isn't, you go without|dinner and conjugal visits.
{63102}{63162}Hey, boss! How about|if we finish early ?
{63222}{63258}Are you kidding?
{63270}{63354}I'll put on leotards and dance|a ballet. Now let's get going !
{63965}{64073}Hey, guys. It's a long road.|Why wear yourself out ?
{64085}{64145}I don't know about you,|but I'm a cultured guy,
{64157}{64217}and I miss the ballet.
{64277}{64337}Hey, that's right.
{64349}{64409}Let'spick it up, and|the boss puts on leotards.
{64421}{64457}Let's go !
{64517}{64553}Yeah!
{64684}{64768}Way to go ! Good work !|Yeah !
{65164}{65200}Move it!
{65308}{65344}All right.
{65404}{65440}Water, sir ?
{65524}{65560}- What's gotten into them ?|- They're inspired.
{65572}{65632}[ Laughs ]
{66411}{66447}Yeah! Come on, guys!|We're almost there!
{66459}{66495}[ Laughing ]|Yeah !
{66915}{66975}I can't believe that they're finished...|two hours ahead of schedule.
{67178}{67238}- Plenty of time for Swan Lake.|- [ Cheering ]
{67970}{68006}Move your sorry ass.
{68281}{68317}Don't let 'em see this.
{68329}{68365}Thanks.
{68449}{68509}So.
{68521}{68605}Tell me. Anything exciting|happen while I was locked up...
{68617}{68677}in the hole and left for dead?
{68689}{68749}Oh, yeah. Boss man.
{68761}{68797}He promised to dance in a tutu,
{68809}{68893}but the asshole|reneged on the deal.
{68905}{69013}That's too bad. A man should|always keep his promises.
{69025}{69061}Yougot that right.
{69073}{69157}I tell you, a man who|doesn't keep his promises..
{69169}{69205}ain't worth shit.
{69241}{69349}I promised my son I will see him|again. I must see him.
{69361}{69373}No way,John!
{69385}{69492}I got special plans for|the next escape. I'll be fine.
{69504}{69540}Yeah, right.
{69552}{69636}Hey, I remember the first time|I saw The Great Escape.
{69648}{69708}What a great movie.|But you're no Steve McQueen.
{69720}{69780}[ Laughing ]
{70440}{70524}[Man]|Oh, baby! Nice!
{70536}{70620}- Putting on glasses, boss!|- Oh ! Oh !
{70632}{70691}Oh, my God !Look at her !
{70775}{70835}Holy mother,|I wish I could see !
{70847}{70931}Oh, man. Next time I fuck my hand,|I'm gonna be thinking about her.
{70943}{71003}You watch your filthy mouth.
{71015}{71051}That's my future wife|you're talking about.
{71063}{71171}- Oh, honey!|- I can't see my bride-to-be.
{71183}{71219}Taking off glasses, boss!
{71375}{71411}- Damn!|- [ Laughing ]
{71495}{71531}Is there a mechanic in the house ?
{71543}{71579}-John!|- Sir!
{71591}{71627}- Help her.|- Yes, sir!
{71711}{71795}Hello, miss. No problem.|My pleasure.
{71854}{71890}[Laughter]
{71926}{71986}- Are you okay?|- Believe me,
{71998}{72058}you have no idea|how good I feel right now.
{72070}{72130}[ Laughing ]
{72142}{72202}I gotta-- Could you|go back around and...
{72214}{72250}rock the car back and forth ?
{72262}{72298}Yeah. Like that.|Thanks.
{72598}{72634}Wow.
{72814}{72850}[Men Chattering]
{72910}{72970}[John ] All right. The horses|are at the starting gate.
{72982}{73042}Get your bets down.|Hurry up, guys.
{73053}{73113}Let's get this show on the road.
{73125}{73161}- Come on, huh ?|- Hey,John.
{73173}{73209}That fox gave me|some major wood.
{73221}{73281}- [ Laughs ]|- Let me tell you. I was so horny,
{73293}{73353}I changed her tire|without using the jack.
{73365}{73401}Huh ? Really ?
{73413}{73449}Watch yourself, Sega.
{73557}{73593}All bets in! |Ding, ding, ding! 
{73605}{73665}They're off!. Go, go!
{73965}{74025}Your Jumbo lost again.|Time for glue factory.
{74037}{74073}How about a smoke ?|Huh,Johnny, huh ? 
{74085}{74145}- Huh ?|- Here.
{74229}{74288}Now don't say I never|did nothing forya.
{74300}{74360}Hey.
{74996}{75056}[Lucas]Iknow Steve's in|for killing BossLee's brother,
{75068}{75152}andI know you're|looking for payback.
{75188}{75272}But I don't want any|contract killings on my cell block.
{75284}{75344}And I mean it.
{75356}{75392}I want you guys to shake on it.
{75404}{75511}You're crazy. I won't shake hands|with this... asshole.
{75523}{75583}Crazy ?|I'll show you crazy.
{75811}{75847}Next, I go crazy on your face.
{76267}{76303}Hey, Andy, have you seen Goliath ?
{76315}{76375}He's probably out|screwing that gerbil again.
{76387}{76447}- We'll find him after lunch.|- Okay.
{76483}{76543}Here.|You need some extra protein.
{77298}{77334}Why ? Why'd you do it ?
{77370}{77406}Why'd you do it? |Why'd you do it ?
{77634}{77694}Kill that asshole!
{77849}{77909}- [Man] Why you stopping it? |- The hole... right now!
{77921}{77957}[ Grunts ]
{78065}{78101}[ Groaning ]
{78665}{78725}Great shot, sir !
{78809}{78845}[ Panting, Laughing ]
{78905}{78941}And we get the slop.
{79336}{79372}[ Grunts ]
{79384}{79420}[ Chortles ]
{79696}{79732}Here. Eat.
{79912}{79948}[Men Chattering, Laughing]
{79984}{80020}Gonna dump a load, boss.
{80056}{80092}Oh, Christ.|Just go down wind, will ya ? 
{80128}{80164}Hey, make sure I always|know where you are.
{80176}{80212}Yes, sir.
{80655}{80691}Give him one.
{80775}{80811}Hey, I-I'm here, boss. I'm here.
{80823}{80859}[ All Laughing ]
{80919}{80955}[Gun Cocks]
{80991}{81051}Still shitting, boss.|Still shitting.
{81063}{81171}-[ Men Laughing ]|-Spare me the details. I'm still eating.
{81327}{81363}[LaughterContinues]
{81399}{81435}[Gun Cocks]
{81806}{81842}That fat bastard.|Spread out and find him!
{81950}{81986}[CarEngineStarts]
{82070}{82106}[ Murmuring ]
{82142}{82178}Captain!
{82430}{82490}We'll steal another car after sunup.
{82550}{82586}Or maybe a boat.
{82645}{82705}When you busted out,|why'd you take me along ?
{82741}{82801}It seemed like the right thing|to do at the time.
{82837}{82921}But I thought you wanted...|to see your son.
{82933}{82993}Sure. I will.
{83125}{83185}[Sirens Wailing]
{83341}{83401}Youset me up.|Why'dyou do it ?
{83413}{83497}Sorry. I made a deal...
{83509}{83569}so I could see my son again.
{83581}{83617}They promised me you'd|only get a little time...
{83629}{83665}in the hole.
{83773}{83809}[CarDoors CIosing]
{84012}{84048}[Gunshot]
{84060}{84096}[ Gasping ]
{84108}{84168}[Body Hits Ground]
{84324}{84360}Lucas, no!
{84444}{84528}You promised me he wouldn't|get hurt ! You promised !
{84540}{84576}That's the way|the cookie crumbles.
{84612}{84624}Take him away !
{84684}{84720}You fuckin' bastard !
{84732}{84768}[ Laughs ]
{84780}{84816}That's because|my mom's a whore.
{84828}{84888}You know, you should worry less|about my family tree...
{84900}{84960}and more about|what we're gonna do to you.
{84972}{85008}Move it !
{85451}{85535}[Guard]Rise and shine,|sweethearts. Rise and shine.
{86362}{86398}I wanted you all to see this.
{86554}{86686}Like I told you all before,|it's stupid to try and escape.
{86698}{86782}As you can see, not even|the great Lucas can dodge a bullet.
{87585}{87621}[CharIie's Voice]|''Sorry it's only a potato.
{87633}{87693}''Next time I'll try|sneaking in a steak.
{87705}{87741}Your friend, CharIie. ''
{87849}{87909}[ Chuckles ]
{87921}{87957}[DoorOpens]
{88281}{88317}[ Grunting ]
{88425}{88461}Chuck's out of the joint, boss.|He's upstairs.
{88473}{88509}Thanks.
{88856}{88916}Good to see you, Chuck.|What's going on inside ?
{88928}{88940}Tell me.
{88952}{89012}That guy who killed|your brother is still alive.
{89024}{89060}The hit you put out|didn't go down.
{89144}{89204}- Are you serious ?|- As serious as a heart attack, boss.
{89312}{89372}Take Chuck downstairs|and make him comfortable.
{89384}{89420}Set him up in the casino.|The works. Go on.
{89552}{89588}Hey, brother.
{89648}{89684}What's wrong ?
{89696}{89780}That dumb-ass I hired|to kill Steve fucked up.
{89816}{89851}Damn!
{89887}{89923}Guess it's up to us.
{89935}{89971}Fuckin' ''A.''
{90127}{90187}Boss, hang on. I'll do it.
{90631}{90643}Water, boss?
{90727}{90763}More noodles, boss ?
{90847}{90883}[FIyBuzzing]
{90895}{90979}Shoo ! Eat up.|Shoo !
{90991}{91050}Snake ! Holyshit !
{91062}{91098}-[Men Yelling]|- [ Hissing ]
{91134}{91170}I'll get your gun, boss.
{91182}{91242}[Men Continue YeIIing]
{91446}{91482}[ Car Engine Starts ]
{91542}{91578}[Gunshot,|Glass Breaks]
{91878}{91914}Davis is dead !
{91926}{91986}Get that fat fuck|outta here !
{92453}{92489}[DoorOpens]
{92813}{92849}[DoorCIoses]
{92861}{92921}[Man]Prisoner John Liu,|having been found guilty...
{92933}{92969}of the murder|of a corrections officer...
{92981}{93017}during your third|escape attempt,
{93029}{93065}it is the judgment of this court...
{93077}{93113}that you shall be executed|before a firing squad.
{93149}{93185}Sentence to be carried out|forthwith.
{93197}{93233}God have mercy|on your souI.
{93245}{93281}[Gavel Strikes TabIe]
{93964}{94048}[ Gasping ]
{94564}{94600}Lieutenant, what's up ?
{94612}{94647}Routine check.
{94659}{94719}Another one?
{94731}{94815}I want a new speedboat, but I can't|swing it on a cop's salary.
{94899}{94935}- A speedboat, huh ?|- Oh, you know.
{94947}{95007}I figured I'd pay a visit.|Roust a few of your customers.
{95163}{95247}Check for contraband.|Unless you convince me not to.
{95307}{95391}- Like, with a new speedboat.|- [ Gargles ]
{95403}{95439}[ Exhales ]|Hey, I like that.
{95451}{95487}Yeah.
{95547}{95607}Come on, man. Why don't|we go back to my office...
{95619}{95679}and seal the deal, huh?
{95763}{95775}Oh, yeah.
{95906}{95942}What's he want ?
{96002}{96062}Why don't you make out|a check ? Standard fee.
{96722}{96830}Yeah, I'm gonna look mighty fine|on my new speedboat.
{96842}{96902}Toolin' on the water.
{96914}{96998}Hey, maybe I'll take you guys|out fishing sometime. Huh ?
{97033}{97093}Get some trout.
{97105}{97165}Uh, guess it's time to go.
{97345}{97405}[ Grunts ]
{97417}{97453}[ Groaning ]
{97777}{97837}I didn't mean to hurt you|that bad, Lieutenant.
{97873}{97933}But I just gotta get|into that prison, you know ?
{97993}{98005}Ready ?
{98089}{98197}A busted nose, a few bruises|for a new speedboat ?
{98209}{98268}I can already see you|cuttin' through the waves.
{98304}{98316}Not a bad deal, huh ?
{98640}{98676}Let's get outta here!
{98688}{98724}Hang on.
{98736}{98772}[PoIice Radio Chatter]
{98784}{98820}- Later, bro.|- Yeah.
{98880}{98916}Back to work.
{98928}{98964}[ Guard ]|Welcome to your new home.
{99000}{99060}You will refer to the guards|as ''boss'' or ''sir.''
{99072}{99108}We run a clean shop here.
{99120}{99180}Smoke in your cell,|that's ten days in the hole.
{99192}{99276}Spit, piss on the prison floor,|that's 20.
{99288}{99348}Unsupervised fighting|gets you a month without daylight.
{99384}{99467}Don't talkback, disobey orders|or break any rules.
{99479}{99539}If you follow these rules during|your stay in this fine institution,
{99575}{99635}you and I will get a long just fine.
{99647}{99755}That is all that you need to remember|during your stay with us here.
{99791}{99851}Oh, one more thing.
{99863}{99947}If you drop the soap in the shower,|you're on your own.
{99959}{100043}Now get your sorry ass in there|and you behave yourself.
{100678}{100738}Why is he alive ?|I gave you an order.
{100750}{100810}- You don't understand.|- Yes, I do.
{101110}{101146}Good luck, Steve.
{101206}{101242}Yeah,
{101254}{101314}you'll need it with Boss Lee|coming after you.
{101326}{101362}[ Laughs ]
{101782}{101865}I'm sorry about your brother.|It was an accident.
{101925}{102009}How dare you|talk about my brother.
{102021}{102057}Just shove your apology.
{102093}{102177}I promise you...|your trip to hell won't be easy.
{102261}{102321}You're gonna suffer,|just like your girlfriend.
{102405}{102417}How would you know ?
{102453}{102489}[ Chuckles ]
{102501}{102537}I heard about it.
{102549}{102609}At least she had a chance.
{102621}{102657}That's more than|my brother had.
{102693}{102777}Now listen.|No more excuses.
{102789}{102825}Tonight, it'sjust you and me.
{103340}{103376}[Man]Hey, Igot five to one|on Boss Lee. Any takers ?
{103388}{103424}Come on. Come on.|Who wants some of this action?
{103436}{103496}Come on. Come on.|Oh, yeah, I got you covered.
{103604}{103664}[Man] Okay. Allright.|Here wego. Here we go.
{103676}{103712}Ah, this is the easiest money|I ever--
{103724}{103760}[Men Laughing]
{104084}{104144}Let'sgo.
{104275}{104359}[Man] That's woman's bet.|That' a woman's bet.
{104443}{104479}[Men Chattering]
{106793}{106829}Ha! Do it !
{106913}{106997}[ Men Yelling ]
{107009}{107069}Kill ! Go on ! Kill ! Kill !
{107081}{107117}I know.|I know you can do it.
{107129}{107213}Go on.Just like|you killed my brother.
{107225}{107261}Don't do it ! Put it down !             
{107321}{107381}- Kill !|- Don't do it !
{107441}{107477}Now!
{107896}{107956}- [Gunshot]|- [ Groans ]
{108184}{108268}- [ Spits ]|- [ Panting ]
{108280}{108316}Stop ! Think about it !
{108328}{108412}There's a lot of witnesses here|that would love to see you fry.
{108424}{108460}[ Panting, Gasping ]
{108904}{108940}[Man]Pay up. Pay up.|Pay up. Pay up.
{108952}{109035}Come on. Come on. Pay up.
{109095}{109155}[ Chattering ]
{109311}{109395}Happy New Year! [ Laughs ]
{109743}{109779}Sit down.
{109887}{109947}What do you need, boss ?
{109959}{109995}[DrawerOpens]
{110079}{110139}Need you to deliver a vaccine.    
{110151}{110187}[ Men Laughing ]
{110846}{110882}A game's going on.
{111110}{111146}- You gonna try ?|- Uh-huh.
{111158}{111194}- I'll get some money.|- Oh, that's okay. I'll float you.
{111230}{111242}Are you kidding,|with the interest you charge ?
{111278}{111290}- I'll get mine.|- Well, hurry.
{111350}{111386}[DoorOpening]
{111565}{111649}[Screaming]
{111661}{111745}- Charlie!|- [ Screaming ]
{111757}{111793}Let me through!|Get out of my way ! Move !
{111829}{111913}Charlie ! Charlie !
{111925}{111985}Charlie ! No, Charlie ! 
{112117}{112201}Charlie ! Charlie !
{112453}{112537}[ Growls, Yells ]
{112836}{112872}You fucker, I'll kill you !
{112884}{112944}It's not... my fault.
{113196}{113232}Men, drag this trash out of here.
{113244}{113280}- Yes, sir.|- Yes, sir.
{113340}{113400}You're the one|who wanted Andy killed.
{113412}{113472}Charlie wasa mistake.
{113484}{113520}I'm not going to take|the fall for this myseIf.
{114131}{114191}-[AIarm Sounding]|-[Whistle Blows]
{114515}{114551}[ Groans ]
{114635}{114671}[GIass Breaks]
{114755}{114791}[Gunshot]
{115162}{115198}[Man]|Breakit up. Breakit up.
{115258}{115294}[Man]|Get back !
{115402}{115486}Prisoner Andy Lau,|having been found guilty...
{115498}{115558}of the murder of|the head corrections officer,
{115570}{115678}you are here bys entenced to be|executed by firing squad forthwith.
{115738}{115798}Godh have mercy onyour soul.
{116265}{116301}No !
{116337}{116421}[ Grunts ] No. No.
{116457}{116469}[ Groans ] Oh.
{116625}{116661}[ Grunts ]
{116745}{116805}[DoorOpens]
{117416}{117500}That's your funeral.|Your girlfriend cried her eyes out.
{117512}{117572}So sad her man was executed.
{117656}{117716}But don't be depressed.
{117728}{117788}It was a beautiful service.
{117800}{117836}It could have been|a lot worse.
{117848}{117932}Be thankful you weren't buried with only|a grave digger to mourn your passing.
{117944}{118004}So, now you're a dead man,
{118016}{118100}as far as the rest|of the world is concerned.
{118112}{118244}Think of it this way. You've been|given a second chance.
{118256}{118340}But don't forget, I'm the one|who saved you from execution.
{118400}{118436}Quid pro quo.
{118448}{118484}I helped you,|now you help me.
{118496}{118556}One quick job|and I'll give you a new identity...
{118568}{118604}so you can start over.
{118615}{118651}Anywhere but here.
{118663}{118723}But don't go against me, okay ?
{118759}{118795}Or I promise you...
{118807}{118843}you'll go before a firing squad,
{118855}{118891}and this time for real.
{119023}{119083}I've seen every kind of scum there is|come through this prison,
{119095}{119179}except the scum|that rises to the top.
{119191}{119227}Criminals so powerful,
{119239}{119323}they can buy their freedom|by paying off judges and juries.
{119335}{119467}And that's why I use men like you|to carry out the final sentence.
{119695}{119731}Colonel Song...
{119743}{119803}is one of the most dangerous|drug dealers in south east Asia.
{119814}{119874}He's being extradited today|to stand trial,
{119886}{119946}but I know he's already|bought himself an acquittal.
{119958}{120018}The only way to stop him|is to take him out,
{120030}{120066}and that's your assignment.
{120078}{120162}After you carr yout the execution,|a jeep will be waiting for you...
{120174}{120210}at the north end|of the airport.
{120222}{120306}Inside that jeep are yournewp apers|anda second chance at life.
{120390}{120450}[ Cameras Clicking ]
{120510}{120570}[Reporters Yelling,|Chattering]
{120942}{121002}[ Chattering Continues ]
{121517}{121601}[Reporter] Colonel, how|do you respond to allegations that you're a drug Lord ? 
{121637}{121697}- Innocent.|- [Reporters Chattering]
{121973}{122033}[ Reporters Screaming ]
{122189}{122224}Let's go !
{122356}{122392}Go!
{122572}{122608}What are you waiting for ?
{122692}{122752}- There's a bomb in the jeep!|- [ All Gasp ]
{122908}{122944}- [RapidGunfire]|- Aah!
{123819}{123855}Hey.
{124634}{124670}Come on.
{125474}{125510}John, over there.
{125786}{125821}No. Please don't kill me.|I have a wife and kids.
{125833}{125869}Shut up, son of a bitch!|All I wanna know is:
{125881}{125917}Can you fly that plane out there ?
{125929}{125965}I-I can fly it.
{126049}{126085}[Man] Move ! Move !
{126097}{126133}Don't shoot me, please !
{126145}{126181}Now tell them we're gonna|fly out of here.
{126193}{126229}And don't fuck with me|or you're dead. Got it ?
{126241}{126301}Yeah.
{126313}{126325}Hold your fire out there.
{126337}{126397}They're taking over the tower|and got me as a hostage.
{126481}{126517}[Man]| Stay strong. Keep going.
{126553}{126589}What are their demands ?
{126601}{126709}They want me to fly them out of here,|so hurry up and fuel that plane.
{126721}{126781}Okay, I'll do it.
{126793}{126829}Hey, get that plane|ready for take off.
{127200}{127260}Okay, you tell them|we're coming out.
{127272}{127332}Please, hold your fire.|We're ready to board the plane.
{127344}{127404}We'll give them safe passage.|Just don't do anything stupid.
{127416}{127476}What do you think|I'm gonna do ? 
{127488}{127524}They got a gun up my ass.
{127704}{127740}Go !
{127824}{127860}Wait up, guys.
{127872}{127908}Why don't we go back and...|[ Spits ]
{127920}{127980}give the warden|a taste of his own medicine ?
{127992}{128028}- Warden ?|- I wasn't talking to you.
{128040}{128076}[HeIicopter Approaching]
{128279}{128315}Fill the gaps, boys!
{128399}{128435}Make that shot count.
{128495}{128531}Move! Move! Move!
{128639}{128675}Cover that perimeter now!
{128759}{128819}Hold your fire !
{128831}{128891}Split troops !
{128903}{128963}Move to the left.
{128975}{129059}- Steady!|- [ Gunshot ]
{129095}{129155}Go! Charge!
{129215}{129251}I want them alive!
{129383}{129418}Go on! Start it up!
{129478}{129514}[Gunfire]
{129526}{129562}Hurry! Come on!
{129718}{129778}They can't make it.|We gotta slow it down.
{129790}{129850}- It won't get off the ground.|- That's it. Move it!
{129886}{129922}Come on!
{130246}{130282}[ Growling ]
{130438}{130498}[ Both Groaning ]
{130582}{130617}[ Airplane Whirring ]
{131517}{131553}Looking for your gun ?
{131613}{131673}I thought we were|supposed to be a team.
{131733}{131816}Yeah, you're right.
{131828}{131864}Good to see you.
{131948}{132008}You seem surprised I made it.
{132020}{132056}[ Chuckles ]|Well, you shouldn't be.
{132116}{132152}The others were all killed.
{132188}{132224}Just like you expected me to be.
{132236}{132272}[ Scoffs ]|Now wait.
{132284}{132344}Don't be upset.
{132356}{132416}I promise to make this whole thing|worth your while.
{132428}{132464}What do you say?
{132524}{132560}This better be good.
{132644}{132704}There's just one thing.
{132716}{132776}Why all this trouble|over one lousy drug lord?
{132788}{132848}We were partners.
{132860}{132920}I'd be dead if he testifiied.
{132932}{132992}And the commissioner ?|Why did he have to die ?
{133075}{133159}His investigation, uh,|was getting too close to me.
{133195}{133279}[ Gun Clicks ]
{133291}{133375}[ Chuckles ]|You dumb shit.
{133387}{133471}The commissioner's the one|who brought me in to bust you.
{133483}{133519}[ Chuckles ]
{133531}{133567}[ Sighs ]
{133675}{133759}Your old man didn't realize|how much money was involved.
{133771}{133807}You and me, huh ?
{133819}{133879}You sick bastard.|You don't quit, do you ?
{133891}{133975}Quit ? Why should I ?
{133987}{134071}With all this money,|I'd be a fool to quit.
{134083}{134143}You know how much money we could|make playing both sides of the fence ?
{134155}{134214}- How many more good men have to die ?|- Huh ?
{134346}{134406}You can shove your precious money|up your ass...
{134418}{134454}'cause I'm giving you|a first-class ticket to hell!
{134466}{134502}Andy, don't!
{134538}{134574}We've got everything on tape.
{134586}{134646}He's going away for good.|You did it.
{137344}{137356}Subtitles by|Captions, Inc. Los Angeles ; Edit by Namlazy